ISSUE = {
    "date_iso":  "2026-09-23",
    "kicker":    "Crux Media // Wednesday 23 September 2026",
    "tagline":   "What brands did on YouTube yesterday, and whether it worked.",
    "pace":      "STEADY",
    "next_drop": "Next drop: Thursday, 06:30 MT",
}

LEAD = {
    "headline": "OPENAI HIRED THE MAN WHO BUILT CREATOR SUBSCRIPTIONS, AND THE SAME MORNING BROUGHT WORD THAT ITS SPONSORED POSTS FOR CHATGPT HAVE GONE FROM 61 A MONTH TO 141",
    "deck": "Sam Yam co-founded Patreon thirteen years ago and ran its technology.  This morning he said he is joining OpenAI to lead Creator Product, and taking Patreon's former head of product and head of engineering with him.  Hours later Business Insider published the other half: OpenAI's sponsored creator posts for ChatGPT have more than doubled since June.  One company is now buying the pipe creators get paid through and the creators themselves.",
    "stamps": [
        ("THE VERGE · 23 SEP", "https://www.theverge.com/ai-artificial-intelligence/999249/openai-creators-patreon-execs-hire-sam-yam"),
        ("BUSINESS INSIDER · 23 SEP", "https://www.businessinsider.com/inside-open-ai-influencer-marketing-strategy-chatgpt-ads-sponsorships-instagram-2026-9"),
        ("TECHCRUNCH · PATREON ROADMAP", "https://techcrunch.com/2026/08/20/patreon-launches-30-new-creator-features-including-short-form-clips-and-revamped-discovery/"),
    ],
    "body": [
        "Take the hire first.  <mark>Yam is a Patreon co-founder and its technology chief, and he is going to OpenAI to lead Creator Product.  Drew Rowny, Patreon's head of product, and Shannon Ma, its head of engineering, both stepped down in the last few weeks and are going with him.</mark>  His own words: we are going to build together with Creators at OpenAI and share early access to a new set of tools that I think will be critically valuable to Creators and their communities.  Then a pointer — pay attention to OpenAI DevDay next week.  That is Tuesday 29 September.",
        "Be clear about how thin the sourcing is, because it matters.  <mark>The entire story is Yam's own post on X, written up by The Verge.  Neither OpenAI nor Patreon has said anything, and no other outlet has done original reporting on it.</mark>  Nobody has described a product.  What we have is three senior people who spent a decade building the largest creator subscription business moving together into the company with the largest consumer artificial intelligence audience, and a date next week.",
        "Now the same-day half nobody is connecting to it.  Business Insider reviewed dozens of sponsored posts and spoke to six managers and creators.  <mark>Sponsored Instagram posts promoting ChatGPT went from 61 in June to 122 in July to 141 in August, according to the creator analytics company HypeAuditor.</mark>  The targets are parenting and fitness creators alongside technology ones.  The pitch, in the words of a talent manager and of one campaign brief seen by Business Insider, is to show why ChatGPT is cool, or how it supports work that is good for the world.  The Shade Room, a meme account with more than 28 million Instagram followers, ran a ChatGPT-made word search in early September.",
        "Here is the mechanism, and it is the part that costs you money.  <mark>OpenAI is not buying customers with these posts.</mark>  One creator who worked on a July campaign, Natasha Badger, put it flatly: most people following any of us have ChatGPT already, they don't need to convert users.  A buyer who is purchasing how a product is regarded rather than how many people sign up has no payback figure to answer to.  Nothing stops it bidding.  Every brand competing for the same parenting or fitness creator is now bidding against a company that cannot lose the auction on the arithmetic, because it is not doing the arithmetic.",
        "And the other side of the hire is a price you have not been quoted yet.  If OpenAI ships a way for creators to charge their audience inside ChatGPT, then some part of a creator's income stops depending on advertisers entirely, which changes who needs you and on what terms.  <mark>Patreon has paid out more than ten billion dollars to creators since 2013 and carries more than 25 million paid memberships, and the three people who built that are now inside the company you are trying to buy attention next to.</mark>  Nobody has announced anything.  DevDay is in six days and you should watch it as a buyer, not as a technology story.",
        "One honest caution on the numbers.  <mark>Nobody has published what OpenAI pays creators — no fee, no budget, no headcount for the programme, not in Business Insider's reporting and not anywhere else.</mark>  Numbers circulating on aggregator sites about premiums and seven-figure fees are not in the reporting and we have not used them.  The 61 to 141 figures are HypeAuditor's count of Instagram posts only, so they say nothing about YouTube, and post volume is not spend.  It is still the clearest evidence available that the buying got much heavier over one summer.",
    ],
    "numbers": [
        ("141", "sponsored Instagram posts for ChatGPT in August, up from 61 in June, counted by HypeAuditor"),
        ("3", "Patreon executives moving together, including the co-founder who built creator subscriptions"),
        ("0", "figures published by anyone on what OpenAI pays creators, or on the size of the programme"),
    ],
    "flagnote": "The hire is single-sourced to Sam Yam's own post on X, reported by The Verge.  There is no OpenAI statement, no Patreon statement and no independent reporting from any other outlet, so treat everything about OpenAI's intentions as inference rather than plan — The Verge itself says only that the hire suggests OpenAI is exploring creator monetisation.  Business Insider reviewed dozens of sponsored posts, which is not a precise count, and spoke to six managers and creators.  The 61, 122 and 141 figures are HypeAuditor's count of sponsored Instagram posts and cover Instagram only.  No payment, budget or programme-size figure exists in any source we found; figures on creator fee premiums circulating on aggregator sites do not appear in the Business Insider article and are that site's own commentary.  Patreon's ten billion dollar payout and 25 million membership figures are the company's own, stated in August 2025, and are context rather than part of today's news.",
    "so_what": "A buyer purchasing sentiment rather than sign-ups is the most dangerous kind of competitor in a creator auction, because it has no cost per customer to defend and therefore no ceiling.  That is what has arrived in parenting, fitness and technology creator inventory over one summer, and it is why your renewals are about to read differently.  The hire is the longer fuse: if creators can be paid directly inside a product with hundreds of millions of users, advertising stops being the only cheque that arrives, and a creator with two income lines negotiates differently from one with one.",
    "do_this": "Pull the last three quotes you received from creators in parenting, fitness or technology and compare them with the same creators' quotes from June, before the sponsored-post count doubled.  Where a price has moved more than about a fifth with no audience change behind it, you are bidding against a reputation buyer, so move that money to a category they are not in rather than matching the price.  Then put DevDay on 29 September in your diary and watch it for creator payment tooling specifically.",
}

SECTIONS = [
    {
        "id": "ws", "name": "W'S", "page": "pg. 02",
        "note": "what worked, and the exact reason it worked",
        "tint": "blue",
        "items": [
            {
                "title": "A discount furniture chain is the only brand in the whole branded-series boom with a published sales figure, and it got there by making the show about buying furniture",
                "hook": "152 million views and nearly nine million dollars of attributed sales.  Everyone else made something entertaining.  Bob's made something about the purchase.",
                "open": True,
                "stamps": [
                    ("DIGIDAY · 23 SEP", "https://digiday.com/marketing/r-i-p-quibi-you-would-have-loved-microdramas/"),
                    ("BOB'S · SEASON TWO · 17 SEP", "https://www.stocktitan.net/news/BOBS/bob-s-discount-furniture-turns-social-content-into-sales-with-season-dyaas84px0vc.html"),
                    ("CAMPAIGN US · 3 SEP", "https://www.campaignlive.com/article/15b-rise-branded-microdrama/1969129"),
                ],
                "body": [
                    "The series is Till Decor Do Us Part, from Bob's Discount Furniture, and season one ran in summer 2025.  <mark>More than 152 million video views, 223 million impressions, and nearly nine million dollars in attributable sales, all figures the company reports itself.</mark>  Season two was announced on 17 September: six creator couples across California, Maryland, Ohio and Pennsylvania, weekly through the autumn, with Gabby Bryan returning to host.",
                    "The format is the item.  Couples who disagree about furnishing their home get the disagreement settled on camera.  <mark>The subject of the show and the subject of the purchase are the same thing.</mark>  A viewer watching two people argue about a sofa is already doing the mental work of choosing a sofa, which is why the path from watching to buying is a short one rather than a leap of faith.",
                    "Now compare it with the cohort it keeps getting filed alongside.  Digiday reported this morning on branded microdramas — short scripted serials, a format that arrived from China — and named Crocs, Nuuly and Procter and Gamble's Native as brands making them.  <mark>Four marketers told Digiday there is no clear business case yet.</mark>  Sean Akaks of SonderCo: there is enough signal to prove that there is demand for this content, there are the views, there are the engagement, but the final loop is how does this drive business impact.",
                    "The honest distinction, because it is the whole lesson.  <mark>Bob's is not making a scripted drama.  It is making a social reality series about the category it sells in.</mark>  The received advice on branded entertainment is to make something good enough that people forget it is an advertisement.  Bob's did the opposite — it put the product decision on screen as the plot — and it is the only one in this group that can show you a sales figure.",
                    "One more piece of context on scale.  <mark>Omdia expects roughly 1.5 billion dollars of United States consumer revenue from microdramas in 2026</mark>, reported by Campaign US on 3 September, so the audience is genuinely there.  What is not there, for anyone except Bob's, is a published number connecting that audience to money.",
                ],
                "flagnote": "The 152 million views, 223 million impressions and nearly nine million dollars in sales are all reported by Bob's Discount Furniture about its own campaign, with no methodology disclosed for how the sales were attributed and no independent audit, so treat the sales figure as a company claim rather than a measured result.  Digiday groups Bob's with scripted microdramas; we think that is the wrong bucket and have said so, which is our judgement rather than anyone's reporting.  The Omdia figure is consumer revenue from microdrama apps, not brand spending, and comes to us through Campaign US rather than from Omdia directly.  No performance figures of any kind have been published for the Crocs, Nuuly or Native series.",
                "so_what": "Branded entertainment converts when the thing being watched and the thing being bought are the same decision, because then watching is already shopping.  Hide the product to make the film better and you have made a better film and a worse advertisement, which is exactly what the marketers quoted this morning are describing when they say the views are there and the business impact is not.  The received wisdom has this backwards and one furniture retailer has the only receipt.",
                "do_this": "Before you commission any branded series, write down in one sentence the decision your customer is making when they buy, then check whether that decision appears on screen in every episode.  If it does not, rewrite the format rather than the scripts.  And set the reporting requirement at commission — attributed sales with a stated method — because nobody in this category is publishing one and yours will be the number everyone quotes.",
            },
            {
                "title": "USA Fencing built the place to convert people before it bought the audience, and put twelve creators with 215 million followers in front of it",
                "hook": "800 clubs with standing trial offers were already live.  The reach was bought second, which is the opposite of how these are usually ordered.",
                "stamps": [
                    ("TUBEFILTER · 22 SEP", "https://www.tubefilter.com/2026/09/22/usa-fencing-creator-showdown-event-new-york/"),
                    ("SPORTICO", "https://www.sportico.com/leagues/olympics/2026/usa-fencing-creator-showdown-olympic-sport-growth-marketing-1234945308/"),
                    ("DIGIDAY · 17 AUG", "https://digiday.com/media/usa-fencing-relies-on-creators-to-attract-new-fans-ahead-of-the-2028-olympics/"),
                ],
                "body": [
                    "The Creator Showdown ran 21 to 23 September at the Heineken Riverdeck in New York.  <mark>Twelve creators with more than 215 million combined followers — Sofie Dossi, Merrick Hanna, itsPikaaa, JoJo Sim and Just Maiko among them — against four Team USA fencers, Maia Chamberlain, Bryce Louie, Mitchell Saron and Lauren Scruggs.</mark>  A one-on-one tournament, a free-for-all, and a round where the four professionals take on several creators at once.  Dolph Lundgren and Mandy Patinkin appear as guests, both of them screen swordsmen.",
                    "Phil Andrews, the chief executive, on what it is for: our goal is to send people to TryFencing dot org where our 800 clubs around the nation have made offers to come in and try the sport.  <mark>The conversion surface existed before the campaign did.</mark>  Not a hashtag, not a landing page built for the event — 800 physical venues with a standing offer, in place, nationally.",
                    "The agency behind it, Creator Showdown, is a London company run by Carsten Thode that has done the same in rugby and cycling.  His diagnosis of why these usually fail is worth keeping.  <mark>A lot of rights holders don't use creators that well, he says.  They give them tickets, or put them on the 50-yard line, or in a hospitality box — and what you get are vanity posts.</mark>  A creator handed access makes a post about being there.  A creator handed a losing fight against an Olympian makes a video about the sport.",
                    "The scale step is steep.  <mark>USA Fencing's creator programme launched in December 2025 and has lifted average monthly impressions 36.9 percent to 4.75 million a month.  This one event was targeted at 60 million impressions and was expected to pass 100 million.</mark>  The whole organisation runs on roughly 17 million dollars a year, mostly membership dues, so this is a small governing body buying reach it could not otherwise afford.  Distribution is USA Fencing's own channels plus the creators' own, across TikTok, YouTube Shorts, Instagram and Snap.  No broadcaster.",
                    "What is missing is the only number that would settle it.  <mark>No club sign-up or trial figure has ever been published from the earlier programme, and none is promised from this one.</mark>  Andrews is already planning a 2027 repeat with a title sponsor attached, which tells you it worked commercially.  It does not tell you anyone turned up at a club.",
                ],
                "flagnote": "No conversion result has been published for this event or for the creator programme that preceded it, so the claim here is about how the campaign is built, not about whether it delivered members.  The 100 million impression expectation and the 60 million target are Digiday's reporting of an advance projection rather than a measured outcome.  Follower reach is stated as more than 215 million by Tubefilter; Digiday's August preview said more than 300 million for the same event, and we have used the later and more specific figure.  The 800 clubs and the standing trial offers are Phil Andrews's own claim.  The 17 million dollar figure is the organisation's entire annual budget, not this campaign's, and combined follower counts are not audience — the same people follow several of these creators.",
                "so_what": "Most creator events are bought in the wrong order: buy the reach, then work out where to send it.  The traffic arrives, finds a hashtag and a highlight reel, and disperses, which is why so many of these produce impressions and nothing else.  Building the destination first means the reach lands on something that can actually take a booking, and it costs almost nothing compared with the campaign because it is mostly asking your existing network to say yes to one standing offer.",
                "do_this": "Before your next creator campaign goes into production, write down the single action you want a viewer to take and check it is live and staffed today, not at launch.  If that action needs your partners, your stores or your franchisees to do something, get them signed up first and count how many said yes, because that number is the ceiling on everything the campaign can deliver.",
            },
        ],
    },
    {
        "id": "ls", "name": "L'S", "page": "pg. 03",
        "note": "what broke, and the failure mode that broke it",
        "tint": "pink",
        "items": [
            {
                "title": "Every YouTube view count went up on 24 August without anybody making a better video, and the smaller the creator the more it went up",
                "hook": "Wrong number.  The figure in the pitch deck and the figure the advertiser is billed against are now two different things, and the gap is widest exactly where you can check it least.",
                "open": True,
                "stamps": [
                    ("YOUTUBE HELP · POLICY", "https://support.google.com/youtube/thread/433409976/an-update-to-how-we-count-public-views-across-youtube?hl=en"),
                    ("TUBEFILTER · AGENTIO DATA · 4 SEP", "https://www.tubefilter.com/2026/09/04/youtubes-new-public-viewcounts-over-report-actual-engagement-by-40/"),
                    ("TUBEFILTER · BRAND CHART · 22 SEP", "https://www.tubefilter.com/2026/09/22/top-5-branded-videos-mrbeast-dr-insanity-maria-vehera-samantha/"),
                ],
                "body": [
                    "The change itself, in YouTube's words: beginning on 24 August 2026, a view will be counted the moment a video begins to play, from the very first frame, and this standard will now apply globally across all formats.  <mark>Before that, a long-form video needed roughly thirty seconds of watching before a view was counted.  Now it needs none.</mark>  The old strict measure survives inside YouTube Studio under a new name, Engaged views, and YouTube was explicit that earnings and Partner Programme eligibility still run on engaged figures rather than on the public count.",
                    "So how big is the gap.  <mark>Agentio measured more than 75,000 videos after the change and found about 549 million public views against 330 million engaged views — only six in ten public views were also engaged views, an average overstatement of 1.67 times.</mark>  Before the switch it had modelled 35,800 long-form videos and forecast a rise of around 30 percent, which turned out to be the conservative end.",
                    "And here is the part that decides what you pay.  <mark>The overstatement is 85 percent on channels under 50,000 subscribers and 49 percent on channels over 300,000.</mark>  The inflation is nearly twice as large on small creators as on large ones.  Small creators are also the ones with no agency, no media kit and no analytics you can audit, so the number you are least able to verify is the number that moved most.  By category the spread runs from Education at 63 percent down to Technology at 46.",
                    "Which brings us to this morning's demonstration of the problem.  <mark>Tubefilter's branded video chart on 22 September described itself as the first report since YouTube introduced its first-frame view metric and said we can see it in the numbers, reporting a general rise in viewcounts across the board.</mark>  Both halves are shaky.  The metric changed on 24 August and the same chart has run on 31 August, 8 September and 15 September since.  And this week's number one, MrBeast Gaming's Minecraft build at 44,043,717 views, is below the 59 million median of the five previous weeks and less than half of the week before, which was 104.2 million.  The chart moved down.",
                    "None of which is a complaint about Tubefilter, who reported the change itself back in August.  <mark>It is a demonstration of how fast a counting change becomes an explanation for things it did not cause.</mark>  Somebody will shortly show you a year-on-year chart that straddles 24 August and call the step a result.",
                ],
                "flagnote": "We were unable to retrieve YouTube's own help thread directly; the wording quoted is carried identically by four outlets that quote it, and we have not read the original page.  Whether the change is retroactive to views accrued before 24 August is not firmly established — one outlet says existing totals are unaffected, others do not address it.  The Agentio figures are from a company that sells creator advertising and therefore has an interest in advertisers distrusting public view counts; its pre-change 30 percent forecast was self-described as modelled and directional rather than measured.  The Tubefilter chart comparison is ours, built from the published number one figure in six consecutive weekly reports; the claims we could not test are its internal counts of how many sponsored videos cleared eight figures and one million, which come from a dataset that is not published.",
                "so_what": "A counting change is not a performance change, but it looks exactly like one on a chart, and from 24 August every year-on-year comparison on YouTube silently mixes two different metrics.  The thing that makes this expensive rather than merely untidy is that the inflation is regressive — it is largest on the smallest channels, which are the ones whose numbers you cannot independently check and whose rates are negotiated off a screenshot.  Meanwhile the money still moves on engaged views, so the seller quotes one number and the invoice is built on another.",
                "do_this": "Write engaged views into your next creator contract as the reported metric, in those words, and ask for a Studio screenshot showing both figures side by side rather than the public count alone.  Then rebase your internal benchmarks to 24 August and mark everything before it, so nobody presents you with a step change in Q4 and calls it a result.",
            },
            {
                "title": "Snapchat published research saying short dramas are enormous, and the only respondents it surveyed were people who already watch short dramas",
                "hook": "Wrong sample.  Screen out everyone uninterested in the format and every adoption number you produce is guaranteed to be large.",
                "stamps": [
                    ("NET INFLUENCER · 23 SEP", "https://www.netinfluencer.com/snapchatters-spending-50-usd-monthly-on-short-dramas-convert-to-downloads-at-higher-rate-than-rivals-study-finds/"),
                    ("SOCIAL MEDIA TODAY · 21 SEP", "https://www.socialmediatoday.com/news/snapchat-report-examines-the-rise-of-microdramas/830970/"),
                ],
                "body": [
                    "The study is The Short Drama Revolution and The Snapchat Advantage, commissioned by Snap and run by Ipsos.  <mark>3,000 consumers across the United States, United Kingdom and Saudi Arabia — 1,719 daily Snapchatters and 1,281 non-Snapchatters.</mark>  Headline findings: 42 percent of daily social media users watch short dramas daily, average monthly spend above 50 dollars, and 64 percent of daily Snapchatters are familiar with at least one short drama platform against 42 percent of non-Snapchatters.",
                    "Then the sentence that governs all of it.  <mark>Every respondent was screened to be either a current short drama watcher or someone interested in the format.</mark>  That is not a general population.  Ask a room of people who already watch something how many of them watch it daily and 42 percent is a low answer, not a high one.  Every adoption figure in the study is measuring enthusiasm inside an audience selected for enthusiasm.",
                    "The competitive claim is thinner than the headline suggests too.  <mark>32 percent of Snapchat viewers downloaded a short drama app after seeing an advertisement or clip on Snapchat, against a competitive average of 28 percent.</mark>  Four points.  That is the whole of higher rate than rivals, on a survey with no published margin of error.",
                    "And it landed in the same 48 hours as Digiday's reporting that four marketers cannot find a business case for the format at all.  <mark>The platform selling the format published growth data on Monday.  The buyers said on Wednesday they cannot connect it to sales.</mark>  Both things can be true — the audience is real and nobody has shown it converts — but only one of them was published by somebody with inventory to sell.",
                    "Snap does report two client figures worth noting, and they are the most useful part: <mark>ShortMax reporting an 11.6 percent improvement in return on advertising spend using Snap's automated advertisement tools, and MoboReels reporting 1.6 times return on advertising spend.</mark>  Both are advertisements for short drama apps running on Snapchat, which is a different business from a brand making one.",
                ],
                "flagnote": "This is vendor-commissioned research: Snap paid for it, Snap sells the advertising inventory it recommends, and the report is titled around Snapchat's own advantage.  Every figure is stated preference from a survey rather than observed behaviour, the sample was pre-screened for interest in the format, and no margin of error is published for any figure or subgroup.  The two client return figures are reported by the advertisers themselves with no methodology.  We have not read the Ipsos report directly; the figures come through trade coverage of it.",
                "so_what": "A screened sample answers a different question from the one the headline asks, and the difference is invisible unless you read the method.  Here the screen removed everyone indifferent to short dramas before a single question was asked, which makes every percentage a measure of intensity among fans rather than of reach across a market.  That is fine as evidence the fans are keen.  It is worthless as evidence that your customers are.",
                "do_this": "On every study a platform sends you this quarter, find the screening criteria before you read the findings, and if respondents were selected for interest in the thing being measured, treat every adoption figure as an upper bound and say so in the deck.  Then ask the seller for the same question asked of a general population, because they usually have it and did not lead with it.",
            },
        ],
    },
    {
        "id": "moves", "name": "MOVES", "page": "pg. 04",
        "note": "who did what, and what it signals",
        "items": [
            {
                "title": "Gap hired a Paramount executive in January, built a department, and has now signed a boy band to a multiyear deal with a documentary series at the centre",
                "hook": "Nine months of hiring before the first deal.  The order tells you this is a department, not a campaign.",
                "stamps": [
                    ("MARKETING DIVE · 22 SEP", "https://www.marketingdive.com/news/gap-rolls-out-fashiontainment-strategy-with-boy-band-collaboration/830984/"),
                ],
                "body": [
                    "The partnership is with Just Your Type, signed through Wexler Records and Republic Records, and it is the first deal out of what Gap calls its Fashiontainment platform.  <mark>The anchor is a Gap co-produced documentary series covering the group's live performances, creative process and the five members' personalities.</mark>  Around it: fan events at United States shopping centres, an autumn capsule collection, stage outfitting and social content.  A national mall tour starts next month.",
                    "On the band: <mark>more than 450 million views over the past three months and more than 2 million followers across social platforms.</mark>  Those are the only audience figures published.",
                    "The build-up is the actual story.  <mark>Gap hired Pam Kaufman, previously at Paramount, as its first chief entertainment officer in January.  Lourdes Arocho, also from Paramount, came in as head of licensing in May.  Justin Breton joined from Walmart as vice president of development last month.</mark>  Three senior entertainment hires across nine months, then a deal.  Most brands do this in the other order, signing the talent and then working out who runs it.",
                    "Note what Gap bought and what it did not.  <mark>It did not buy posts.  It bought a documentary series it co-produces, which means it owns a library rather than renting attention for a quarter</mark>, and it attached retail footfall to it through the mall tour.  Whether that works is unknown — no performance data exists and the series has not aired.",
                ],
                "flagnote": "No spend, deal term, episode count, distribution platform or performance figure has been published for any part of this, so nothing here says whether it will work.  The 450 million views and 2 million followers are as reported by Marketing Dive and are the band's own figures across all platforms, not a YouTube audience.  The reading of the hiring sequence as deliberate strategy is ours; Gap has not framed it that way in the reporting we have.",
                "so_what": "Owned entertainment fails most often because a brand buys the talent before it has anyone who can run a production, and then the production becomes the marketing team's side project.  Gap has built the function first and made its first deal the kind that produces an asset it keeps.  That is the difference between a campaign that ends and a library that compounds, and it is decided by who you hire, not by who you sign.",
                "do_this": "If owned video is on your plan for next year, name the person who will own the production calendar before you approve any talent deal, and give them the commissioning budget rather than the marketing team.  If no such person exists, buy an integration into somebody else's show this year and hire in the meantime.",
            },
            {
                "title": "MrBeast filed a trademark for a wearable on Monday, three weeks after signing a Google deal that includes a fitness tracker",
                "hook": "Read the filing next to the partnership and the partnership starts looking like product research.",
                "stamps": [
                    ("NET INFLUENCER · 23 SEP", "https://www.netinfluencer.com/mrbeast-files-trademark-for-beast-band-pointing-to-wearable-device/"),
                ],
                "body": [
                    "<mark>Jimmy Donaldson filed a United States trademark application for Beast Band on 21 September on an intent-to-use basis, which the trademark attorney Josh Gerben reads as pointing at a wearable activity tracker.</mark>  Intent-to-use means no product exists yet and none has to for years.",
                    "The timing is the point.  <mark>On 2 September, Beast Industries announced a multiyear Google partnership built around Gemini and Google Health, including Gemini appearing inside Donaldson's videos and a planned Fitbit integration in an upcoming challenge video.</mark>  Three weeks later, a wearable trademark.",
                    "It joins a run of filings since early 2025: MrBeast Mobile for wireless service, MrBeast Financial covering banking, investment advice, crypto exchange and consumer lending, MrBeast Social and Beast Social for influencer marketing and advertising, Watchtime Studios and Creator Industries.  <mark>He became the first individual creator to pass 500 million subscribers in June, after adding 117 million in 2025.</mark>",
                    "What a brand should take from this is uncomfortable.  <mark>If your partner is filing trademarks in your category, the sponsorship is also a live test of your product with an audience they own and you rent.</mark>  Nothing improper about it.  But the Fitbit challenge video is now, among other things, a way to find out how a wearable performs on camera before deciding whether to build one.",
                ],
                "flagnote": "An intent-to-use trademark filing is not a product, a launch or a commitment, and many such filings never become anything.  The connection drawn here between the filing and the Google partnership is ours and is not stated by Donaldson, Beast Industries or Google.  The trademark reading is attributed to attorney Josh Gerben via Net Influencer.  No terms, values or dates have been published for the Google partnership.",
                "so_what": "Creator businesses with product ambitions are a different counterparty from creator businesses that sell attention, because the sponsorship doubles as market research they keep.  That is not a reason to avoid them — their audiences are the reason you are there — but it is a reason to write the contract as if a competitor may emerge from it.  Most brand partnership agreements with creators have nothing in them about this at all.",
                "do_this": "Check whether your largest creator partners have filed trademarks in your category, which takes about ten minutes on the public trademark register, and do it before your next renewal rather than after.  Where the answer is yes, ask your legal team for a non-compete window and exclusivity on the product demonstration, and price the deal knowing what you are also funding.",
            },
        ],
    },
    {
        "id": "onstream", "name": "ON STREAM", "page": "pg. 05",
        "note": "the live numbers, and what they are actually worth",
        "items": [
            {
                "title": "World of Warcraft pulled 807,223 people watching at the same moment, and a round-the-clock government channel launched days later and has not cleared 10,000",
                "hook": "Nine Wembleys against a village hall, on the same platform, inside a fortnight.",
                "open": True,
                "stamps": [
                    ("STREAMS CHARTS · 22 SEP", "https://streamscharts.com/news/wow-forever-viewership-chat"),
                    ("TUBEFILTER · 22 SEP", "https://www.tubefilter.com/2026/09/22/trump-tv-youtube-channel-news-media/"),
                ],
                "body": [
                    "The reveal of WoW: Forever at BlizzCon on 12 September hit <mark>807,223 peak concurrent viewers — the highest number of people watching at the same instant — which is the third-biggest peak of any World of Warcraft campaign since 2019, behind only WoW Classic and Shadowlands.</mark>  For scale, Wembley Stadium holds 90,000, so that is roughly nine full stadiums at one moment.",
                    "Across the seven days around the reveal: <mark>21.85 million hours watched, a 4.2 times lift on the game's baseline.  Twitch took 88 percent of it.  YouTube carried 2.19 million hours, the largest YouTube total of any World of Warcraft campaign compared.</mark>  Hours watched is total viewing time added up across everybody, so it rises when an event simply runs longer or when more channels carry it, which is why the peak matters more.",
                    "The beta on 17 September produced a second spike: <mark>599,618 peak concurrents and 16.10 million hours across five days, a 4.3 times lift — Twitch 14.24 million hours, YouTube 1.33 million, Kick 381,236.</mark>  Between 12 and 21 September the game sat second on Twitch, about 1.7 million hours behind Grand Theft Auto V.",
                    "Now the contrast, because it is the useful half.  <mark>A round-the-clock Trump TV stream went live on the White House YouTube channel in the days after, and concurrent viewership has stayed below 10,000.</mark>  It launched hours after five television networks issued a joint statement and stopped carrying the president live.  The White House digital chief called it the Administration's greatest hits, unfiltered.",
                    "The mechanism behind the gap is not politics, it is scheduling.  <mark>A reveal is an appointment — one moment, announced, that everybody attends at once.  A 24-hour channel is availability, which is the opposite thing.</mark>  YouTube pays attention to sessions, not airtime, and a stream with nothing scheduled in it has no moment to arrive for.  That is the same reason most brands' always-on live channels do nothing.",
                ],
                "flagnote": "Streams Charts published no average concurrent viewership, no broadcast duration and no count of how many channels were included in the hours-watched totals, so the multiples cannot be separated into audience growth versus wider coverage, and we have led on peak for that reason.  Streams Charts sells data products based on these figures.  The Trump TV figure is Tubefilter's characterisation of concurrent viewership staying below 10,000 rather than a published measurement with a timestamp, and the channel had been live only a few days at the time of writing.  The Wembley comparison is ours and is a capacity comparison, not a like-for-like audience measure.",
                "so_what": "Peak concurrents measures whether you created a moment.  Hours watched measures how long you left the lights on, and it goes up when you add channels or extend the broadcast without one extra person showing up.  The two numbers next to each other this week are the clearest demonstration you will get of the difference: one campaign built a single appointment and got nine stadiums, the other built permanent availability and got a village hall.",
                "do_this": "When a seller quotes you hours watched, ask for peak concurrents, average concurrents, total broadcast duration and the number of channels counted, in writing, before you reply on price, and price off peak alone where any of the four are missing.  And if you are planning an always-on brand channel, put a scheduled weekly appointment in it or do not build it.",
            },
        ],
    },
    {
        "id": "watch", "name": "ONE TO WATCH", "page": "pg. 06",
        "note": "one creator, picked for momentum rather than size",
        "items": [
            {
                "title": "Nutrition Made Simple's median video went from 64,000 views to 302,000 in eight weeks, and in 471 videos he has never taken a sponsor",
                "hook": "The most sponsor-saturated category on YouTube, and the one credible channel in it has no rate card because the obvious buyers are the ones he debunks.",
                "open": True,
                "stamps": [
                    ("CHANNEL", "https://www.youtube.com/@NutritionMadeSimple"),
                ],
                "body": [
                    "Dr Gil Carvalho is a physician-scientist who makes nutrition explainers to camera with animated charts, every claim tied to named peer-reviewed papers linked in the description.  <mark>394,000 subscribers, 42,390,029 lifetime views, 471 videos since 2014.</mark>  Typically 9 to 22 minutes, roughly weekly.",
                    "The inflection is sharp and recent.  <mark>His last eight long-form videos, from 25 July to 17 September, have a median of 302,141 views.  The eight before them, from 30 May to 18 July, have a median of 64,355.  That is 4.7 times.</mark>  Before 25 July his best video of all 2026 was 228,305.  Since then he has five above that old record in eight weeks.  Some of that gap is the counting change in L'S rather than growth, and the two cannot be separated from outside — but that change is worth roughly a third on average, not four times, so the run is real.",
                    "Two things changed on the same date.  <mark>First, longer original pieces instead of short reactive fact-checks — his two biggest are his longest, at 20 minutes 49 and 34 minutes 46.</mark>  The 34-minute one is an investigation into a large podcast's health claims and finances, which is reporting rather than explaining.  Second, fast turnarounds on newly published trials: his two most recent, on a new keto-versus-Mediterranean trial and an NEJM heart paper, did 510,801 and 345,845 at under eleven minutes each.",
                    "On sponsorship, and we checked this properly.  <mark>We read the full descriptions of all 26 long-form uploads from 10 March to 17 September and searched every one for sponsor, promotion code, discount, affiliate and paid promotion language.  Zero hits.</mark>  The descriptions contain a subscribe link, his social handles, an animator credit and journal citations.  One link to his own newsletter.  That is the whole commercial footprint.",
                    "So who should be calling, and what they would be buying.  <mark>The money in nutrition is supplement money, and supplements are exactly what he takes apart on camera, often by name — which is why there is no rate card and no agency rather than why there is no demand.</mark>  The buyers who are not disqualified are diagnostics and laboratory testing companies selling cholesterol panels and glucose monitors, staple food brands he already recommends on the evidence, and health systems and insurers.  What you would be buying is the only place in this category where a health claim is not automatically discounted by the audience, at a price nobody has set.",
                ],
                "watch": {
                    "label": "TOP VIDEO, LAST 3 MONTHS",
                    "title": "I Studied Nutrition for 30 Years. Here's What Actually Matters.",
                    "url": "https://www.youtube.com/watch?v=T1-5Ic9iiPs",
                    "meta": "570,146 views · published 25 July 2026 · 20m 49s",
                    "note": "The video that started the run, and his longest-form turn away from short reactive fact-checks.",
                },
                "flagnote": "Subscriber and lifetime view figures are taken from the channel's own about page on 23 September 2026; subscriber counts are YouTube's rounded public figure.  The median comparison is ours, calculated from per-video view counts retrieved the same day, and view counts keep accruing, so the two windows are not measured at equal ages — the newer videos have had less time and the gap is therefore understated rather than overstated.  Public view counts after 24 August also include the first-frame counting change described in L'S, which inflates the later window relative to the earlier one; we cannot separate the two effects and the true lift is smaller than 4.7 times.  Description scanning cannot rule out an unlabelled spoken sponsor read, and attempts to retrieve captions to check were blocked, so no sponsors found is not the same as no sponsors.",
                "so_what": "A channel that has refused the only money in its category has built the one thing that category cannot buy, which is an audience that does not discount a health claim on sight.  That asset is worth most to the buyers who were never going to be the obvious ones, and it is unpriced rather than underpriced, because no rate card exists and no agency has been hired to write one.  Whoever asks first sets the number.",
                "do_this": "If you sell diagnostics, testing, or a staple food with actual evidence behind it, email this channel this week before somebody builds a media business around it, and propose funding a video on a subject rather than a read inside one.  Ask for engaged views in the reporting, per the L'S item, and expect to be turned down on anything that reads as an endorsement of a product claim.",
            },
        ],
    },
    {
        "id": "money", "name": "THE MONEY", "page": "pg. 07",
        "note": "where the spend actually is, and where it is not",
        "items": [
            {
                "title": "YouTube took a record 14.2 percent of American television time in July while Netflix took 7.8, and two banks cut their ratings on Netflix the same month",
                "hook": "This is the chart to put in front of anyone who still files YouTube under social media.",
                "open": True,
                "stamps": [
                    ("NIELSEN · 10 SEP", "https://www.nielsen.com/news-center/2026/tv-usage-kicks-usual-summer-slowdown-fueled-by-world-cup-and-streaming-in-nielsens-july-gauge-reports/"),
                    ("MEDIA PLAY NEWS · 22 SEP", "https://www.mediaplaynews.com/analyst-netflix-losing-viewership-ground-to-youtube/"),
                ],
                "body": [
                    "Nielsen's July report, covering 29 June to 26 July and published on 10 September: <mark>YouTube captured a record 14.2 percent of all television viewing time in American homes, with streaming overall at 49.0 percent.  Netflix took 7.8 percent, level with Fox.  Disney's streaming properties together took 4.7 percent.</mark>  YouTube's lead over second place is now five full share points.",
                    "The money behind the share.  <mark>YouTube advertising revenue was 11.06 billion dollars in Alphabet's second quarter, up 13 percent year on year and ahead of the 10.8 billion expected.  Netflix reported 3.4 billion dollars of net income on 12.6 billion of revenue in the same quarter.</mark>  Netflix is much more profitable per dollar.  YouTube is where the time went.",
                    "The analysts moved on the back of it.  <mark>HSBC and Wells Fargo both downgraded Netflix.  Wells Fargo expects Netflix's top 100 original content hours to fall 21 percent year on year in the second half of 2026.</mark>  HSBC's Mohammed Khallouf: YouTube has been benefiting, in our view, from a declining reception to Netflix's original content, and its strategy shift further heightens competition.  He points at Netflix's lowest Emmy haul since 2016 and audience scores on its latest franchise releases down 7 percent on previous seasons.",
                    "The second number worth having this week sits in gaming.  <mark>At the IAB gaming event in New York on 17 September, Overwolf's Shahar Sorek put it at 2.4 percent of media spending against 67 percent of the country playing every week.</mark>  The comparison made there was connected television, which takes about 20 percent of media time and roughly 7.7 percent of spend.  Gaming has the same shape of gap, earlier.",
                ],
                "numbers": [
                    ("14.2%", "of all American television viewing time went to YouTube in July, a record, against Netflix on 7.8 percent"),
                    ("$11.06B", "YouTube advertising revenue in Alphabet's second quarter, up 13 percent and ahead of the 10.8 billion expected"),
                    ("2.4%", "of media spending goes to gaming, in a country where 67 percent of people play every week"),
                ],
                "flagnote": "Media Play News describes Netflix's 7.8 percent as a multiyear low; Nielsen does not use that phrase and frames it as down 1 percent on a July 2025 record driven by Squid Game, so we have not used it.  Media Play News labels the 4.7 percent as Disney+; Nielsen's own release attributes it to Disney's streaming properties collectively, and we have used Nielsen's wording.  A Prime Video figure of 4.2 percent appears in the Media Play News piece but is not in Nielsen's release and another outlet reports Amazon at 4.3 percent, so we have left it out.  The claim that Netflix has shed more than 46 percent of its market value since a 2025 peak is asserted without a source in the Media Play News piece and we could not confirm it.  Wells Fargo's analyst is not named in the reporting.  The gaming spend figures are quoted from a trade event by a company selling into gaming advertising.",
                "so_what": "Share of viewing and share of budget have come apart in two places at once, and both gaps point the same way.  YouTube now takes almost twice as much American television time as Netflix, and most brand video plans still treat it as the social line rather than the television line.  Gaming is the same argument two or three years behind, which is exactly when the inventory is cheap and the case is hard to make internally.",
                "do_this": "Take the Nielsen July chart into your next budget meeting and ask one question out loud: what percentage of our video budget goes to the platform that has 14.2 percent of television time.  If the answer is smaller than the share, move a test budget this quarter rather than next year, and run it against your television benchmarks rather than your social ones so the comparison is fair.",
            },
        ],
    },
    {
        "id": "format", "name": "FORMAT LAB", "page": "pg. 08",
        "note": "a format worth stealing, and what makes it work",
        "items": [
            {
                "title": "A daily live business show did about 5 million dollars of advertising in 2025 off a YouTube channel smaller than a market town, and OpenAI bought it",
                "hook": "Subscriber count was never the product.  Who is in the room was, and the room was about 70,000 people a day.",
                "open": True,
                "stamps": [
                    ("OPENAI · ACQUISITION", "https://openai.com/index/openai-acquires-tbpn/"),
                    ("TECHCRUNCH · 2 APR", "https://techcrunch.com/2026/04/02/openai-acquires-tbpn-the-buzzy-founder-led-business-talk-show/"),
                    ("NET INFLUENCER · 23 SEP", "https://www.netinfluencer.com/podcaster-sammi-cohen-is-launching-social-commerce-network-a-live-business-show-modeled-on-tbpn/"),
                ],
                "body": [
                    "TBPN is a daily live technology and business show launched in late 2024 by John Coogan and Jordi Hays.  <mark>OpenAI acquired it on 2 April 2026, its first media acquisition, terms undisclosed.</mark>  It sits inside OpenAI's strategy organisation with stated editorial independence.  Figures circulating about the price are unsourced speculation and we have not used them.",
                    "The revenue, because it is the reason this is in Format Lab.  <mark>The Wall Street Journal reported about 5 million dollars of advertising revenue in 2025 and the show on track to pull in more than 30 million this year, with sponsors including Ramp, Plaid, Google's Gemini and the New York Stock Exchange.  Axios, also citing the Journal, published 15 million for 2026 in December and never updated it.</mark>  Take the range rather than the headline.  Either end is a very large number for a channel this size.",
                    "And that is the size.  <mark>The channel was around 58,000 to 62,000 subscribers at the time of the deal.  It is 142,000 today.  Reported daily viewership is around 70,000 per episode.</mark>  Do the arithmetic at the conservative end and each of those daily viewers is carrying roughly 200 dollars of annual advertising revenue.  That is trade-publication arithmetic rather than channel arithmetic.",
                    "The mechanism is not mysterious, it is just unfashionable.  <mark>A daily live show sells the way a trade magazine sells — against exactly who is in the room, at a known time, every weekday.</mark>  Ramp and Plaid are not buying 70,000 people, they are buying the specific 70,000 who watch a founder show at 11am.  Appointment plus a defined audience produces a rate that has nothing to do with subscriber count.",
                    "Which is why it is being copied this week.  <mark>Sammi Cohen launches Social Commerce Network on 6 October, Tuesday to Thursday, 11am to 1pm Pacific, from a studio in Los Angeles, simulcast on YouTube, X, TikTok and Instagram</mark>, co-hosted with Alaina Hartley, previously a principal at Greycroft.  Cohen has more than 500,000 followers across platforms, 107,000 of them on YouTube, and an audience around 70 percent women.  Explicitly modelled on TBPN.",
                ],
                "flagnote": "The revenue figures are reported by The Wall Street Journal, which we could not access directly; they reach us through TechCrunch, Axios and others quoting it.  The 2026 figure is genuinely disputed between outlets, at more than 30 million and at 15 million, both attributed to the same original reporting, and neither has been corrected — we have given both rather than choosing.  The acquisition price was not disclosed.  The 58,000 subscriber figure quoted in this week's trade coverage is roughly the deal-time number from April and is not current; we checked the channel on 23 September and it shows 142,000.  The revenue per viewer calculation is ours, uses the lower revenue figure and the reported daily viewership, and is a rough illustration rather than a company metric.",
                "so_what": "Advertising rates are set by who is watching and whether the advertiser can be sure they will be there, and subscriber count measures neither.  A daily show at a fixed time with a defined professional audience sells like a trade publication, which is a much better business per person than a large channel selling general attention.  The reason more brands do not build one is that it demands a schedule they have to keep, and the schedule is the entire asset.",
                "do_this": "If your customers are a defined professional group, price a weekly live show at a fixed hour before you price another campaign, and be honest about whether you can keep the slot for a year, because missing it is what kills these.  If you are buying rather than building, ask small shows in your category for daily viewership and time of day instead of subscriber count, and expect the rate to look expensive per subscriber and cheap per customer.",
            },
        ],
    },
]

FORECAST = [
    {
        "confidence": "LIKELY",
        "window": "by 31 March 2027",
        "headline": "A large advertiser writes engaged views into a creator contract as the billing metric, and its agency starts quoting both numbers as standard",
        "body": "From 24 August the public view count and the metric YouTube pays on are different numbers, and the gap measured across more than 75,000 videos runs at 1.67 times on average and 85 percent on the smallest channels.  That is a procurement problem rather than a taste problem, which is why it will move quickly once one company's finance team notices that the number in the deck is not the number in the invoice.  It costs nothing to ask for and it is very hard to refuse, since the figure sits in Studio next to the one already being screenshotted.  The reason it might not happen this fast is that no advertiser wants to be the first to tell creators their numbers are inflated, and the polite version of the conversation takes longer.",
        "do": "Add engaged views to your creator reporting template now as a required field beside public views, and start collecting both on current partnerships so you have a comparison before renewal season rather than after it.",
    },
    {
        "confidence": "LIKELY",
        "window": "by 30 June 2027",
        "headline": "OpenAI ships a way for creators to charge their audience directly, and the first serious competitor to Patreon's take rate is an artificial intelligence company",
        "body": "Three people who built the largest creator subscription business have moved together into OpenAI, the man leading it is titled Creator Product, and he pointed at DevDay on 29 September in the same post.  That is a team assembled to ship rather than to advise.  The mechanism that makes it likely is distribution — a payment layer inside a product with hundreds of millions of weekly users does not need to win creators over, it needs to be present where their audience already is.  What would stop it is that OpenAI's problems are compute and regulation rather than creator payouts, and a payments business is a slow, unglamorous thing to run.  Watch for a revenue share percentage in the announcement, because that number is the whole competitive claim.",
        "do": "Watch DevDay on 29 September specifically for creator payment or subscription tooling, and if it appears, ask your three largest creator partners within the fortnight whether they intend to use it, because a partner with a second income line negotiates differently.",
    },
    {
        "confidence": "WATCH CLOSELY",
        "window": "by 31 December 2027",
        "headline": "A sports body publishes actual sign-ups from a creator campaign rather than impressions, and the figure is much smaller than anyone expects",
        "body": "USA Fencing has done the hard part already by putting 800 clubs with standing trial offers behind a single address, which means for once the conversion is countable.  Somebody in that position eventually publishes, because being the only organisation with a real participation number from creator marketing is worth more than the number itself.  The reason it stays a watch rather than a likely is that impressions are a much kinder statistic and the people who commission these campaigns are the people who would have to publish the unkind one.  When it comes, expect a conversion rate in the low hundredths of a percent and expect it to be reported as a disappointment, which it will not be, because a governing body on a 17 million dollar budget converting anyone at that reach is a good outcome.",
        "do": "If you are buying creator reach against a physical action, instrument the destination before the campaign starts and agree internally what a good conversion rate would look like, in writing, so the result is judged against a number you set rather than against the impression figure.",
    },
    {
        "confidence": "LONG SHOT",
        "window": "by 31 December 2027",
        "headline": "A brand publishes attributed sales from a branded series with the method attached, and it undercuts the figure everybody has been quoting",
        "body": "Bob's Discount Furniture is the only brand in this category with a published sales number, nearly nine million dollars, and it is self-attributed with no method disclosed.  That number is now the benchmark every branded series will be sold against, which creates an obvious opening for a brand to publish a smaller, properly evidenced figure and take the credibility instead.  The reason it stays a long shot is that publishing a method invites people to argue with it, and a marketing team that has just spent a year on a series has no incentive to hand critics the tools.  It becomes likely only if a finance function rather than a marketing function decides to publish.",
        "do": "Agree the attribution method for any branded series before you commission it, write it into the brief, and keep a holdout region that never sees the series so you have a comparison that does not depend on anybody's model.",
    },
]

TLDR = [
    "OpenAI hired Patreon co-founder and technology chief Sam Yam to lead Creator Product, with Patreon's former heads of product and engineering joining him, and pointed at DevDay on 29 September — while its sponsored Instagram posts for ChatGPT went from 61 in June to 122 in July to 141 in August, per HypeAuditor.  Compare your current creator quotes in parenting, fitness and technology against June quotes, and move budget to a category OpenAI is not bidding in rather than matching a price set by a buyer with no cost per customer to defend.",
    "Since 24 August YouTube counts a public view from the first frame rather than after about thirty seconds, and Agentio's measurement of more than 75,000 videos found public views overstating engaged views by 1.67 times on average — 85 percent on channels under 50,000 subscribers against 49 percent on channels over 300,000 — while earnings still run on engaged figures.  Write engaged views into your next creator contract as the reported metric and ask for a Studio screenshot showing both numbers side by side.",
    "Bob's Discount Furniture reports 152 million views, 223 million impressions and nearly nine million dollars of attributed sales from its social reality series about couples choosing furniture, and has commissioned a second season, while four marketers told Digiday that scripted branded microdramas from Crocs, Nuuly and Native still have no business case.  Check that the purchase decision your customer makes appears on screen in every episode of anything you commission, and set the attribution method at commission rather than after.",
    "Nielsen has YouTube at a record 14.2 percent of American television viewing time in July against Netflix on 7.8, with YouTube advertising revenue at 11.06 billion dollars in Alphabet's second quarter, up 13 percent, and both HSBC and Wells Fargo downgrading Netflix.  Take that chart into your budget meeting and ask what share of your video budget goes to the platform holding 14.2 percent of television time, then run a test against television benchmarks rather than social ones.",
    "USA Fencing put twelve creators with more than 215 million combined followers against four Team USA fencers this week and pointed the whole thing at TryFencing.org, where 800 clubs had already agreed standing trial offers, against a creator programme baseline of 4.75 million impressions a month.  Build and staff the single action you want viewers to take before you buy any reach, and count how many partners have agreed to it, because that number caps everything the campaign can deliver.",
    "Snap's Ipsos study reporting that 42 percent of daily social media users watch short dramas daily screened every one of its 3,000 respondents to be a current watcher or someone interested in the format, and its competitive claim rests on a four-point gap, 32 percent against a 28 percent average.  Read the screening criteria on every platform study before the findings, and treat any adoption figure from a pre-screened sample as an upper bound in your deck.",
    "TBPN did about five million dollars of advertising in 2025 and was reported on track for between 15 and 30 million in 2026 off a YouTube channel of roughly 58,000 subscribers at the time OpenAI bought it, with about 70,000 viewers per daily episode, and Sammi Cohen launches a copy of the format on 6 October.  If your customers are a defined professional group, price a weekly live show at a fixed hour before you price another campaign, and ask small shows for daily viewership and time of day rather than subscriber count.",
]

SHARE = [
    {
        "who": "JARED · CEO",
        "angle": "The only brand with a published sales figure from a branded series is a discount furniture chain, and it got one by putting the purchase decision on screen rather than hiding it.",
        "post": "Everyone making branded entertainment right now is being told the same thing: make it good enough that people forget it's an advertisement.\n\nThe only brand in the category with a published sales number did the opposite.\n\nBob's Discount Furniture made a series about couples arguing over how to furnish a house. 152 million views, and the company reports nearly nine million dollars in attributable sales. Season two was commissioned last week.\n\nMeanwhile Digiday spoke to four marketers this morning about branded microdramas — Crocs, Nuuly, Procter and Gamble's Native. Their summary was that the views are there and the business impact isn't.\n\nThe difference isn't budget and it isn't craft. Bob's made a show about the decision its customer is already making. Someone watching two people argue about a sofa is doing the work of choosing a sofa. There's no leap from the watching to the buying, because they're the same activity.\n\nHide the product to make the film better and you have made a better film. You have probably also made a worse advertisement.\n\nWorth saying the nine million is self-reported with no method published, so I'd want to see the workings. But it's the only number anyone in this category has put their name to, and it came from the least glamorous format in it.",
        "why": "It takes the one received rule of branded entertainment — disguise the commerce — and shows the only brand with a receipt broke it deliberately.  A sceptical client assumes the answer is a bigger production; this says it is a different subject.  Image: a sofa on flat orange, one sales figure beside it.",
    },
    {
        "who": "JAMES · CREATIVE DIRECTOR",
        "angle": "Sixty-one percent of consumers expect a social link to reach a product page and creators deliver that 40 percent of the time, which means the variable killing conversion sits after the creative, not in it.",
        "post": "Sixty-one percent of people expect a link on a social post to take them to the product. Creators send them there 40 percent of the time. Marketers manage 66.\n\nThat's from Bitly's new Click Expectation Report, about 1,500 people surveyed in late July.\n\nI have spent a lot of my career arguing about the eight seconds before the link. Which frame opens it, how the product is lit, whether the line lands. And then the click lands on a directory with nine options on it, and the person who wanted the thing has to go and find the thing.\n\nCreators route 24 percent of clicks to a directory and 17 percent to a marketplace. Thirty percent land on a generic homepage.\n\nNobody briefs that. It happens after the brief, in a field somebody fills in on their phone.\n\nSo the honest version is that on a lot of campaigns the creative was not the variable. We were optimising the part we enjoy and leaving the part that decides the outcome to whoever had the password.\n\nFair warning on the source: Bitly sells link management, and this is a survey of what people say they do rather than a measurement of what they did. It's an argument for their product. I still think it's describing something real, because I have watched it happen on work I was proud of.",
        "why": "A creative director conceding that craft was not the variable, and naming the specific unglamorous field that beat it, is the admission nobody expects from that chair — and he flags the vendor interest instead of overselling it.  Image: a link-in-bio screen with nine buttons, flat pink ground.",
    },
    {
        "who": "LAWRY · LEAD VIDEO EDITOR",
        "angle": "The thirty-second rule that shaped every cold open on YouTube quietly stopped applying on 24 August, and the number editors have been protecting is no longer the number anyone is billed on.",
        "post": "On 24 August YouTube started counting a view from the first frame. Before that a long-form video needed around thirty seconds of watching before the view registered at all.\n\nWhich means the thing most of us build the opening around stopped existing, and almost nobody in an edit has changed how they cut.\n\nThirty seconds was a real constraint. You hold the establishing shot a beat longer than you want to because you need them past the line. You put the sponsor read after it, never before, because a read inside the first thirty seconds costs you the view outright. Most editors could tell you roughly where their videos cross that line without checking.\n\nThat bar is gone from the public count. It is not gone from the number that pays. The strict measure still sits in Studio, renamed engaged views, and that is what the money runs on.\n\nSo there are now two numbers and they disagree. Agentio looked at more than 75,000 videos and found public views running about 1.67 times the engaged ones.\n\nIf you cut the opening for the public figure you are optimising something nobody gets invoiced for.\n\nI don't have a settled answer on where the read goes now. The argument for moving it earlier is real. I just don't want to be the person who tested it on somebody else's video.",
        "why": "It follows a platform counting change into the specific timeline habit it invalidated — where the read sits, how long you hold the opening — and lands on the business consequence that the metric an editor protects is not the metric that pays.  That only reads from inside the cut.  Image: a timeline with a marker at thirty seconds, flat black ground.",
    },
]
