ISSUE = {
    "date_iso":  "2026-09-18",
    "kicker":    "Crux Media // Friday 18 September 2026",
    "tagline":   "What brands did on YouTube yesterday, and whether it worked.",
    "pace":      "STEADY",
    "next_drop": "Next drop: Monday, 06:30 MT",
}

LEAD = {
    "headline": "THE SAME AD WAS REMEMBERED BY 41 PERCENT OF VIEWERS IN A LIGHT AD BREAK AND 26 PERCENT IN A HEAVY ONE.  NOBODY CHANGED THE AD",
    "deck": "FreeWheel tested 436 people on identical thirty-second spots inside the same streaming programme.  In the comparison that matters, the only thing changed was how many other ads sat beside the spot.  Recall fell by more than a third.  Every conversation you have ever had about why a film underperformed assumed the film was the variable, and inside one ad break it is not.",
    "stamps": [
        ("PPC LAND · 18 SEP", "https://ppc.land/more-ads-cut-streaming-brand-recall-from-41-to-26-freewheel-finds/"),
    ],
    "body": [
        "FreeWheel, the advertising technology arm of Comcast, ran this with MediaScience, a research firm that does lab-based advertising testing.  <mark>436 participants, in lab and in-home settings, watching thirty-second ads inside a thirty-minute streaming programme in a plain interface with no channel branding on it.</mark>  They measured with eye tracking and a survey afterwards.",
        "Two ad loads were tested.  Ad load is simply how many minutes of advertising sit inside a programme.  <mark>The heavy condition carried 9 minutes of ads per 30 minutes of programme, which is 30 percent of the runtime.  The light condition carried 3 minutes 45 seconds, which is 12.5 percent.</mark>",
        "<mark>Unaided recall — the share of people who could name the brand later with no prompt — came out at 41 percent on the light load and 26 percent on the heavy one.</mark>  Same ads.  Same length.  Same programme.  In this test, the fifteen-point gap came from nothing but the number of other advertisers in the break.",
        "Now do the arithmetic that nobody in the release does, because it is the whole decision.  <mark>Cutting from 9 minutes to 3 minutes 45 costs the publisher 5 minutes 15 seconds, which is 58 percent of its sellable ad time.</mark>  What the buyer collects for it is recall going from 26 to 41 percent.  Both figures are ours, from the two loads FreeWheel tested.  The two 58s are different quantities and the match between them is a coincidence of where the loads happened to be set, so do not build anything on the symmetry.  Build on the shape: the seller pays in inventory and the buyer gets paid in memory.",
        "That is why light-load inventory barely exists.  Cut the break by 58 percent and the publisher has 42 percent of its slots left, so it needs roughly two and a half times the price just to stand still.  You are buying one slot either way, so the same trade costs you nothing.  <mark>You are not choosing between good streaming inventory and bad streaming inventory.  You are choosing a load tier, and it is almost never on the rate card.</mark>",
        "The study carries other findings and they are worth separating rather than stacking.  A single exposure in streaming produced 33 percent unaided recall against 12 percent in social feeds.  Two streaming exposures produced 53 percent, two social exposures 24 percent, and one of each 42 percent.  On eye tracking, 94 percent of people looked at the streaming ads against 75 percent in social, with dwell time at 71 percent of the ad's duration against 52 percent.  Handle that streaming-beats-social comparison with tongs — see the flagnote — but the mixed result is the interesting one, because a single social exposure added to a single streaming exposure got most of the way to two streaming exposures.",
    ],
    "numbers": [
        ("41 / 26", "percent unaided recall for the identical ad in a light versus a heavy ad break"),
        ("58%", "of its sellable ad time a publisher gives up to deliver the lighter load — our arithmetic from the two loads tested"),
        ("436", "people tested by FreeWheel and MediaScience across lab and in-home settings"),
    ],
    "flagnote": "FreeWheel is owned by Comcast and its revenue depends on streaming advertising.  The deck is titled Why Brands Need TV and concludes that streaming beats social, so treat the streaming-versus-social comparison as a sales argument.  The ad-load finding is the credible part precisely because it cuts against the interests of FreeWheel's own publisher clients, who sell the heavier load.  The study is dated 15 September and was distributed on the 17th; we have found only one outlet covering the 41-to-26 figure, so it rests on a single read of a vendor study.  No fieldwork dates, no per-condition sample sizes and no confidence intervals were published.  PPC Land notes the deck discloses less about its eye-tracking method than it should, no co-viewing was accounted for, and no linear television was tested despite the title.  A separate FreeWheel study with a different research partner, surfaced the same week, reported that six minutes of ads per hour delivered 89 percent higher recall than twelve minutes per hour — same direction, different study, different method, and not to be merged with the numbers above.",
    "so_what": "Two ads competing for the same memory interfere with each other, and the more of them there are in a single break the less well any one of them gets stored.  That is not a creative problem and no amount of craft fixes it, which is uncomfortable because craft is the only lever most of us actually control.  The lever that moved the number by more than a third sits in the media plan, in a field that usually is not even filled in.",
    "do_this": "On your next streaming or connected television buy — connected television meaning ads served to a TV set over the internet rather than broadcast — ask the seller in writing what the ad load is on the inventory being offered, in minutes per half hour, and insist on a range rather than a single average.  Then compare your two best quotes on cost per thousand people reached adjusted for that load, and be willing to pay more for the lighter one.",
}

SECTIONS = [
    {
        "id": "ws", "name": "W'S", "page": "pg. 02",
        "note": "what worked, and the exact reason it worked",
        "tint": "blue",
        "items": [
            {
                "title": "Michelle Khare got 25 million views of build-up before the video existed, by treating the shoot as the campaign and holding her single best shot back until after release",
                "hook": "The full video landed five months after the footage was captured.  The gap was not a delay.  It was the distribution plan, and it is an editing decision as much as a marketing one.",
                "open": True,
                "stamps": [("THE PUBLISH PRESS · 16 SEP", "https://news.thepublishpress.com/p/michelle-khare-meets-hollywood")],
                "body": [
                    "The Publish Press published a breakdown this week of how Khare ran her series Challenge Accepted: I Ran Seven Marathons in Seven Days on Seven Continents.  The events are months old.  The mechanism is the reason to read it.",
                    "She travelled with <mark>a five-person crew</mark> and ran seven marathons on seven continents in seven days, becoming the 86th woman to finish The Great World Race.  While she was doing it, she posted short videos to Instagram and TikTok every day, cutting them on Premiere Mobile between continents.  <mark>Those posts did more than 25 million views before the long-form video came out five months later.</mark>",
                    "Read that sequence again, because most brand video does it in the opposite order.  The usual shape is to finish the film, then buy attention for it.  She spent five months building the audience using the making of the thing as the content, then released the thing into an audience that already knew the story and had been waiting on the ending.",
                    "Then the part that is purely an edit decision.  For the segment recreating a Tom Cruise stunt, <mark>she held every piece of airborne footage back until days after the full video premiered</mark>, and put out only the pre-flight preparation in advance.  The best shot in the entire production never appeared in any of the promotion.  It was the payoff, and it was the one thing she refused to spend.",
                    "The premiere itself was run as a film release — a red carpet at the Directors Guild of America Theater in Los Angeles, a step-and-repeat, a life-sized poster, food from each continent, and Emmy voters in the room.  The series went up on YouTube two days later.  <mark>YouTube partnered with her on a Primetime Emmy For Your Consideration campaign.</mark>  Red Bull signed her as a Red Bull Creator and worked with her on the social rollout of the stunt.  She made behind-the-scenes editing content with Adobe and went on First We Feast's Heat Eaters to reach a different audience.",
                    "Khare's line about the premiere: hundreds of voters approached me and said, I came expecting what I perceived as a YouTube video, and what you presented blew us away.",
                ],
                "flagnote": "The 25 million view figure is reported as an aggregate across Instagram and TikTok posts over the running period, with no split by platform, no split between organic and paid, and no definition of what counts as a view on either.  It is not a reach number and it is not comparable to a YouTube view count.  No fee or terms were disclosed for Red Bull, Adobe or the YouTube partnership.  The premiere and the runs happened earlier this year; only the account of how it was built is new this week.",
                "so_what": "The received idea is that you protect the best material for the finished film because that is what people paid to see.  What she did instead is treat the best shot as the only thing that cannot be spent early, and treat everything else — the crew, the travel, the failures, the editing on a phone in an airport — as the advertising.  That inverts where the money goes.  The promotion cost almost nothing because it was footage the shoot generated anyway, and the thing that was scarce stayed scarce.",
                "do_this": "On your next owned video, list every shot before you cut and mark exactly one as unspendable, then build the whole pre-release run out of the material around it.  Start posting the making-of the week you start shooting rather than the week you finish, so the audience arrives before the film does.",
            },
            {
                "title": "The most useful branded video on this week's chart is third, not first, and it is the only one whose number has a cause you could copy",
                "hook": "Dude Perfect and BODYARMOR did 12.4 million views.  The useful detail is Tubefilter's: the channel describes it as the video its audience had asked for most, and the brand attached to that rather than to a pitch.",
                "stamps": [("TUBEFILTER · 15 SEP", "https://www.tubefilter.com/2026/09/15/top-5-branded-videos-mrbeast-dude-perfect-jesse-moncur/")],
                "body": [
                    "Tubefilter publishes a weekly ranking of the most-watched branded videos on YouTube, using data from Gospel Stats.  This week's chart, in order: <mark>MrBeast with Call of Duty Mobile at 104,169,846 views, MrBeast 2 with Jack Link's at 23,032,812, Dude Perfect with BODYARMOR at 12,402,563, and Jesse Moncur with Strider Bikes at 11,025,413.</mark>  A bonus entry, JustAli carrying two sponsors, did 54,380.",
                    "Four of those five tell you nothing you can act on.  Big creator posts video, video gets big numbers.  The explanation offered for the second entry is essentially the size of the audience, which is a description rather than a cause.",
                    "The third entry is different.  Dude Perfect's School Stereotypes, sponsored by the sports drink brand BODYARMOR, is described by Tubefilter as <mark>the most-requested video in Dude Perfect's history</mark> — the audience had been asking for it before it was made.  The brand did not attach to a concept somebody pitched in a room.  It attached to a thing people had already said they wanted.",
                    "It is the only free input available in a creator brief, and it is the one most briefs write over.  Every creator with a comment section is sitting on a list of videos their audience has asked for and they have not got round to making.  That list is not a survey and should not be read as one — there is no sample frame and no denominator.  It is still the only demand signal you can get before you spend anything, and the creator will usually tell you what is on it if you ask.",
                    "Keep the bonus entry in view as the floor, too.  <mark>A mid-size creator carrying two sponsors did 54,380 views in the same week the top entry did 104 million.</mark>  Both of those are branded videos.  Both would appear in a deck as creator content.  They are three orders of magnitude apart, and the thing separating them has nothing to do with how well either was made.",
                ],
                "flagnote": "View counts are as published on 15 September and will have moved since.  Tubefilter's ranking is ordered by views, not by anything resembling effectiveness — there is no spend, no cost per person reached, no measure of whether anybody remembered the brand afterwards, and no sales data attached to any entry.  The most-requested-in-history claim is Tubefilter's characterisation and we have not seen Dude Perfect's underlying request data.",
                "so_what": "Almost every creator brief starts with the brand's idea and asks the creator to carry it, which means you are paying for distribution and gambling on demand.  Reversing that order costs nothing and removes the biggest single unknown, because the audience has already told you they want it.  The concession is that you do not get to pick the concept, and the video will be about what they care about rather than what you wanted to say.",
                "do_this": "Ask your next three creator partners one question before you brief anything — what is the video your audience keeps asking for that you have not made yet — and fund the answer.  Put your product inside their idea rather than asking them to carry yours, and hold the brief to a single thing you need said.",
            },
        ],
    },
    {
        "id": "ls", "name": "L'S", "page": "pg. 03",
        "note": "what broke, and the failure mode underneath it",
        "tint": "pink",
        "items": [
            {
                "title": "Wrong critic: Novig modelled the audience sensibly and ignored the constituency, and got a run of professional athletes explaining what was wrong with its ad",
                "hook": "Roughly 70 percent of sports bettors are men, so the people offended were largely not the people buying.  That calculation was probably sound.  It left out who else was standing nearby with a camera.",
                "open": True,
                "stamps": [
                    ("FORTUNE · 16 SEP", "https://fortune.com/2026/09/16/sydney-sweeney-novig-ad-sports-prediction-market-female-athletes-why-it-went-wrong/"),
                    ("ADWEEK · 14 SEP", "https://www.adweek.com/brand-marketing/one-year-post-american-eagle-scandal-sydney-sweeney-sparks-ire-by-going-naked-for-novig/"),
                ],
                "body": [
                    "Novig is a sports prediction market, a service where people bet on sporting outcomes.  Its first national campaign is <mark>a 42-second spot</mark> featuring Sydney Sweeney nude behind strategically placed sports equipment — footballs, a basketball, a tennis racket, a golf club, a pool table — with the word sports repeated over it.  Adweek reports that <mark>Sweeney is not only the face of it but a partner and equity stakeholder in the company.</mark>",
                    "The commercial logic is legible and it is not stupid.  Adweek cites an estimate that <mark>70 percent of sports bettors are men</mark>, and a 2013 study in the Journal of Advertising finding that males evaluate ads with sexual appeals significantly more positively than females.  Novig chief executive Jacob Fortinsky said the campaign was about closing the gap from a brand-awareness perspective, and that Sydney is an actress, we're a prediction market focused on sports.",
                    "What the model left out is that this category has a professional constituency who are not customers, are extremely visible, and were handed a perfect rebuttal format.  <mark>Four-time Olympic swimming gold medallist Ariarne Titmus: I can't describe how infuriated I feel when I watch this.  British sprinter Amy Hunt: Sydney Sweeney, this is what women in sport look like.</mark>  Australian surfer Felicity Palmateer asked how far you can set women's sport back in the space of a 42-second commercial.",
                    "Notice the shape of Hunt's reply, because that is the actual failure.  It is one line of text over a video of herself training.  Every professional athlete on earth already has that footage on their phone.  An ad that stamps the word sports over somebody who does not play one hands a ready-made, free, high-quality reply to every professional athlete with a following and a personal stake in correcting it.  You did not buy a controversy.  You commissioned an open brief for your opponents.",
                    "And there is no number on the other side of the ledger.  No app downloads, no impressions, no engagement figure, no sales — nothing has been published by anybody that would let you say the attention was worth it.  Which means for now this is a cost with no measured benefit, and anyone telling you it worked is inferring.",
                ],
                "flagnote": "No performance data for this campaign exists in public.  Every claim that the backlash was strategically valuable, including our own framing of the trade, is inference rather than measurement.  Sweeney's equity stake is reported by Adweek without a formal title or terms.  Fortune's account does not mention the stake at all.  The 70 percent figure is described by Adweek as one recent estimate with no source named, so treat it as directional.  Neither outlet reports any response from Novig to the athletes specifically.",
                "so_what": "Audience modelling tells you who will buy and says nothing about who will be watching over their shoulder with standing to object.  In any category built on a sport, a craft or a profession, the practitioners are a second audience with more credibility on the subject than your brand will ever have, and you do not get to opt out of being judged by them.  The specific trap here is that the ad's own line invited the comparison — it claimed to be about sport, in a category full of people whose job is sport.",
                "do_this": "Before your next campaign in a category built around an activity, write down the ten most visible practitioners of that activity and ask one plain question of the cut: does this give any of them an easy, flattering thing to post in reply.  If it does, change the line before you change the casting, because the line is what handed them the format.",
            },
            {
                "title": "Wrong measure: the company that just launched livestream brand-mention tracking says in its own launch post that it cannot prove a mention was the sponsored one",
                "hook": "Ten dollars a month per keyword, and a vendor being unusually honest about the limits of its own product.  Keep the disclaimer it wrote for the next agency deck that counts mentions at you.",
                "stamps": [("STREAMS CHARTS · 15 SEP", "https://streamscharts.com/news/brand-monitoring-live-streaming-gap-your-social-listening-stack")],
                "body": [
                    "Streams Charts launched Brand Radar this week.  It tracks brand mentions in live chat messages and channel bios across Twitch, Kick and YouTube Gaming, and returns the channel, the author, a timestamp, the message text, the follower count and the average viewers for each one.  Reports run over 24 hours, 7 days or 30 days.  <mark>The first keyword is free and each additional keyword is 10 dollars a month.</mark>",
                    "The pitch is that the established social listening tools handle posts, comments, news and review sites and none of them read live chat.  That is a real gap and at ten dollars a keyword it is cheap enough to run without a purchasing process.",
                    "Then the company writes this about its own product.  <mark>It counts mentions; it does not score sentiment, weight by reach, or prove that a mention was the sponsored one.</mark>  And this: <mark>Brand Radar reads live chat and channel bios — not stream titles, and not speech, so nothing a streamer said out loud is in here.</mark>",
                    "Sit with the second one for a moment.  The single most valuable thing that happens in a sponsored stream is a person saying your brand name out loud to an audience that trusts them.  That is the thing you paid for.  It is not in the data.  What is in the data is what viewers typed in chat, which is a different event with a different cause, and it will include people complaining about you.",
                    "<mark>Streams Charts also notes that YouTube coverage is thin — on its own Red Bull demonstration report, the YouTube share of mentions was under 1 percent.</mark>  So YouTube is effectively uncovered and this is mostly a Twitch and Kick monitor, which matters if your money is not going there.",
                    "None of this makes the product bad.  It makes it a chat monitor, which is a useful and modest thing.  The problem arrives when a number from a chat monitor turns up in a results deck under a heading about campaign performance, and the gap between what was measured and what is being claimed is the width of the entire sponsorship.",
                ],
                "so_what": "Livestream sponsorship currently has no way to connect the money you spent to the mention it bought, and the vendor selling the measurement has said so in writing on its own website.  Mentions counted in chat are a proxy for how much people are talking, not for whether your read landed, and the two can move in opposite directions — a badly received sponsorship generates a lot of chat.  The honest position is that live is a format you buy on units sold or on sign-ups, not on mentions.",
                "do_this": "When a livestream campaign is reported back to you on brand mentions, ask two questions before you accept the number — were spoken mentions measured, and can you show me which of these mentions came from the sponsored broadcasts.  If the answer to either is no, move the reporting to something you can count directly, such as a unique code or link used during the stream.",
            },
        ],
    },
    {
        "id": "moves", "name": "MOVES", "page": "pg. 04",
        "note": "platform, policy and legal changes that alter what you can make and buy",
        "items": [
            {
                "title": "YouTube quietly moved its line on graphic gaming violence and drugs, and the inventory your exclusion list was built to avoid is now ad-eligible",
                "hook": "Graphic gaming content in the first eight to fifteen seconds now earns ad revenue.  Only the first seven seconds stays ineligible.  Your brand safety settings were calibrated against the old line.",
                "open": True,
                "stamps": [
                    ("YOUTUBE HELP · SEPTEMBER 2026 UPDATES", "https://support.google.com/youtube/answer/9725604?hl=en"),
                    ("DEXERTO · 4 SEP", "https://www.dexerto.com/gta/youtube-updates-gaming-violence-monetization-rules-ahead-of-gta-6-launch-3405945/"),
                ],
                "body": [
                    "Two entries dated September 2026 have appeared on YouTube's own advertiser-friendly guidelines page.  The first, in its words: <mark>content featuring graphic gaming content in the first eight to fifteen seconds will earn ad revenue.  Content featuring graphic gaming content in the first seven seconds will continue to be ineligible for ad revenue.</mark>",
                    "The second: <mark>gaming and scripted content featuring the use, sale, and promotion of recreational drugs is now eligible to earn ad revenue.</mark>  Public service announcements and non-glorifying educational content about drug trafficking organisations become eligible too.",
                    "The timing is worth noting even though YouTube has not linked the two.  Grand Theft Auto VI launches on 19 November into what is widely expected to be the heaviest gaming quarter YouTube has handled.  A platform that demonetised the opening seconds of violent gameplay was about to demonetise a large share of the biggest category on its own service.",
                    "The consequence for a creator is straightforward and good — more of their work earns money.  The consequence for a brand runs the other way, and it is the one nobody will send you a note about.  <mark>YouTube's own demonetisation has been doing a quiet share of your brand safety work for years.</mark>  Inventory that simply did not carry ads is inventory you never had to exclude.  That filter has moved, and your exclusion lists and suitability settings were built against where it used to be.",
                    "This is live now, not upcoming.  If you buy anything against gaming content between now and Christmas, the pool you are bidding into is not the pool you were bidding into in July.",
                ],
                "flagnote": "YouTube has not stated a reason for the change; the connection to Grand Theft Auto VI is our inference from the dates.  The trade coverage ran in early September and the guideline entries carry a September 2026 date, so the exact day it took effect is not published.  YouTube's page does not enumerate what remains ineligible under the recreational drugs change, and we have not found a published list.  Content built primarily to shock has previously remained fully demonetised under separate rules, and we have no confirmation that has changed.",
                "so_what": "Brand suitability tools are usually set once and reviewed when something goes wrong, and most of them were tuned against a platform whose own monetisation rules removed the worst material before anybody had to think about it.  When the platform loosens, every downstream setting silently becomes more permissive without anyone touching it.  That is a change in what you are buying that arrives with no notification, no invoice line and no meeting.",
                "do_this": "Pull your YouTube exclusion lists and content suitability settings this week and re-run them against gaming inventory specifically, before the Grand Theft Auto VI window opens in November.  Decide deliberately whether you want the newly eligible material in or out, and write the decision down so the next person to inherit the account knows it was a choice.",
            },
            {
                "title": "The clause underneath the proposed EU KIDS Act is the one that would change reach: recommendation by engagement switched off by default for everyone under 18",
                "hook": "We covered the Commission publishing its proposal yesterday.  This is what is actually in Article 10, and it is a different problem from the age limits.",
                "stamps": [("PPC LAND · 17 SEP", "https://ppc.land/eu-kids-act-sets-6-month-deadline-to-disable-existing-under-15-accounts/")],
                "body": [
                    "The headlines on Wednesday were about ages — no autonomous account under 15, guardian-controlled accounts capped at an hour a day for 13 and 14 year olds.  Underneath that sits the provision that changes how video travels.",
                    "<mark>Recommender systems must disable by default any recommendation driven by implicit engagement-based signals drawn from a minor's behaviour.</mark>  Implicit engagement signals means watch time, clicks, replays — the behavioural exhaust that every recommendation system on every short-form feed runs on.  Platforms must use stated preferences instead and cannot fall back on outside data for anyone under 18.  Autoplay goes, streaks and reward mechanics go, and push notifications unrelated to what the user did go.",
                    "Then the operational deadline.  <mark>Within six months of the regulation applying, platforms must check the ages of existing account holders and disable every account confirmed as under 15 or that cannot be verified.</mark>  Enforcement runs to administrative fines of up to 6 percent of worldwide annual turnover.  The regulation enters into force 20 days after publication in the Official Journal, and applies six months after that.",
                    "Work through what that does to a feed.  If a meaningful share of the audience for a category is under 18 and their behaviour no longer feeds ranking, the signal that decides what surfaces gets thinner for everybody in that category, not only for the minors.  Add the account sweep, which removes a cohort and their history from the inputs entirely, and the ranking quality for youth-skewing content in Europe degrades twice over.",
                    "This is still a proposal and it has to get through Parliament and Council.  Parliament's own report last November wanted the threshold at 16, not 15, so the final age is unlikely to be the one in the draft.  What is not in dispute between them is the policy itself — engagement-based recommendation switched off for minors.",
                ],
                "flagnote": "This is a Commission proposal, not law, and the ordinary legislative procedure can take many months.  The age threshold is explicitly contested between Parliament and Commission.  Our reading of the downstream effect on ranking quality is an inference from how recommendation systems work, not something the regulation states or that anybody has measured.  France's own constitutional court struck down a comparable national ban in August, so the legal path is not clear.",
                "so_what": "Every organic reach plan in Europe for a brand with a young audience is built on a recommendation system that learns from what those viewers watch.  Take the learning signal away from that cohort and the feed gets worse at finding them, which does not mean they disappear — it means they have to be reached deliberately and paid for.  The part to plan around is that this arrives as a gradual degradation with no announcement date, not as a switch you can diarise.",
                "do_this": "Reprocess the last twelve months of your European reporting by age band now, so you hold a clean picture of organic reach to under-18s from before the rules rather than starting the clock today.  Then price a paid route to that group into your 2027 plan rather than assuming the feed keeps delivering them.",
            },
            {
                "title": "Disney signed Like Nastya, which has 250 million subscribers and 123 billion views, and did not disclose a single number about the deal",
                "hook": "The archive goes to Disney+, and new originals go to Disney Junior and Disney+.  No terms, no timeline, no episode count — which is itself the thing worth noticing.",
                "stamps": [("TUBEFILTER · 17 SEP", "https://www.tubefilter.com/2026/09/17/like-nastya-radzinskaia-disney-plus-development-deal/")],
                "body": [
                    "Like Nastya is the channel built around Anastasiia Radzinskaia.  <mark>It was the first kid creator channel to reach 250 million YouTube subscribers, and the flagship channel has 123 billion lifetime views.</mark>  Disney is bringing the archive to Disney+ and commissioning new videos aimed at kids, tweens, teens and families across Disney Junior and Disney+.",
                    "Anna Radzinskaia, Anastasiia's mother and the founder of the operation, said bringing together the worlds of Like Nastya and Disney is an exciting opportunity to create something truly special for a new generation.",
                    "Tubefilter puts it alongside Bluey and the incoming CoComelon as Disney assembling a children's slate out of properties that were built somewhere else.  The read is that the most reliable children's intellectual property of the last decade was made on YouTube by families with cameras, and the studios are now buying it rather than competing with it.",
                    "The thing to take from this if you commission anything for families is narrower and more useful.  A channel with 123 billion views has more evidence about what holds a four-year-old's attention than any research a studio could commission, and that evidence is public.  It is sitting in the view counts of individual videos, sorted by popularity, available to anybody who opens the channel page.",
                ],
                "flagnote": "No financial terms, no timeline, no episode counts and no premiere dates were disclosed.  Development deals frequently produce nothing at all.  The subscriber and view figures are the channel's own public YouTube numbers and count multiple language channels in the network differently depending on how you total them.",
                "so_what": "Studios commissioning creator properties rather than competing with them suggests the traditional development process has lost its information advantage: a channel with a decade of uploads has already run thousands of tests on a real audience and published the results in public view counts.  The deal itself is a development agreement with no terms attached, so do not read it as a price signal about what creator archives are worth.  Read it as a statement about where the evidence is.",
                "do_this": "If you make anything aimed at families, spend an hour this week sorting two large children's channels by most popular and writing down what the top twenty videos have in common — length, thumbnail, first five seconds, whether an adult appears.  Bring that list to your next concept meeting instead of a competitor reel.",
            },
        ],
    },
    {
        "id": "onstream", "name": "ON STREAM", "page": "pg. 05",
        "note": "live audiences, what the numbers actually measure, and what a sponsor got",
        "items": [
            {
                "title": "Rocket League's qualifier grew hours watched 46.5 percent and the broadcast ran 35 minutes longer, and the honest growth number is the one nobody put in the headline",
                "hook": "Hours watched were up 46.5 percent, peak was up 40.5 percent, average was up 30.9 percent.  Three growth numbers for one event, and the gap between the biggest and the smallest is the item.",
                "open": True,
                "stamps": [
                    ("ESPORTS CHARTS · 17 SEP", "https://escharts.com/news/rlcs-2026-world-championship-play-in"),
                    ("ESPORTS CHARTS · 15 SEP", "https://escharts.com/news/overwatch-world-cup-2026-viewership-record"),
                ],
                "body": [
                    "The RLCS 2026 World Championship Play-In is the qualifying stage for Rocket League's world championship.  <mark>Peak concurrent viewers hit 173.2 thousand, up 40.5 percent year on year.  Average concurrent viewers grew 30.9 percent.  Hours watched came in above 782 thousand, up 46.5 percent.  The broadcast ran about 35 minutes longer than last year's.</mark>",
                    "Peak concurrent viewers is the largest number of people watching at any single instant, added up across every channel carrying it.  173.2 thousand is roughly two Wembley Stadiums, full — about 180,000 seats — at the same moment.  Average concurrent viewers is the number sustained across the whole broadcast, and it is the one you should price against, because it is the audience that was actually there for the duration.",
                    "Now the gap between those three numbers.  Hours watched grew most, at 46.5 percent.  Hours watched is average concurrent viewers multiplied by how long the broadcast lasted, so a longer broadcast inflates it without a single extra person turning up — and this one ran 35 minutes longer.  <mark>Peak grew 40.5 percent and average grew 30.9 percent, and the average is the honest one.</mark>  Quote the 46.5 and you are describing growth as half as much again as the sustained audience actually managed.",
                    "Esports Charts published the average as a percentage change only and did not publish the absolute number, which means you cannot compute cost per thousand people reached from this release at all.",
                    "For the ratio you need when somebody quotes you a peak with nothing beside it, use the Overwatch World Cup two days earlier.  <mark>Peak 401 thousand, average 173.1 thousand — note that this one is an average, not a peak like the Rocket League figure above — and 10.1 million hours watched</mark>, beating a peak record of 321.9 thousand that had stood since 2017.  <mark>The average is 43 percent of the peak.</mark>  That is our arithmetic, and it is a reasonable sanity check — when someone hands you a peak concurrent figure and no average, work on a sustained audience a little under half of it until they show you otherwise.",
                    "One more from the Rocket League release that is worth a diary note rather than a decision.  <mark>The official English TikTok channel grew its watch time by more than 1,300 percent year on year</mark>, and Spanish became the second most-watched language.  That percentage is off a tiny base and means very little about scale.  What it means is that live esports distribution is moving onto a platform with completely different advertising products from Twitch.",
                ],
                "numbers": [
                    ("173.2k", "peak concurrent viewers for the Rocket League qualifier, roughly two full Wembley Stadiums at one instant"),
                    ("43%", "the Overwatch World Cup's average concurrent viewers as a share of its peak — our arithmetic, and a usable sanity check"),
                    ("35 min", "of extra broadcast time inflating a 46.5 percent rise in hours watched"),
                ],
                "flagnote": "Esports Charts and Streams Charts are sister products from the same company, and that company sells the measurement and launched a paid brand-tracking product this same week.  All figures are estimated from platform data, not audited.  Esports Charts published the Rocket League average as a percentage change with no absolute figure, and published no airtime for the Overwatch World Cup, so the 43 percent ratio comes from one event and should not be treated as a constant.  No sponsorship or disclosure data was published for either event.",
                "so_what": "Hours watched is the number a rightsholder reaches for because it goes up when the broadcast gets longer or when more co-streamers join, neither of which is more audience.  Peak is the number that gets into headlines because it is the biggest.  Average concurrent viewers is the only one of the three that describes what a sponsor actually bought, and it is the one most often left out of the release.  When all three are published you can see the gap, and here it was almost sixteen percentage points wide.",
                "do_this": "Write average concurrent viewers into your next live sponsorship contract as a reported deliverable alongside peak, with the broadcast duration stated, and make payment reporting reference the average.  When a seller offers only peak and hours watched, take a little under half the peak as your working assumption and tell them that is what you are pricing against.",
            },
        ],
    },
    {
        "id": "money", "name": "THE MONEY", "page": "pg. 07",
        "note": "what things cost, who is funding what, and what the market says it values",
        "items": [
            {
                "title": "Car brands cut television spending 15.4 percent in August and their household impressions fell 20.2 percent, so the money they kept bought less than it did last year",
                "hook": "The forecasts all went up this month.  This is the only hard measured spend number in the set and it went down, which is the contrast nobody is running.",
                "open": True,
                "stamps": [("MEDIAPOST · 17 SEP", "https://www.mediapost.com/publications/article/418078/automotive-tv-spending-falls-154-in-august.html")],
                "body": [
                    "The figures come from iSpot, which tracks national television advertising directly rather than surveying anybody.  <mark>Automotive television spending in August was 72.5 million dollars against 85.7 million a year earlier, down 15.4 percent.  Household impressions were 14.2 billion against 17.8 billion, down 20.2 percent.</mark>  Year to date, roughly 1.1 billion dollars against roughly 1.3 billion, which iSpot puts at down 14.8 percent, with impressions down 16 percent.",
                    "The two August percentages do not match, and the gap is the item.  Spending fell 15.4 percent and household impressions fell 20.2 percent, <mark>which means the cost of a thousand household impressions rose about 6 percent for these advertisers in August.</mark>  That is our arithmetic from the two published figures.  They spent less, and each remaining dollar bought fewer impressions than it did a year ago.",
                    "Top spenders for the month: <mark>Kia at 10.5 million dollars, Mercedes-Benz at 8 million, Lexus at 6.5 million, Toyota at 6.2 million, Hyundai at 5.2 million.</mark>",
                    "Where the surviving money went is the second half of the story.  <mark>NFL preseason took 22 percent of total automotive industry spending, and seven of the top ten programmes by automotive reach were sport.  WNBA impressions were up 126 percent year on year and NFL impressions up 35 percent.</mark>  Stuart Schwartzapfel, executive vice president at iSpot, singled out the WNBA increase.",
                    "So a category retreating from television is not retreating evenly.  It is abandoning the general schedule and concentrating what is left into live sport, which is the one thing on television that people still watch at the same time as each other and cannot skip.",
                ],
                "flagnote": "iSpot measures national linear television only.  There is no connected-television or digital video breakout in this data, so some of this decline is very likely money moving channels rather than leaving the category, and this release cannot tell you which.  iSpot is a measurement vendor.  The 6 percent rise in cost per thousand household impressions is our calculation from the published spend and impression figures, not a number iSpot published.  Impressions count repeat exposures to the same household, so this is not a measure of how many distinct households were reached and should not be read as one.  The year-to-date dollar figures are published rounded to one decimal place, so the 14.8 percent is iSpot's and does not reconcile exactly against 1.1 versus 1.3.",
                "so_what": "When a category cuts its television budget, the cheap general inventory goes first and the expensive appointment inventory survives, so the average cost of what remains rises even as the total falls.  That is why spending less can leave you paying more per exposure, and it is the mechanism that pushes big advertisers towards owning a channel rather than renting one.  The sports concentration is the same instinct in its most expensive form — paying a premium for the last places where an audience shows up on purpose.",
                "do_this": "Take your own spend and impressions for the last twelve months, divide one by the other month by month, and see whether your cost per thousand impressions is rising while your budget falls.  If it is, model what the same money would buy as production on a channel you own, and bring both numbers to the same meeting.",
            },
            {
                "title": "Two forecasts went up this month, and the only video line anybody trimmed was ordinary web video",
                "hook": "The IAB raised its 2026 US forecast from 9.5 to 12.3 percent.  Connected television and social video were both revised up.  Digital video that is not on a television set was the one line revised the other way, by two tenths of a point.",
                "stamps": [
                    ("IAB · 10 SEP", "https://www.iab.com/news/iab-raises-2026-u-s-ad-spend-forecast/"),
                    ("MEDIAPOST · 9 SEP", "https://www.mediapost.com/publications/article/417751/ad-outlook-composite-improves-on-mw-upgrade.html"),
                ],
                "body": [
                    "The IAB now puts 2026 US advertising growth at <mark>12.3 percent, revised up 2.8 points from the 9.5 percent it forecast in January.</mark>  The channel detail is where the decision sits.  <mark>Social at 16.5 percent, revised up from 14.6.  Connected television — ads served to a TV set over the internet rather than broadcast — at 15.6 percent, up from 13.8.  Commerce media, meaning advertising sold by retailers on their own sites and apps, at 13.6 percent, up from 12.1.  Digital video excluding connected television at 9.4 percent, revised down from 9.6.  Linear television at minus 1.5 percent.</mark>",
                    "Be careful with that one.  Every digital video line is still forecast to grow, and 9.4 percent growth is not a collapse.  But it is the only video line the forecasters moved downwards, and it is the one that is neither on a television set nor native to a social feed.  Two tenths of a point is well inside the noise of a 200-person survey, so treat it as a direction of travel rather than a finding — the money is being revised up at both ends of the screen size range and left alone in the middle.",
                    "Separately, the independent analyst Brian Wieser at Madison and Wall raised 2026 global growth by 2.2 points to 11.6 percent and <mark>US growth by 3.5 points to 15.6 percent</mark>, with 2027 at 5.9 percent globally and 4.1 percent in the US.",
                    "Read all of that with two things held firmly in view.  The IAB number is a survey of roughly 200 brand and agency decision-makers, so it is stated intent rather than measured spend.  And the growth is attributed partly to the Winter Olympics and the FIFA World Cup, which is cyclical and does not repeat next year.  Wieser's US figure includes political advertising, which is why 2027 drops to 4.1.",
                    "Set that against the automotive numbers above.  Total spending is forecast to rise, and to rise in connected television, social and commerce, while a measured category cuts its general television buying and pays more for each exposure it keeps.",
                ],
                "flagnote": "The IAB is a trade body whose members sell digital inventory, and its forecast is a survey of about 200 decision-makers with no dollar total, no confidence intervals, no sampling weights and no fieldwork dates published.  Madison and Wall's US figure includes political advertising and is not separated out.  Both are forecasts, not measurements.  The IAB's own chief executive hedged publicly that the economy has real areas of uncertainty and there are no easy wins.",
                "so_what": "Every forecast revision this month went up and every one of them leans on a sporting calendar that does not repeat, so the 2027 numbers are the ones describing the underlying market.  The useful signal is not the headline growth but which lines moved in which direction, because that is where the people writing cheques think attention is going.  Both ends of the screen size range got raised and the middle did not.",
                "do_this": "Look at where your own video sits on that split — big screen, social-native, or in-page web video — and if a meaningful share is the middle option, move a test budget to the other two this quarter.  Plan 2027 against the lower growth figures rather than this year's, because the Olympics and the World Cup are not in next year's numbers.",
            },
            {
                "title": "The reason finance teams will not fund creator work is a filing problem, and one marketer described the fix out loud this week",
                "hook": "Book it as production rather than as media.  That is the whole move, and it works because a production budget and a new channel are judged against completely different standards.",
                "stamps": [("DIGIDAY · 16 SEP", "https://digiday.com/media/iab-creator-upfront-why-a-half-built-infrastructure-is-holding-back-cfo-buy-in/")],
                "body": [
                    "At the IAB's first creator sales event in New York on 15 September, the stated blocker on bigger creator budgets was not belief.  It was that the numbers cannot be reconciled.  <mark>The three named friction points: nobody agrees what counts as a view, performance measurement is inconsistent between platforms, and creators are hard to price and buy at scale.</mark>",
                    "The 44 billion dollar figure in the quote below is the IAB's own projection of US creator advertising spend for 2026.  James Douglas, a vice president at the IAB, put the scale problem plainly: <mark>improvisation is easy when a market is small.  But at 44 billion dollars, it's going to break, and it's not going to be fair and equitable and truly opportunistic for everyone.</mark>",
                    "The practical answer came from Ankur Goyal, chief marketing officer at Ultra Pouches, and it is a filing decision rather than a strategy.  His description was flat: <mark>creators became our creative production house for so many of our paid channels already.</mark>  The instruction we would draw from it, which is ours and not his, is to book the spend as a production line rather than as a separate channel.  Finance departments have approved production budgets for decades without requiring a cross-platform measurement standard to exist.  A new channel has to prove itself.  A production cost has to be justified.  Those are very different conversations, and only one of them is winnable this year.",
                    "The one hard performance figure offered on stage came from Karin Tracy, group lead for retail and ecommerce at Meta, who said creator commerce work produced <mark>a 19 percent reduction in cost per action</mark> — cost per action being what you pay for each sale or sign-up.  No methodology, no sample, no time period.",
                    "The event produced a survey of the people in the room, which the IAB says it will use to set up working committees in the final quarter of this year.  Nothing was standardised.  If you are building a 2027 plan that assumes a common definition of a view arrives, do not.",
                ],
                "flagnote": "Meta's 19 percent cost-per-action figure was given on stage by a Meta executive with no methodology, sample size or time period, and Meta sells the inventory it describes.  The 44 billion dollar figure is the IAB's own projection of 2026 US creator advertising spend, not measured spend, and the IAB is a trade body funded by companies selling this inventory.  Nothing at the event produced a standard — it produced a survey and a plan for committees.",
                "so_what": "The money for creator video is usually not blocked by a disagreement about whether it works, it is blocked by the fact that it cannot be compared to anything else in the budget.  Moving it into a bucket that finance already accepts is not a trick, it is an accurate description — a creator making four cuts of an advertisement is a production supplier, and the media spend that amplifies it is a separate thing that can be filed separately.  The people who get this funded in the next twelve months will be the ones who stopped asking for a new line.",
                "do_this": "Split your next creator proposal into two numbers before it goes to finance — what you are paying for the making of the assets, and what you are paying to put media behind them — and file the first as production.  Bring one example of a creator asset that outperformed an agency-made one in the same slot, because that is the comparison a production budget is actually judged on.",
            },
        ],
    },
    {
        "id": "format", "name": "FORMAT LAB", "page": "pg. 08",
        "note": "shapes of video that are working, and how they are put together",
        "items": [
            {
                "title": "Brands are turning up at a television sales market in October to pitch content slates to distributors, which is a different business from running a channel",
                "hook": "Vinted, L'Oreal Luxe, Jamie Oliver with Life360, and a documentary headed for Prime Video.  Brand content looking for third-party distribution instead of being posted on the brand's own page.",
                "open": True,
                "stamps": [("TUBEFILTER · 17 SEP", "https://www.tubefilter.com/2026/09/17/mipcom-2026-conference-programming-vertial-series-branded-content-gen-ai/")],
                "body": [
                    "MIPCOM runs 12 to 15 October at the Palais des Festivals in Cannes, and is the market where television distributors buy and sell finished programming.  This year it adds MIP BrandWorks — a summit for senior leaders, followed by a showcase that Tubefilter describes as a presentation of individual brands and their content in the same shape as a television sales pitch.  <mark>Over 10,000 attendees are expected, and tickets start at 1,780 euros.</mark>",
                    "The named projects tell you what shape this content is taking.  <mark>Webedia-Elephant is bringing The Engineers of the Future for Prime Video and cultural content for L'Oreal Luxe on YouTube.  Baby Teeth has Finding Jamie, a vertical series with Jamie Oliver and Life360.  Vinted has a format called Live Better for Less, made with WPP, Fan Club and Electric Robin.</mark>  Bluelemon is presenting on brands, rights holders and creators on YouTube.",
                    "<mark>Meta, Dentsu and Ferrero Rocher are all presenting on vertical dramas</mark> — short, phone-shaped serialised fiction, released in very short episodes.  A platform, an agency group and a confectionery brand, all betting on the same shape.",
                    "The move being made here is the one worth understanding.  A brand that posts its series on its own channel owns the audience and has to build it from zero every time.  A brand that sells or licenses a series to a distributor gives up ownership and gets carriage — the show turns up somewhere people already are, with a slot and a promotion budget attached.  Those are opposite trades and most brands have only ever considered the first one.",
                    "Note which project is aimed where.  An engineering documentary is being taken to Prime Video.  Cultural content for a cosmetics group is going to YouTube.  A series with a celebrity chef is being cut for the phone.  Nobody is putting everything in one place, and the fit between the format and the destination is doing the work.",
                ],
                "flagnote": "This is a preview of an event that has not happened, based on the organiser's own programme.  The attendance figure is an organiser projection.  No budgets, no viewing figures and no results have been published for any of the named projects, and several have not been released.",
                "so_what": "Owned video carries two costs where licensed video carries one: you pay to make it, then you pay again for distribution you do not own.  Licensing it to a distributor swaps the second cost for a loss of control and a loss of the data.  Whether that is a good trade depends entirely on whether your series can survive being introduced by somebody else, which most brand content cannot because the brand is the reason it exists rather than the reason to watch.",
                "do_this": "Take the owned series you are proudest of and ask one question of it — would a distributor put this in a slot without being paid to.  If the answer is no, spend this quarter's development budget making the premise strong enough to stand on its own, and stop asking the channel to carry the show.",
            },
        ],
    },
]

FORECAST = [
    {
        "confidence": "LIKELY",
        "window": "by 30 June 2027",
        "headline": "Ad load appears as a buyable tier on a streaming rate card, priced above standard inventory",
        "body": "There is now a published number putting a fifteen-point recall gap between light and heavy ad breaks, and the arithmetic says the trade is close to symmetric for the publisher — give up 58 percent of the ad time, deliver 58 percent more recall.  That is exactly the shape of a product: a premium tier that costs the seller real inventory and can therefore be priced.  The reason it has not existed is that no buyer was asking, and the reason it will is that a buyer now has a study to point at.  Expect the first version to be sold as an attention or premium environment product with the load buried in the specification rather than in the name.",
        "do": "State a maximum ad load in your next two streaming briefs, then keep a record of which sellers can answer and which cannot, because that list is what tells you who is building the tier before it goes on sale.",
    },
    {
        "confidence": "WATCH CLOSELY",
        "window": "by 31 December 2027",
        "headline": "A brand publishes a measured drop in European organic reach among under-18s and blames the recommendation rules",
        "body": "The KIDS Act would switch off engagement-based recommendation for everyone under 18 and force platforms to remove unverifiable under-15 accounts within six months of application.  Neither of those produces an announcement on the day it starts biting — they produce a slow degradation in how well a feed finds a young audience.  Somebody with clean year-on-year age-banded data will notice, and because the regulation is contested and politically loud, they will say so publicly.  The reason this might not happen is that most brands do not report reach by age band with enough consistency to see it, which is also why the baseline matters now.",
        "do": "Ask your two largest European platform representatives what they intend to do about ranking for the under-18 cohort, and get the answer in an email, because their plan is what decides whether your reach survives this.",
    },
    {
        "confidence": "LIKELY",
        "window": "by 31 December 2027",
        "headline": "Reported creator marketing spend grows more slowly than actual creator spend, because more of it gets filed as production",
        "body": "The blocker described at the IAB event is that creator budgets cannot be reconciled against anything else, and the workaround named on stage is to file the money as creative production instead.  That workaround spreads because it works and it costs nothing to adopt.  The consequence is a measurement problem for everybody trying to size this market — spend booked as production does not show up in creator marketing surveys, so the published totals will understate the real number by a growing margin.  Watch for the first forecaster to publish a restatement or add a production category.",
        "do": "Keep your own internal record of total creator spend regardless of which budget line it comes from, so that your year-on-year comparison stays honest even as the external benchmarks drift.",
    },
    {
        "confidence": "LONG SHOT",
        "window": "by 30 June 2027",
        "headline": "A livestream rights holder starts publishing average concurrent viewers as standard because a buyer refused to renew without it",
        "body": "Average concurrent viewers is the only live metric that describes what a sponsor bought, and it is routinely left out while peak and hours watched are published.  That is not an accident — the average is always the least flattering of the three.  It changes when a large enough buyer makes reporting it a condition of renewal, and the conditions for that are assembling: a measurement vendor has just admitted in writing it cannot attribute a mention to a sponsorship, and hours watched keeps being inflated by longer broadcasts.  It stays a long shot because the buyers big enough to force it are mostly gaming publishers who are also sellers of the same attention, and they have no reason to push a standard that would reprice their own inventory.",
        "do": "Find one live contract coming up for renewal in the next six months and ask for average concurrent viewers to be added to its reporting schedule now, so you learn how that seller reacts while the renewal is still your strongest card.",
    },
]

TLDR = [
    "FreeWheel and MediaScience tested 436 people and found the identical thirty-second ad was recalled unprompted by 41 percent of viewers in a light ad break and 26 percent in a heavy one, with nothing about the ad changed.  Ask your next streaming seller what the ad load is on the inventory offered, in minutes per half hour, insist on a range rather than a single average, and be willing to pay more for the lighter one.",
    "Automotive television spending fell 15.4 percent in August while household impressions fell 20.2 percent, which by our arithmetic means the cost of a thousand household impressions rose about 6 percent, and NFL preseason took 22 percent of what the category spent.  Divide your own spend by your own impressions month by month for the last year, and if the cost is rising while the budget falls, model what that money buys as production on a channel you own.",
    "YouTube has loosened its advertiser-friendly rules so graphic gaming content in the first eight to fifteen seconds now earns ad revenue, and gaming and scripted content featuring recreational drugs is eligible too, weeks before Grand Theft Auto VI launches on 19 November.  Re-run your YouTube exclusion lists and suitability settings against gaming inventory this week and write down whether you want the newly eligible material in or out.",
    "The European Commission's KIDS Act proposal would make platforms switch off recommendation driven by watch time and clicks for every user under 18, and remove existing under-15 accounts within six months of the rules applying, with fines up to 6 percent of worldwide turnover.  Reprocess your last twelve months of European reporting by age band now, so you hold a clean picture of organic reach to under-18s from before the rules land.",
    "Rocket League's qualifier reported hours watched up 46.5 percent on a broadcast that ran 35 minutes longer, while peak concurrent viewers rose 40.5 percent and average concurrent viewers rose 30.9 percent — and the Overwatch World Cup's average was 43 percent of its peak, which is a usable sanity check.  Write average concurrent viewers into your next live sponsorship contract as a reported deliverable alongside peak and the broadcast duration.",
    "At the IAB's first creator sales event the stated blocker on bigger creator budgets was that nobody agrees what a view is or how to price a creator, and one marketer's answer was that creators already function as his production house.  Split your next creator proposal into the cost of making the assets and the cost of the media behind them, and file the first as production rather than asking finance for a new channel.",
    "Michelle Khare generated more than 25 million views on Instagram and TikTok during the shoot, five months before the long-form video came out, and held every frame of the Tom Cruise stunt's airborne footage back until days after the premiere.  Mark exactly one shot on your next owned video as unspendable, and start posting the making-of the week you begin shooting rather than the week you finish.",
]

SHARE = [
    {
        "who": "JARED · CEO",
        "angle": "Car brands cut television spending and the money they kept bought fewer people than it did last year, which is the actual argument for owning a channel.",
        "post": "Car brands cut their US television spending 15.4% in August. The household impressions they bought fell 20.2%.\n\nSpend down 15%. Impressions down 20%. Run the division and the cost per thousand impressions went up about 6% — for advertisers who were actively cutting.\n\nThat is iSpot data, measured rather than surveyed, reported by MediaPost this week.\n\nThe instinct is that a smaller budget buys at a better rate. It went the other way, and the reason is what you cut first. The cheap general schedule goes. The expensive appointment viewing stays, because it is the only thing still working.\n\nNFL preseason took 22% of everything the category spent. Seven of the top ten programmes for automotive reach were sport.\n\nI should say iSpot only measures national linear TV, so some of that money has moved to connected TV rather than left. Nobody has published how much.\n\nThe part that sits badly with me is that this cuts against my own argument as much as for it. If the expensive appointment inventory is the only television that still works, then the cheap end of owned video — the volume stuff, the filler, the things made to fill a content calendar — is competing with exactly the inventory the car brands just walked away from. Being owned does not make it worth watching.",
        "why": "It takes a number everyone will read as a straightforward budget cut and shows it means the opposite of what a cut is supposed to mean, then turns the argument back on the writer's own business rather than landing on the conclusion his job predicts.  Image: a single television aerial against flat orange, one percentage set over it.",
    },
    {
        "who": "JAMES · CREATIVE DIRECTOR",
        "angle": "The same ad was recalled by 41 percent of viewers in one ad break and 26 percent in another, and nothing about the film changed.",
        "post": "The same ad. The same length. The same programme. Remembered by 41% of viewers in one version of the break and 26% in another.\n\nNothing about the film changed. The only difference was how many other ads were standing next to it.\n\nThat is FreeWheel and MediaScience, 436 people, reported this week. Light break was 3 minutes 45 of ads per half hour. Heavy break was 9 minutes. Unaided recall went 41 to 26.\n\nI have sat in a lot of post-mortems on work that underperformed. Almost every one was about the work. The opening was slow. The logo came too late. The line did not land.\n\nSome of it was true. But a fifteen point swing is bigger than anything we argue about in those rooms, and it came out of a field in a media plan nobody fills in.\n\nTwo ads competing for the same memory get in each other's way. There is no grade, no edit, no recast that fixes it. The problem is not on the timeline.\n\nI do not love writing that down. I have built a career on the belief that the work is the thing.\n\nSo the post-mortem I should have been running is one I have never once sat in. What was the ad load on the buy. Did anyone ask before we booked it. I have no idea who I would even ask.",
        "why": "A creative director conceding on the record that the media plan moved recall by more than a third while the creative held constant is the admission the audience does not expect from that seat, and it ends on a question he cannot answer rather than a resolution.  Image: two identical film frames side by side, one crowded by strips of other footage, flat pink ground.",
    },
    {
        "who": "LAWRY · LEAD VIDEO EDITOR",
        "angle": "Holding the best shot out of every piece of promotion is an edit decision that decides whether the release has anything left to reveal.",
        "post": "Michelle Khare recreated a Tom Cruise stunt for a YouTube series and kept every frame of the airborne footage out of the promotion. She posted the pre-flight preparation and nothing else.\n\nThe best shot in the production never appeared in any of the marketing.\n\nThat is an edit decision before it is a marketing one, and it is the one most editors lose. You cut a teaser and you reach for the strongest frame you have, because the teaser needs to work. Everybody in the room nods. It is obviously right.\n\nThen the full video goes up and the best moment in it is something the audience has already watched four times on a phone.\n\nHer sequencing is the opposite. The making-of ran for five months while that footage sat there. Daily cuts from the road, edited on Premiere Mobile between continents, doing over 25 million views on Instagram and TikTok before the long-form existed. All of it built from material the shoot was generating anyway.\n\nSo the cheap footage did the advertising, and the one shot that could not be replaced never left the drive until release week.\n\nWhat I have not worked out is whether it survives a client. Holding your best shot for five months means somebody senior has to sit in a review and approve a teaser that is deliberately not the best thing you have.",
        "why": "It is a decision made in the cut — what you spend and what you hold — shown to determine whether the release has anything left, written from inside the sequence and ending on the real obstacle rather than resolving neatly.  Image: a strip of film frames with one frame blacked out, flat black ground.",
    },
]
