ISSUE = {
    "date_iso":  "2026-09-15",
    "kicker":    "Crux Media // Tuesday 15 September 2026",
    "tagline":   "What brands did on YouTube yesterday, and whether it worked.",
    "pace":      "STEADY",
    "next_drop": "Next drop: Wednesday, 06:30 MT",
}

LEAD = {
    "headline": "REDDIT IS 28.9 PERCENT OF EVERYTHING CHATGPT CITES.  YOUTUBE IS 21.1 PERCENT OF WHAT GOOGLE'S AI CITES.  THE MACHINES ARE NOT ONE AUDIENCE",
    "deck": "A study across 22 US product categories found the assistants do not read the same internet.  Reddit is ChatGPT's single biggest source, at 28.9 percent of every citation it makes.  Google's AI answers lean on video and social instead, with YouTube first at 21.1 percent and Facebook second at 17.  Everyone has spent this year being told to make video so the machines quote you.  Which machine turns out to matter more than the video does.",
    "stamps": [
        ("DIGIDAY · 15 SEP", "https://digiday.com/marketing/in-graphic-detail-inside-the-scramble-to-measure-a-brands-ai-visibility/"),
    ],
    "body": [
        "Digiday published a data round-up this morning on how brands are trying to work out whether an AI assistant mentions them at all.  Buried in it is the finding that should change a video budget this week.  A citation here means the source an assistant points at when it gives somebody an answer.  Semrush, the search analytics firm, studied US data across 22 categories between January and June.  <mark>Reddit is ChatGPT's number one source, at 28.9 percent of every citation it makes.</mark>  Google's AI reaches for video and social instead.  <mark>YouTube is its number one at 21.1 percent and Facebook is second at 17 percent.</mark>",
        "A second study, run differently, points the same way without agreeing on a number.  Scrunch, owned by Sitecore, measured answers the same way across four assistants between May and July.  Google AI Mode, Google AI Overviews, Perplexity and, sometimes, Gemini all cite YouTube regularly.  ChatGPT and Microsoft's Copilot, in Digiday's words, not so much.  Two studies, two date ranges, two methods, so read them as agreeing on direction rather than on a figure.",
        "The size of the swing between assistants is the part that should stop you.  Tinuiti's numbers on one company, Amazon, for a single month.  <mark>In July it accounted for 4 percent of Microsoft Copilot's citations, 0.1 percent of ChatGPT's and zero on Gemini.</mark>  Same brand, same month, three different answers about whether it exists.  What is being measured there is not the quality of anything Amazon made.  It is which pipes each model was plumbed into.",
        "Here is the mechanism, and it is simpler than the measurement industry growing up around it.  An assistant is not searching the whole web and weighing everything it finds.  It reaches for the kind of source its makers decided is trustworthy for that kind of question.  ChatGPT's answer to is this any good is a thread of people arguing about it.  Google's answer to the same question is a video of somebody using it.  Both are defensible.  They are not the same request, and one asset cannot fill both.",
        "So what does this do to a brief.  Every creator brief written this year has carried a line about making the video quotable — say plainly whether the thing is good, and why, and who it is for, so a summariser has a sentence to lift.  That advice still holds and nothing here contradicts it.  What it now needs next to it is a question nobody has been asking, which is which assistant this category's buyer actually opens.  If the answer is ChatGPT, the most valuable thing your campaign produces may not be a film.  It may be a place where real people say, in their own words, the thing your film says.",
        "Underneath all of it is a measurement problem that nobody has solved.  <mark>Of 200 brand and agency ad investment decision-makers surveyed by the IAB, 45 percent named comparing AI-driven customer journeys with traditional ones as their biggest challenge.</mark>  Caroline Giegerich, the IAB's vice president of AI, who led the four-month effort behind the trade body's new framework, describes the problem plainly.  The market is messy.  It is hard to do measurement because you could run what's the best sneakers for under 200 dollars and get different results 100 times.  The same prompt returns different sources run to run, and a model upgrade can move everything overnight while the brand changes nothing.",
    ],
    "numbers": [
        ("28.9%", "Reddit's share of every citation ChatGPT makes, across 22 US categories"),
        ("21.1%", "YouTube's share of Google's AI citations in the same study, Facebook second at 17%"),
        ("45%", "of 200 ad decision-makers say comparing AI and traditional journeys is their hardest measurement problem"),
    ],
    "flagnote": "Three vendors, three methods, no common standard between them.  Semrush sells search visibility tooling, Scrunch is owned by Sitecore and sells the same category of product, and Tinuiti is an agency that sells the service of fixing this — every figure here comes from a company with a commercial interest in brands worrying about it.  Digiday's phrasing of who ran the 22-category study is ambiguous between Adobe and Semrush, and we have attributed it as Digiday published it.  The two citation studies cover different months and measure differently, so the shares are not directly comparable to each other.  And none of this shows that being cited sells anything.",
    "so_what": "The industry has spent the year treating AI answers as one new channel with one new rule, which is make the video quotable.  This says there are at least two channels wearing the same coat and they read different parts of the internet.  Inside Google's answers, video is the most cited kind of source there is.  Inside ChatGPT's, the most cited source is people talking to each other on a forum.  Same question, same brand, completely different evidence being pulled to answer it.",
    "do_this": "Take your ten most valuable buying questions, ask each one in both ChatGPT and Google AI Mode this week, and write down every source each assistant cites for your category.  Then split your next brief in two — keep the video for the Google side, and fund a real presence where people already discuss your category for the ChatGPT side — rather than assuming one asset covers both.",
}

SECTIONS = [
    {
        "id": "ws", "name": "W'S", "page": "pg. 02",
        "note": "what worked, and the exact reason it worked",
        "tint": "blue",
        "items": [
            {
                "title": "Sonos built its comeback campaign around the exact thing that broke, and made it with no agency",
                "hook": "An app update cost at least 100 million dollars of revenue in six months.  Two years later the tagline points straight at it.",
                "stamps": [("ADWEEK · 14 SEP", "https://www.adweek.com/creativity/sonos-new-brand-story-aims-to-win-back-trust-two-years-after-botched-app-update/")],
                "body": [
                    "Sonos launched Love the Sound.  Feel the System yesterday, which Adweek calls the most significant brand repositioning in the company's history.  It runs across the United States and Mexico on outdoor posters, streaming audio, podcasts, print, online video and social, with a heavy media presence in New York.  It is the first work under Colleen DeCourcy, who joined as chief marketing officer in November 2025 from Snap, and before that was chief creative officer and co-president of Wieden and Kennedy.",
                    "The number behind it.  A faulty app update in May 2024 sent the stock down, led to staff cuts, ended Patrick Spence's run as chief executive and <mark>cost the company at least 100 million dollars in revenue in the six months that followed</mark>.  Tom Conrad took over in July 2025.  <mark>Third-quarter revenue is up 9 percent year on year to 375 million dollars</mark>, which is the first real sign of a turn.",
                    "Now the decision that is actually interesting.  The campaign's argument is that Sonos is not a speaker company but an end-to-end sound system.  The system is the thing that broke.  Most brands recovering from a public failure spend the recovery talking about something else entirely.  DeCourcy said the quiet part on the record: the system is what broke down for customers in 2024, and it's the thing we're choosing to put back at the center of how we talk about ourselves.  The proof isn't in the tagline, it's in the software work behind it.",
                    "Two new products carry the idea — Ace Ultra headphones that link into the wider home system, and a compact soundbar called Beam Ultra — and both are shown as parts of a whole rather than as things you buy on their own.  The work drops the specification language the category runs on for collage, visible handmade marks and photography, on the reasoning that an ad in a home should look like something you would hang in one.",
                    "And there is no agency on any of it.  The campaign came from an in-house creative team DeCourcy has been building through this year: heads of global creative Rinee Shah and Kendra Eash, who arrived in June from the sleep brand Hatch, and brand design lead Raquel Scoggin, who came from Snap the same month.  Three senior creative hires in one quarter, and the first campaign is a full repositioning.",
                ],
                "so_what": "Pointing at your own failure only works if you have fixed it, which is why almost nobody does it — the positioning is downstream of engineering rather than of copywriting.  Sonos can say the system is the point because the software work is done, and DeCourcy names that dependency out loud instead of pretending the line did the work.  The transferable part is that the strongest claim a recovering brand owns is usually the thing it is most embarrassed about, and the reason it stays unsaid is that marketing cannot authorise it alone.",
                "do_this": "Write down the single thing your customers complain about most, then ask the team that owns it whether it is genuinely fixed and how you would prove it in thirty seconds of video.  If the answer is yes, build your next campaign on it.  If the answer is no, you have just found the real brief and it belongs to someone other than marketing.",
            },
            {
                "title": "Everyone assumed AI search would eat the brand budget.  The IAB raised its US growth forecast and named AI search as a reason it went up",
                "hook": "Revised from 9.5 percent to 12.3 percent.  State Farm's marketing chief says the alarm is now a factor in the media budget argument, and the argument is for spending more.",
                "stamps": [("DIGIDAY · 15 SEP", "https://digiday.com/media-buying/marketers-are-using-ai-search-concerns-to-argue-for-higher-media-budgets/")],
                "body": [
                    "The assumption all year has been that AI answers remove the click, so the money that used to chase clicks goes away with it.  Digiday reported this morning on the opposite happening.  <mark>The IAB has revised its estimate of US ad spend growth this year from 9.5 percent up to 12.3 percent</mark>, and credits part of that rise to marketers increasing spend specifically to improve how their brand shows up inside AI answers.",
                    "The supporting numbers.  <mark>In an IAB survey, 44 percent of buyers say adapting to changing search habits is their top investment challenge.</mark>  The agency Dept surveyed 2,600 US shoppers and found <mark>61 percent had used an AI assistant for shopping research or a decision in the past three months</mark>.  The most exposed categories are the ones where people take a long time to choose — insurance, cars, running shoes.",
                    "The thing to notice is where the money is actually going, because it is not into tricking the models.  Alyson Griffin, head of marketing at State Farm, on brand work: we value it.  We're not pulling it back.  She also says the alarm about AI search has become a factor in internal debates about media budgets that have been flat for several years.  Oliver Williams, head of digital performance at the agency Mediaplus, says they are telling clients to put more money into awareness work — video whose job is to make people know and like you rather than click on anything — and is blunt that it will not pay back on a short clock.  We're not having conversations with clients around it being a performance channel and it paying off immediately.",
                    "The mechanism is older than any of this and that is what makes it credible.  Research published by Google and Tracksuit in June found that advertisers with high brand awareness also have a high share of search.  Models cite what the internet already says about you.  If more people write about, film and argue about your brand, there is simply more for a model to find and repeat.  So the response to a machine deciding whether to mention you turns out to be the least modern thing in marketing, which is getting more people to talk about you.",
                    "Where it is landing in practice.  State Farm is running college football with Patrick Mahomes.  Mercedes-Benz is running Coco Gauff off the back of the US Open, across television, paid social, display and outdoor.  Hoka is running a New York City Marathon campaign through the autumn.  All three declined to give budget figures.  The IAB projects US connected TV spend up 15.6 percent.",
                ],
                "so_what": "The prediction was that AI answers would kill the click and take the budget with it.  What is happening instead is that buyers cannot yet measure the new thing, so they are funding the old thing that correlates with it.  That is real money for anyone who makes brand video, and it is also a fragile reason to be funded — the moment somebody can measure AI visibility directly, the argument moves to whoever can show that number.  Take the money, and get your own baseline running before the justification changes underneath you.",
                "do_this": "Put one slide in your next budget request showing your brand's share of mentions in AI answers next to your share of search, tracked monthly from this week, so that when the measurement standards land you already hold a baseline instead of starting the argument from zero.",
            },
        ],
    },
    {
        "id": "ls", "name": "L'S", "page": "pg. 03",
        "note": "what broke, and the failure mode underneath it",
        "tint": "pink",
        "items": [
            {
                "title": "Wrong owner: Sydney Sweeney owns part of the company whose ad she is being blamed for, and it made no difference at all",
                "hook": "She is an equity partner in Novig rather than hired talent, and says she was in the creative conversations from the start.  The backlash landed on her exactly as it has landed on people who had no say whatsoever.",
                "stamps": [
                    ("ADWEEK · 14 SEP", "https://www.adweek.com/brand-marketing/one-year-post-american-eagle-scandal-sydney-sweeney-sparks-ire-by-going-naked-for-novig/"),
                    ("ADWEEK · 15 SEP", "https://www.adweek.com/brand-marketing/four-female-endorsers-left-holding-the-bag-for-ads-gone-wrong/"),
                ],
                "body": [
                    "Novig, a sports prediction app, launched Just Sports, its first national brand campaign, with Sydney Sweeney appearing nude.  The backlash arrived within hours.  Ariane Titmus, the Australian Olympic gold medallist swimmer, on Instagram: I can't describe how infuriated I feel when I watch this, calling the campaign a kick in the face to every woman who has dedicated her life to perfecting her craft.",
                    "The detail almost everyone skipped past.  <mark>Sweeney is a partner and equity stakeholder in Novig, not a hired face.</mark>  She told Complex that she had been part of the creative conversations from the very beginning.  So this is the rare case where the person on camera genuinely helped decide what the camera did, and the public response is indistinguishable from the cases where she decided nothing.",
                    "Adweek ran the comparison piece the following morning and that is the useful half of the story.  Mary J. Blige took the blame for a 2012 Burger King spot that Burger King later said was not the final cut — everybody dropped the ball, and I'm holding everything, she has said since.  Kendall Jenner took the blame for Pepsi's 2017 ad after Pepsi itself said it had missed the mark.  Brooke Shields, at fifteen, took the blame for a line written by Calvin Klein and the photographer Richard Avedon.  Danica Patrick took the blame for a GoDaddy concept the company's founder has admitted was his.",
                    "The mechanism is that authorship is invisible.  A viewer cannot see who pitched the idea, who approved it, which safer version was killed or who killed it.  The only person visible is the one on screen, so an audience assigns the idea to the face by default and there is no mechanism by which it could do anything else.  Adweek's own framing: when a campaign starring a female endorser tanks with the public, it's often the women who get blamed, whether or not they played a role in creating the ads.",
                    "The context that sharpens it here rather than softening it.  One estimate cited in the piece puts roughly 70 percent of sports bettors as men.  The complaint being made is not really about nudity.  It is that a sports brand chose a body over an athlete in a year when women's sport has more to show than it has ever had, and that reads as a statement about what sport is for.  Sweeney is the only person standing in the frame where that decision can be seen.",
                ],
                "so_what": "If you cast a face, that face absorbs your reputational risk whether or not they had any say, and giving them a say transfers none of it back.  Sweeney had equity and creative input and still carries the whole thing alone, because none of that is visible in a thirty second film and no amount of contract language makes it visible.  So the question to settle before you cast is not whether the talent is comfortable with the idea.  It is whether your brand is willing to stand next to them in public and say out loud that this was our decision.",
                "do_this": "Before your next talent-led campaign ships, agree in writing who speaks publicly if it goes wrong, and get a brand statement drafted in advance that names the brand as the author of the idea.  Put it in the same approval pack as the creative, so it exists before you need it rather than being written in a panic at nine in the evening.",
            },
            {
                "title": "Wrong economics: a company that did 615 million dollars last quarter has budgeted fifteen grants of two thousand dollars for its first creator programme",
                "hook": "Thirty thousand dollars in year one, invitation only, and the creators recruit the next ones.  Judge it as media and it will be dead by spring.",
                "stamps": [("MODERN RETAIL · 15 SEP", "https://www.modernretail.co/marketing/carters-unveils-brand-refresh-as-it-courts-more-gen-z-and-millennial-parents/")],
                "body": [
                    "Carter's is 161 years old and is running its first major brand refresh since 2000 — a new brand commitment, a new logo and identity, and a commercial called Watch Them Glow that starts rolling out across streaming video networks today.  <mark>Net sales grew 5 percent to 615 million dollars in the second quarter of 2026</mark>, the third consecutive quarter of growth, after the company said last October it would close 150 stores and cut 300 jobs over three years, partly because of tariffs.",
                    "Attached to the refresh is Light Makers, which chief marketing officer Sarah Crockett says is the first dedicated creator programme the company has run.  Carter's hand-picks the first group; there is no open application.  <mark>The grants are 2,000 dollars each, up to fifteen of them in the first year</mark>, with the first expected some time this holiday season.  As the programme grows, creators already inside it can invite other creators to join.",
                    "Do the arithmetic, because nobody in the coverage does.  Fifteen grants of two thousand dollars is <mark>thirty thousand dollars across a full year</mark>, at a company whose most recent quarter alone was 615 million in net sales.  As a media budget that is a rounding error on a rounding error.  Two thousand dollars does not buy a piece of video that can sit anywhere near a national streaming commercial, and everyone involved knows it.",
                    "Which is the point, and also the risk.  This is not a media buy and it is not pretending to be one.  The grant buys a creator's willingness to be publicly associated with the brand and, far more valuably, their willingness to bring in the next one.  Invitation-only membership with a small cash marker attached is how you build a roster.  It is not how you buy reach, and the two things are scored by completely different numbers.",
                    "So the failure mode is predictable and it is not about the creators.  A programme designed to grow a roster, reviewed after two quarters on views per dollar, gets closed.  The numbers that would actually tell you whether Light Makers is working are how many creators are in it six months from now, how many of those arrived through an invitation rather than through Carter's, and how much usable footage the brand now owns that it did not have to commission.",
                ],
                "so_what": "A creator programme with a thirty thousand dollar budget is not trying to buy attention and should not be scored as though it were.  What Carter's is buying is a list of people who have agreed to be associated with it and a mechanism by which those people recruit more of them, which is enormously cheaper than signing a fresh roster every year.  The danger is entirely internal: the finance review sees a creator line item, asks it for reach, gets a terrible answer, and kills something that was never built to produce one.",
                "do_this": "If you are standing up a seed creator programme, write its success metric down before the first payment leaves the building — roster size, the share of members who joined by invitation, and usable content produced per quarter — and get finance to sign that sheet rather than the media plan.",
            },
        ],
    },
    {
        "id": "moves", "name": "MOVES", "page": "pg. 04",
        "note": "platform, policy and legal changes that alter what you can make and buy",
        "items": [
            {
                "title": "YouTube, Netflix and Amazon have opened a lobbying office in Washington to defend exclusive sports rights",
                "hook": "Founding members YouTube, Netflix, Amazon and TechNet.  The bills they are worried about would force leagues to put local games in one place.",
                "stamps": [("TUBEFILTER · 14 SEP", "https://www.tubefilter.com/2026/09/14/youtube-netflix-amazon-saca-sports-rights-lobbying/")],
                "body": [
                    "The Streaming Access and Choice Alliance launched yesterday, founded by YouTube, Netflix, Amazon and TechNet, the bipartisan network of technology executives.  Its stated purpose is promoting high-quality and high-value entertainment experiences for consumers.  Its practical purpose is to argue in Washington that streaming services should keep being allowed to sign exclusive sports deals.",
                    "What is on the table.  <mark>YouTube has NFL Sunday Ticket locked up for seven years.  Netflix has WWE Raw for five billion dollars over ten years.  Amazon has an eleven-year NBA agreement.</mark>  All three are expected to bid for the 2030 and 2034 World Cups.",
                    "What prompted it.  Senator Tammy Baldwin of Wisconsin introduced a bill in April to stop leagues blacking out games and to make a team's games available to local fans in one place.  Her office's number is that <mark>a Wisconsin fan would need to spend over 1,500 dollars a season</mark> across services to watch every Packers, Brewers and Bucks game, and that more than 400,000 Packers fans across thirteen Wisconsin counties are assigned to an out-of-state television market.  Two months later the House Judiciary Committee began probing the Sports Broadcasting Act of 1961 — the law that lets leagues sell their media rights collectively without falling foul of competition law — with a committee report calling it a special-interest antitrust exemption gone awry.",
                    "Mike Ward, TechNet's senior vice president of federal policy, on why the group exists: the industry and its customers deserve a dedicated voice in Washington, D.C., advocating for policies that enable innovation and address the needs of today's consumers.",
                ],
                "so_what": "The only reason live sport is worth ten figures to a streaming service is that one of them has it and the others do not.  If a law forces local games into a single place, exclusivity stops being worth paying for, and the deals that currently set the price of every live sponsorship slot in America get repriced downwards.  This alliance is the industry saying out loud that it expects that fight and intends to win it.",
                "do_this": "If your brand has multi-year sponsorship money committed to a league or to a streaming rights holder, ask your legal team this month what happens to your inventory if a blackout or local-availability rule passes, and get the answer in writing before the next renewal lands on your desk.",
            },
            {
                "title": "Someone is selling a list of 40,000 Twitch streamers with their email addresses, and your outreach team is the thing it is aimed at",
                "hook": "A 501-record sample checked by Cybernews contained emails that were not public.  Separately, an extension with 31,000 users was forwarding live account tokens.",
                "stamps": [("DEXERTO · 14 SEP", "https://www.dexerto.com/twitch/dark-web-hacker-claims-to-have-stolen-40000-twitch-streamers-personal-info-3409031/")],
                "body": [
                    "A listing appeared on an illicit marketplace on 9 September claiming records for <mark>roughly 40,000 Twitch streamers</mark> — usernames, profile links, email addresses, legal names, follower counts and verification status.  <mark>Cybernews reviewed a sample of 501 records</mark> supplied as evidence and found the fields real.",
                    "Researchers believe it is a scrape rather than a hack.  From what I see, this indeed looks like a data scrape, not a breach, one told Cybernews.  The complication is that some email addresses in the sample were not publicly visible on the creators' profiles, which raises the possibility that Twitch's own interface was queried using a token it should not have had.  Twitch has not confirmed a breach.",
                    "Separately, researchers at Socket found that a browser extension called Twitch Enhanced Viewer, with <mark>about 31,000 users</mark>, was forwarding live account tokens to servers its operator controlled — tokens that let somebody act as that account with no password and no second factor.  Twitch confirmed on Monday that it has revoked potentially exposed tokens and told people to remove the extension.  Nothing links the two incidents.",
                    "Now the reason a brand should care, which is not the obvious one.  A list pairing a streamer's legal name, working email address and exact follower count is close to perfect raw material for a fake sponsorship offer.  Cybernews says it plainly: aggregating creator information into one place makes it easier to profile these people and craft social engineering scams.  The version of that scam which works best is the one that arrives in a real brand's name.",
                ],
                "so_what": "Every creator outreach programme in the industry runs on cold email from addresses nobody verifies, which makes it trivially impersonable, and there is now a fresh list circulating that makes the impersonation convincing.  The cost of getting this wrong is not that you lose a deal.  It is that a streamer gets defrauded by somebody using your brand's name, and the story that follows has your logo in the headline rather than the scammer's.",
                "do_this": "Publish one page on your own domain this week listing the exact email domains your brand uses to approach creators and the name of any agency that contacts them on your behalf, then link it in every outreach message so anyone can check you are real before they click a thing.",
            },
            {
                "title": "YouTube premiered five creator projects at Venice and Toronto on the same weekend, for the first time",
                "hook": "A feature documentary, two episodes of a talk show, two international docs and a Cannes short.  Nobody disclosed who paid for any of it.",
                "stamps": [("YOUTUBE BLOG · 14 SEP", "https://blog.youtube/news-and-events/youtube-creators-venice-toronto-film-festivals/")],
                "body": [
                    "The slate.  Mark Vins of Brave Wilderness premiered Reef to Ridge, a feature-length documentary shot in the Galapagos, on opening day at Toronto, alongside two new episodes of Ziwe's You'd Be an Iconic Guest.  At Venice: The Last Day of Ramadan from the Italian duo theShow, The Mad Honey of the Himalayas from Lati Umani about Nepal's Gurung honey hunters, and City of Owls, a Cannes-selected short by Zhenia Kazankina presented by Rai Cinema.",
                    "It is the first time YouTube has debuted a slate at both festivals simultaneously.  The Vins and Ziwe shows come to YouTube itself later this year.  Sean Downey, president of Americas and global partners at Google, in the announcement: YouTube is where this generation of entertainment is being built.  Our creators are redefining storytelling across every screen.",
                    "No budget or financing detail appears anywhere in the post, and it does not say whether YouTube funded the productions or the creators did.  That is the single number that would tell you what this actually is — a distribution signal or a subsidy — and its absence is the most interesting thing in the announcement.",
                ],
                "so_what": "Creator work has been stuck fighting for social budget because of what it gets called rather than what it costs or how long it runs.  A premiere at Venice changes the name of the thing, and the name decides which budget line pays for it and which executive has to sign.  That is not cosmetic.  It is the difference between a brand funding a ninety-minute creator film out of branded entertainment money and never being allowed to consider it at all.",
                "do_this": "Take your strongest creator relationship and price a single long-form documentary with them this quarter against your branded entertainment budget rather than your social budget, then find out whether the approval path is genuinely shorter.  If it is, you have just discovered your creator work was mispriced by its filename.",
            },
            {
                "title": "Microsoft will reject your ad for stripping the metadata that says it was made with AI",
                "hook": "Keep the watermark, keep the provenance record, and put the disclosure next to the thing it discloses.",
                "stamps": [("SEARCH ENGINE LAND · 14 SEP", "https://searchengineland.com/microsoft-advertising-sets-rules-for-ai-generated-ads-488429")],
                "flagnote": "Single-sourced.  We could not locate Microsoft's own announcement post, only Search Engine Land's write-up of Microsoft's advertising policy documents, and no effective date or enforcement timeline appears in the coverage.  Treat the wording as reported policy rather than as a dated announcement.",
                "body": [
                    "Microsoft Advertising has published rules covering AI-generated ad content.  Advertisers must comply with applicable laws wherever their campaigns run, including requirements around disclosures and permissions, and must preserve watermarks, metadata and other provenance information identifying how AI-generated content was created.  Where a disclosure is required, it has to be clear and placed close to the relevant content.",
                    "The rejection list.  Ads can be refused for prohibited deepfakes, for impersonating people or organisations, for using someone's likeness or voice without the required authorisation, for omitting required disclosures, or for interfering with machine-readable provenance information.",
                    "That last one is the new part and it is a production problem rather than a legal one.  Provenance data is a small invisible record attached to a file saying what made it and how.  Plenty of ordinary editing, transcoding and export steps strip that record out without warning anybody.  So an ad can be entirely legal, correctly disclosed, and still rejected because somebody re-encoded it on the way to delivery.",
                ],
                "so_what": "The compliance risk in AI-assisted advertising has quietly moved from what you say to what your export settings do.  A disclosure you wrote correctly can still fail because the file arrived without the record that proves the claim, and nobody in the chain will have done anything wrong or even known it happened.  Expect this to become a recurring class of rejection until the editing tools carry provenance through by default.",
                "do_this": "Run one recent AI-assisted ad file through a provenance checker before and after your normal export, identify exactly which step strips the data, and add a delivery check to your specification sheet so nothing leaves the building stripped again.",
            },
        ],
    },
    {
        "id": "onstream", "name": "ON STREAM", "page": "pg. 05",
        "note": "the live numbers, and what they are worth to a sponsor",
        "items": [
            {
                "title": "A two-day convention with 1,400 channels drew half the live audience of a pre-recorded video from the day before",
                "hook": "BlizzCon peaked at 1.76 million across everything.  Nintendo's Direct, twenty-four hours earlier, peaked above 3.7 million with more channels carrying it.",
                "open": True,
                "stamps": [
                    ("STREAMS CHARTS · 14 SEP", "https://streamscharts.com/news/blizzcon-2026-viewership-stats"),
                    ("STREAMS CHARTS · 11 SEP", "https://streamscharts.com/news/nintendo-direct-sep-2026-viewership"),
                ],
                "numbers": [
                    ("1.76M", "BlizzCon peak concurrent viewers across 1,400-plus channels, 12-13 September"),
                    ("3.7M", "Nintendo Direct peak concurrent viewers on 11 September, its fourth biggest ever"),
                    ("8.8M", "hours watched at BlizzCon over two days, with no average concurrents published"),
                ],
                "body": [
                    "BlizzCon ran in Anaheim on 12 and 13 September.  Streams Charts puts it at <mark>more than 1.76 million peak viewers across live coverage channels and over 8.8 million hours watched</mark>, with more than 1,400 unique channels covering it.  World of Warcraft became Twitch's most-watched game by hours over the weekend, with increases of more than 620 percent in hours watched and average viewers after the Diablo V and open-world StarCraft reveals.  Overwatch entered the top five.",
                    "The comparison that matters happened the day before it started.  <mark>Nintendo's Direct on 11 September peaked at more than 3.7 million</mark>, its fourth most-watched ever, with <mark>over 2,200 unique channels streaming it</mark>.  So the event with more channels carrying it was the pre-recorded video, and it took more than double the peak of the physical convention.",
                    "Define the two numbers, because they do completely different jobs and get quoted interchangeably.  Peak concurrent viewers is the most people watching at the same moment, which is demand.  Hours watched is everybody's viewing added together, and it rises whenever a thing runs longer or more channels carry it.  BlizzCon ran across two days.  A Direct runs well under an hour.  Of course the convention wins on hours.  It lost badly on the number a sponsor is actually buying.",
                    "Now the co-stream question, which is where a lot of sponsorship money currently goes.  <mark>BlizzCon's biggest individual channel was zackrawrr at 144,000 peak across almost twelve hours of airtime, about 8 percent of the event's peak.</mark>  <mark>Nintendo's biggest community caster, Maximilian Dood, hit a combined peak of more than 46,000 across two channels, about 1.2 percent of the Direct's peak.</mark>  Both figures are our own arithmetic against the published totals.  In both cases the crowd was at the source and not at the commentary.",
                    "Neither event published average concurrent viewers, and for a two-day convention that is the number that would tell you the most.  A 1.76 million peak spread over two days says nothing whatsoever about what the ordinary hour looked like, and the ordinary hour is what a logo on a stream is being sold against.  Ask for it and treat a refusal as an answer.",
                    "For scale: the biggest Nintendo Direct ever, the Switch 2 showcase on 2 April 2025, peaked at 6.3 million.  The Zelda 40th Anniversary Direct, two days before this one, peaked at 2.24 million and missed Nintendo's own all-time top ten.  Nintendo is running a schedule where a middling entry still beats a flagship convention.",
                ],
                "flagnote": "All figures are Streams Charts.  The percentage shares of peak attributed to individual co-streamers are our own calculation against the published event totals, and they compare a single channel's peak with the whole event's peak, which need not have occurred at the same moment.  Neither event published average concurrent viewers or total airtime, so no like-for-like duration comparison is possible.",
                "so_what": "Channel count is not audience.  Nintendo had roughly 800 more channels carrying it than BlizzCon did and took more than twice the peak, because what people cleared time for was the announcement itself rather than anybody's coverage of it.  So if you are buying a live sponsorship, the co-streamer roster is breadth and the official broadcast is the crowd — and at both of these events the single biggest co-streamer was somewhere between one and eight percent of the moment.",
                "do_this": "On your next live sponsorship proposal, demand peak concurrents, average concurrents, hours watched and total airtime in the same table, and price the official broadcast separately from the co-stream network instead of buying them as one undifferentiated audience.",
            },
        ],
    },
    {
        "id": "watch", "name": "ONE TO WATCH", "page": "pg. 06",
        "note": "one creator with momentum, and the client who should be calling",
        "items": [
            {
                "title": "TheOutdoorGearReview has 768,000 subscribers, 234 million lifetime views and has never taken a sponsor in fourteen years",
                "hook": "His best video of the quarter did 411,273 views on a bivvy tent from a brand nobody has heard of.  The premium names he reviews land below his median.",
                "open": True,
                "stamps": [("YOUTUBE · @THEOUTDOORGEARREVIEW", "https://www.youtube.com/@TheOutdoorGearReview")],
                "body": [
                    "Luke runs TheOutdoorGearReview, a camping and outdoor gear channel that has been publishing since December 2012.  It now carries <mark>2,298 videos, 768,000 subscribers as YouTube displays it, and 234,125,773 lifetime views</mark>.  He posts nearly every day.  Across his last fifteen uploads the median is <mark>105,000 views</mark>.  On 8 September he published I Have NEVER Seen This Before - EVER! - OneWind Bivy Tent and it is at <mark>411,273 views, roughly four times his own median</mark>.",
                    "Read the description on that video before you plan anything.  He takes Amazon commission, has a Patreon and a membership, and writes: TOGR is 100% Agenda Free.  This channel is Agenda Free and is fully supported by the viewers.  No sponsored placements, no discount codes, no brand landing pages, on any description we were able to retrieve.",
                    "Now the thing a brand should stare at.  We sorted his last four months of uploads by views and looked at which brand is the subject of each one.  The top twelve are led by <mark>OneWind at 411,273 and HexoTool at about 156,000</mark>, with most of the rest either unbranded gear or storm and survival films with no product in them at all.  The established names land nowhere close: <mark>Nemo around 29,000, Therm-a-Rest around 24,000, Osprey around 33,000, Sierra Designs around 38,000</mark>.  Every one of those sits below his median.",
                    "And the strongest category on the channel is not gear at all.  Across his last thirty uploads, the storm and survival films with no product as the subject have a <mark>median around 144,500 views</mark>.  Plain specification reviews sit at a <mark>median around 52,000</mark>.  The novelty-hook reviews land between them at about 73,000.  His audience is turning up for the field and the weather, not for the spec sheet.",
                    "Which makes the brief obvious and slightly uncomfortable.  A premium outdoor brand buying a review on this channel would be buying the worst-performing format on it.  A premium outdoor brand funding a bad-weather field film in which its tent is simply the tent he happens to be sleeping in would be buying the best one.  Nobody has done either, because in fourteen years he has not sold anything to anybody.",
                ],
                "watch": {
                    "label": "TOP VIDEO, LAST 3 MONTHS",
                    "title": "I Have NEVER Seen This Before - EVER! - OneWind Bivy Tent",
                    "url": "https://www.youtube.com/watch?v=GUP_zX8gxAk",
                    "meta": "411,273 views · published 8 September 2026 · 16m 36s",
                    "note": "Sixteen minutes on a one-person bivvy tent from OneWind, a brand that does not sponsor him, filmed in the field and carrying the channel's standard no-sponsor line in the description.",
                },
                "flagnote": "The medians, the format split and the brand-by-brand comparison are our own calculations across his last thirty to sixty uploads, read off YouTube on 15 September, not published statistics, and the view counts will have moved since.  The subscriber figure is the rounded number YouTube displays rather than an exact count.  We confirmed the no-sponsor line on the two descriptions we could retrieve before YouTube blocked further requests, including the featured video, so read it as strongly indicated rather than exhaustively checked.  Relative upload dates on the channel page round down, so the period boundaries are approximate.",
                "so_what": "This is a channel with a quarter of a billion lifetime views that has never run a paid placement, which means every brand mention on it is unbought and therefore worth something a bought one is not.  The catch for anyone who wants in is that his audience has already voted on formats, and the format brands habitually buy — a product review with the manufacturer's name on the front — is the one that performs worst here by a wide margin.  The expensive part of that lesson is that it is almost certainly not specific to him.",
                "do_this": "If you sell tents, sleep systems, packs or camp stoves, send TheOutdoorGearReview your hardest-to-believe product this week with no brief, no conditions and no request for coverage, and put it through the budget as product seeding rather than as media.  On a channel that has refused sponsorship for fourteen years the only thing available to buy is a chance at being the thing he found interesting.",
            },
        ],
    },
    {
        "id": "money", "name": "THE MONEY", "page": "pg. 07",
        "note": "the numbers that change what a thing is worth buying",
        "items": [
            {
                "title": "The company that held creators' affiliate money ran up unpaid invoices of as much as 900,000 dollars, then quietly sold the business",
                "hook": "Overdue payments stretching back eight months, one publisher still owed around 60,000 dollars, and the buyer's first email to creators was an apology about payments.",
                "open": True,
                "stamps": [
                    ("ADWEEK · 14 SEP", "https://www.adweek.com/dealroom/howl-sells-creator-business-taboola-connexity/"),
                    ("GLOSSY · 14 SEP", "https://www.glossy.co/fashion/coreli-ltk-integration-creator-commerce/"),
                ],
                "body": [
                    "Howl, which connects creators and publishers to retailers and earns by taking a percentage of the affiliate deals it facilitates, sold its creator division to Connexity — a commerce platform owned by Taboola — in August.  Both companies confirmed the sale and declined to give financial specifics.  A source told Adweek the price was not large enough to have required disclosure in Taboola's quarterly earnings.",
                    "The history is the story.  In 2023 Howl fell behind on payments to its publishing partners, racking up millions of dollars in delinquent invoices.  Adweek reported at the time that <mark>the overdue payments stretched back up to eight months and ranged from 20,000 dollars to 900,000</mark>.  Three publishers told Adweek this week that it is happening again, two of them currently owed.  <mark>The head of affiliate revenue at one major publisher says Howl still owes them around 60,000 dollars.</mark>  Another executive: they apparently still owed me a bit of money, which I finally got paid, over a year later.",
                    "Connexity has since paid off the balances Howl owed to its creators, and the August email it sent to the creators it acquired opened with the line: we know payments have been a pain point, and fixing that is priority number one.  Its own creator arm, ShopYourLikes, is now approaching the brands Howl worked with to win that business directly.",
                    "Here is the mechanism, and it is not a marketing mechanism at all.  An affiliate platform sits between the retailer's money and the creator's bank account.  The retailer pays on its own schedule, the platform pays the creator on another, and the gap between those two dates is working capital the platform gets to use.  That gap is the business.  When it breaks, nothing has underperformed — the videos worked, the links converted, the brand got its sales — and the creator still does not get paid, with your brand's name on the deal they signed.",
                    "Which is the context for a very small number in the same week's news.  Glossy reported that Coreli, a subscription page builder for creators, now has <mark>561 paying subscribers at 29 dollars a month or 290 a year, roughly 16,000 dollars in monthly recurring revenue and about 190,000 a year</mark>, having added an integration that pulls a creator's LTK and ShopMy storefronts onto a single page they control.  It takes no cut of affiliate revenue at all.  Five hundred and sixty-one creators are paying a subscription specifically so the page their audience lands on is not owned by a platform that might have a bad quarter.",
                ],
                "so_what": "Everybody prices creator deals on reach and conversion and nobody prices them on whether the intermediary can make payroll.  Howl's failure was never a performance failure — the campaigns worked and the money existed, it simply sat in the wrong account for eight months at a time.  The creators and publishers carrying that risk did not know they had agreed to carry it, and the brand whose products were being sold is the name attached to the whole arrangement in public.",
                "do_this": "Pull every creator and affiliate contract you have running and write down, for each one, who holds the money between the sale and the payout and for how many days.  Then ask your finance team which of those intermediaries they would extend credit to, and move the uncomfortable ones to paying the creator directly.",
            },
            {
                "title": "EA has bundled three games into a single ad buy, and the barrier it is removing is paperwork rather than performance",
                "hook": "Four months into running advertising as a real business, it is selling EA Sports FC 27, College Football 27 and Skate as one purchase for the holidays.",
                "stamps": [("DIGIDAY · 15 SEP", "https://digiday.com/marketing/electronic-arts-is-bundling-its-games-to-make-a-bigger-pitch-to-advertisers/")],
                "flagnote": "The 25 percent holiday engagement lift is EA's own internal data, not independently measured or verified.  No pricing, advertiser count or revenue figure has been disclosed for the four months since EA launched advertising as a standalone business.",
                "body": [
                    "Digiday reported this morning that EA is rolling out Moments of Play, a single-buy package bundling ad units across its games with brand integration opportunities.  It starts with the 2026 holiday period and spans <mark>EA Sports FC 27, EA Sports College Football 27 and Skate</mark>, with plans to extend it to other big moments across the year including major sports events and game launches.  No pricing was disclosed.  This lands four months after EA began selling advertising as a real business unit rather than a side project.",
                    "The number behind the timing is EA's own.  <mark>Engagement across its games rises by an average of 25 percent during the holiday period</mark>, according to the publisher's internal data, which is why it wants to sell against those weeks specifically.  That is a first-party figure with no outside verification and it is doing a great deal of work in the pitch.",
                    "The mechanism is considerably better than the number, and it comes from Nikhil Lai, principal analyst for performance marketing at Forrester.  Most advertisers do not plan around individual game titles.  They plan around audiences, outcomes and operational efficiency.  The reality is that a chief marketing officer is more likely to ask for sports and gaming audiences at scale than for Madden inventory.  And on what has actually been holding the category back: the biggest barrier to gaming advertising hasn't been audience demand, but execution.  Brands may want to reach gaming audiences, but fragmented inventory, custom integrations, inconsistent measurement and difficult media-planning workflows can make those audiences harder to buy at scale.",
                    "Read that twice, because it is the useful part and it has nothing to do with games.  A media category can be held back for years by how hard it is to purchase rather than by whether it works.  What EA has shipped is not a new ad format.  It is an order form.  Alex Dao, EA's vice president of advertising and sponsorships: Moments is definitely going to be a part of our offerings going forward.",
                    "And it is competing for exactly your money.  EA already sells machine-bought placements across its mobile games and is now extending those capabilities to console and PC, where Dao says interest is strongest — the premium audience on PlayStation 5 and Xbox.  That is the same argument YouTube and connected TV are making, aimed at the same budget, inside the same ten weeks.",
                ],
                "so_what": "What unlocked a category here was not a creative breakthrough or a measurement breakthrough.  It was one purchase order instead of three separate negotiations.  That should make you look hard at whatever your team has written off as not worth the effort — a roster of small creators, a regional buy, a set of niche channels — and ask whether the problem was ever the inventory or just the admin wrapped around it.  Friction is a performance number and nobody reports it.",
                "do_this": "Take the media idea your team has quietly abandoned twice because it was too fiddly to execute, spend an hour this week writing down what a single simplified purchase would have to look like for it to be worth doing, and send that description to the seller.  They may well build it.",
            },
        ],
    },
    {
        "id": "format", "name": "FORMAT LAB", "page": "pg. 08",
        "note": "the format decision underneath the numbers",
        "items": [
            {
                "title": "Dr Squatch has run three collaborations in four weeks, and the scarcity is really a publishing schedule",
                "hook": "Five thousand units of the Megan Fox bar, 1,500 of them sold by draw, winners told four days later.  The product is the reason to make the video.",
                "open": True,
                "stamps": [("DEXERTO · 14 SEP", "https://www.dexerto.com/entertainment/dr-squatch-reveals-megan-fox-soap-collab-designed-to-drive-people-feral-3409073/")],
                "flagnote": "No sales, engagement or view figures have been published for any of the three collaborations, so the cadence is observable and the results are not.  Unit counts, prices and dates are as reported by Dexerto from Dr Squatch's own announcement.",
                "body": [
                    "Dr Squatch announced Feral Fox with Megan Fox yesterday.  <mark>Five thousand products in total.</mark>  US customers enter a drawing from 14 September for the chance to buy one of <mark>1,500 soap and deodorant bundles</mark>, with winners notified on 18 September.  Limited additional stock goes through Target and Walmart online plus international markets.",
                    "It is the third unusual collaboration in roughly four weeks.  Blue Ribbon Breeze, an <mark>eight dollar bar</mark> made with actual Pabst Blue Ribbon lager, launched less than a month before.  A Tajin collaboration called Mango Tango came earlier in August.  Fox had already appeared for the brand as Professor Fox in an earlier campaign, so the relationship was built before the drop needed it.",
                    "Look hard at the drawing mechanic, because that is the format decision and everything else is packaging.  You are not entering to win a product.  You are entering for the right to buy one.  That turns a purchase into a two-stage event with a gap in the middle — entry opens, four days pass, winners are told.  Four days is a content window.  John Ludeke, Dr Squatch's chief brand officer: only 5,000 are available, so the chase is officially on.",
                    "Here is what that structure actually solves, and it is the problem most brand channels have.  Brands do not fail to make video because they lack budget or crew.  They fail because they have nothing new to say, so they make one big thing a quarter and go quiet either side of it.  Manufacturing a drop every three weeks manufactures a reason to publish every three weeks.  The scarcity is not primarily a pricing tactic.  It is a commissioning tactic.",
                    "The honest caveat is that none of the previous drops have published results.  We do not know whether Blue Ribbon Breeze sold out, or what any of this did to the base business, and a brand can run a beautiful cadence into an empty room.  What is observable is the rhythm, and the rhythm is a choice any brand can copy without a celebrity attached to it.",
                ],
                "so_what": "The hardest thing about running a brand channel is not making the video, it is having a reason to make one this week.  Dr Squatch has solved that by giving itself something new to announce roughly every three weeks, and the two-stage draw stretches each announcement across a week of content rather than a single day of it.  You can copy the structure without the celebrity, because the value sits in the calendar rather than in the collaborator.",
                "do_this": "Map your next quarter's video calendar backwards from three things you could make scarce — a limited run, a single-day restock, a numbered edition — and put an entry window and a separate reveal date between each one, so every drop gives you two videos instead of one.",
            },
        ],
    },
]

FORECAST = [
    {
        "confidence": "LIKELY",
        "window": "by 31 March 2027",
        "headline": "AI visibility becomes a named line in the creator brief, split by assistant",
        "body": "The Semrush and Scrunch numbers hand a buyer arithmetic they did not previously have, which is that video is the most cited kind of source inside Google's answers while forums lead inside ChatGPT's.  Once that sits in a deck, a brief that says make the video quotable acquires a second line asking which assistant this buyer opens, and campaigns start commissioning a forum presence and a film as one package rather than treating the second as a freebie.  The IAB framework landing is what turns an argument into a field on a form, and forms are how this industry makes anything permanent.",
        "do": "Add one line to your next creator brief naming which assistant this campaign's buyer actually uses, and commission against that answer rather than against both.",
    },
    {
        "confidence": "WATCH CLOSELY",
        "window": "by 31 December 2026",
        "headline": "A platform publishes its own citation data to correct the measurement vendors",
        "body": "Three vendors currently disagree in public about where assistants get their answers, and every one of them sells the fix for the problem they are describing.  Platforms hold far better data about what gets cited from their own surfaces and have historically published it at precisely the moment an outside number starts shaping how buyers allocate budget.  Google has the strongest incentive of anyone here, because the current numbers flatter it — YouTube first at 21.1 percent — and confirming a flattering number is the cheapest publication in the world.",
        "do": "When a platform publishes citation data, check whether it counts links shown to a user or sources the model consulted, because those are different numbers and only one of them is about your video.",
    },
    {
        "confidence": "LIKELY",
        "window": "by 30 June 2027",
        "headline": "A named brand's creator outreach gets impersonated and a creator loses money",
        "body": "A list pairing 40,000 streamers' legal names, working emails and exact follower counts is circulating now, and the highest-value use of it is a fake sponsorship offer.  The economics favour the scammer completely: sending mail in a real brand's name costs nothing, creators are conditioned to receive cold offers from strangers, and the first party to find out is usually the brand, from the creator, after the money has gone.  The tell that it has happened will be a brand publishing a verification page nobody asked it for.",
        "do": "Publish the email domains your brand uses to contact creators on your own site, and link that page in every outreach message you send from now on.",
    },
    {
        "confidence": "LONG SHOT",
        "window": "by 30 September 2027",
        "headline": "A major outdoor or tools brand funds a creator's field film and takes no title credit",
        "body": "TheOutdoorGearReview's numbers say his best-performing work has no product as its subject and his weakest has a manufacturer's name on the front, and the same shape has now shown up on several channels in this brief over the past month.  The commission that follows logically is a brand paying for a film it is not the subject of, with credit only in the description.  It stays a long shot because nobody in a marketing structure gets signed off for a video that does not mention the product, and the measurement team cannot attribute it to anything.  The first company to do it will have found a way to file it as a production deal.",
        "do": "Price one film in your category where your product appears but is not the subject, and find out which person in your own organisation refuses to approve it.",
    },
]

TLDR = [
    "Reddit is 28.9 percent of every citation ChatGPT makes, while YouTube is 21.1 percent of Google's AI citations and Facebook is second at 17, across a 22-category US study.  Ask your ten most valuable buying questions in both ChatGPT and Google AI Mode this week, log which sources each cites for your category, and split your next brief so the video serves one side and a genuine forum presence serves the other.",
    "The IAB raised its US ad spend growth estimate for this year from 9.5 percent to 12.3 percent and credits part of the rise to brands spending more on awareness work to improve how AI answers describe them, with 61 percent of 2,600 US shoppers surveyed by Dept having used an AI assistant for shopping in the past three months.  Add a slide to your next budget request tracking your share of mentions in AI answers next to your share of search, monthly from now, so you own the baseline before the standards arrive.",
    "Howl ran up delinquent invoices of 20,000 to 900,000 dollars stretching back eight months, still owes one publisher around 60,000, and quietly sold its creator business to Taboola's Connexity in August, whose first email to acquired creators was about fixing payments.  Write down who holds the money between sale and payout on every creator and affiliate contract you run, and move the ones your finance team would not extend credit to onto direct payment.",
    "Sonos lost at least 100 million dollars of revenue in the six months after its 2024 app update and has built its first repositioning since then around the system that broke, made entirely in house with no agency, as third-quarter revenue rose 9 percent to 375 million.  Ask the team that owns your biggest customer complaint whether it is genuinely fixed and how you would prove it in thirty seconds, then build the next campaign on whichever answer you get.",
    "Nintendo's pre-recorded Direct peaked above 3.7 million concurrent viewers on 11 September with more than 2,200 channels carrying it, while BlizzCon's two-day convention peaked at 1.76 million across more than 1,400 channels and 8.8 million hours watched.  Demand peak concurrents, average concurrents, hours watched and total airtime in one table on your next live sponsorship proposal, and price the official broadcast separately from the co-stream network.",
    "Sydney Sweeney holds equity in Novig and says she was in the creative conversations from the start, and the backlash to its first national campaign landed on her exactly as it landed on Kendall Jenner, Mary J. Blige, Brooke Shields and Danica Patrick for work they did not author.  Draft the statement naming your brand as the author of the idea before the campaign ships, and put it in the same approval pack as the creative.",
    "TheOutdoorGearReview has 768,000 subscribers, 234 million lifetime views, a 105,000-view median across his last fifteen uploads and 411,273 on an unsponsored bivvy tent video, and by our count the premium brands he reviews all land below his median while his no-product storm films sit around 144,500.  If you sell tents, packs, sleep systems or camp stoves, send him your hardest-to-believe product this week with no brief and no conditions, budgeted as seeding rather than media.",
]

SHARE = [
    {
        "who": "JARED · CEO",
        "angle": "More distribution partners did not produce more audience.  The company that owned the moment did.",
        "post": "A pre-recorded video that runs under an hour drew more than twice the live audience of a two-day convention last week. Both had over a thousand channels carrying them.\n\nNintendo's Direct on 11 September peaked above 3.7 million concurrent viewers. BlizzCon, in a venue in Anaheim across 12 and 13 September, peaked at 1.76 million. Figures from Streams Charts.\n\nThe channel count is the part I did not expect. More than 2,200 channels carried the Nintendo Direct. More than 1,400 covered BlizzCon. So the event with fewer partners was also the one that lost, which means the partners were not the variable.\n\nNintendo's biggest community caster peaked around 46,000 across two channels. Roughly one percent of the audience. Everyone else went to the source.\n\nI have sat in meetings where distribution is treated as the hard part and the thing itself is assumed. This says the opposite. Blizzard had a venue, two days of programming and 1,400 partners amplifying it, and still came second by a factor of two to a video with no audience in the room.\n\nWhat Nintendo has is an appointment. A channel it owns, a format people recognise, and enough repetition that announcing a date is the entire campaign.\n\nYou cannot buy that this quarter. You can only start it this quarter, which is a much less satisfying thing to write into a budget.",
        "why": "It argues for owned video using two numbers a non-specialist can hold, and it contradicts the thing every client believes, which is that reach is a distribution problem.",
    },
    {
        "who": "JAMES · CREATIVE DIRECTOR",
        "angle": "Creative input does not transfer reputational risk, because the audience cannot see who wrote it.",
        "post": "Sydney Sweeney holds equity in Novig and says she was in the creative conversations from the very beginning. The backlash to their campaign has landed on her exactly the way it landed on Kendall Jenner, who wrote none of the Pepsi ad she is still known for.\n\nAdweek ran the pattern piece the next morning. Mary J. Blige carrying a 2012 Burger King spot the brand later said was not the final cut. Brooke Shields at fifteen carrying a line written by Calvin Klein and Richard Avedon. Danica Patrick carrying a concept GoDaddy's founder has admitted was his.\n\nFour women. Four different levels of actual authorship. One identical outcome.\n\nMost of us in creative work assume responsibility follows the craft. It does not, because the craft is invisible. A viewer cannot see the room, the deck, the safer version that got killed or who killed it. They see a face and they assign the idea to it.\n\nSo when the work lands, someone else gets credited, and that is the job. When it does not, someone else gets blamed, and that is not.\n\nGiving talent creative input moves none of this. Sweeney had more input than most and carries all of it anyway.\n\nThe minimum fix is the brand saying whose idea it was, publicly, on the day. I cannot think of a time I have watched it happen.",
        "why": "A creative director conceding that craft is invisible and that the work's author is never the person blamed is the uncomfortable admission that makes the argument credible.",
    },
    {
        "who": "LAWRY · LEAD VIDEO EDITOR",
        "angle": "Cutting the audio version first is an edit decision that tests whether a positioning survives being described rather than shown.",
        "post": "Sonos launched a campaign yesterday whose entire argument is that it sells a system rather than a speaker. It is running on out-of-home, print, online video, social, streaming audio and podcasts.\n\nTwo of those have no picture.\n\nMost edits go one way. You cut the film, you lift a thirty and a fifteen out of it, and then somebody asks for the audio version and you pull the voiceover off the timeline and hope it still holds. The audio cut is a byproduct. It is also the only version where the idea has nowhere to hide.\n\nA system is a genuinely hard thing to show. It is several objects and the invisible thing between them. In picture you can get there with a cut that moves through rooms. What you cannot do is fake it with a beautiful static shot of a speaker, which is most of what a speaker brand's footage actually is.\n\nTheir marketing chief said the proof is in the software work, not the tagline. I read that as somebody who knows the film cannot carry it alone.\n\nIf I were starting this, I would cut the podcast read first. Thirty seconds, no picture, and see whether the claim survives being described.\n\nI do not know what order they worked in. I know which order finds the problem before the shoot is booked.",
        "why": "It is an edit-room decision about which version you cut first, and the consequence is a business one, which is finding out a positioning is undemonstrable before you have paid for the crew.",
    },
]
