ISSUE = {
    "date_iso":  "2026-09-22",
    "kicker":    "Crux Media // Tuesday 22 September 2026",
    "tagline":   "What brands did on YouTube yesterday, and whether it worked.",
    "pace":      "STEADY",
    "next_drop": "Next drop: Wednesday, 06:30 MT",
}

LEAD = {
    "headline": "A MILLION SUBSCRIBERS, MORE THAN 60 MILLION VIEWS, TEN YEARS, AND THE FIRST REASON GIVEN FOR CLOSING THE CHANNEL WAS THAT SQUARESPACE IS PULLING OUT",
    "deck": "Mango Street has taught photography on YouTube for ten years and across nearly 400 videos.  Its two founders have said it is ending, The Publish Press reported it yesterday, and the first reason they gave was that Squarespace is pulling out before the end of the year.  A million subscribers were still there.  What left was one line in somebody else's marketing budget.",
    "stamps": [
        ("THE PUBLISH PRESS · 21 SEP", "https://news.thepublishpress.com/p/live-from-new-york-it-s"),
        ("MANGO STREET · YOUTUBE", "https://www.youtube.com/watch?v=SWxtsTfZOao"),
    ],
    "body": [
        "Mango Street is Rachel Gulotta and Daniel Inskeep, who have been making photography tutorials for a decade.  <mark>Ten years, nearly 400 videos, a million subscribers, more than 60 million views.</mark>  They announced the end in a video titled the end of mango street, and The Publish Press reported it yesterday.",
        "The reasons came in an order, and the order is the item.  <mark>First, Squarespace is pulling out before year-end.  Second, views and engagement had been declining for a while.  Third, the channel was built almost entirely on long-form with no short-form hedge.</mark>  Inskeep on the decline: for the past couple years we felt like there was a dark cloud over our channel, videos weren't getting a lot of comments or views.  And his advice to other creators: diversify your forms of revenue, you never know when it's going to disappear.",
        "Before the mechanism, the honest part.  <mark>We have one outlet and the creators' own video.  No revenue figures were published — nothing on what share of the channel's income Squarespace was, no fee, no term, no notice period.</mark>  Squarespace has not commented.  We went looking for reporting that Squarespace is cutting creator spend generally and found none from any named publication, so do not read this as a brand pulling out of the category.  Read it as one renewal not happening.",
        "What survives is the structure, and it is the thing worth your morning.  An advertising read on a 20-minute photography tutorial is not a bonus on top of the platform money.  <mark>On a teaching channel in a small niche the sponsor is structurally the load-bearing revenue line rather than a bonus on top of the platform money, because the platform pays on views while the advertiser pays on the audience being the exact people it wants.</mark>  We have no figure for this channel, which is precisely why the closure is the only evidence anybody gets.  The anchor advertiser leaving is not a line item going down.  It is the line item going away.",
        "Now the half that changes what you do, because it is the buyer's half.  <mark>If your exit closes a channel, you were not buying a media placement at market price.  You were funding the asset.</mark>  That is a different thing and it carries different leverage — on price, on term, on what you get for renewing — and few buyers price it that way.  Worth noting we wrote on the seventeenth that Squarespace also funds a coffee channel of unusual technical depth.  We have no visibility into that budget, and that is the point: decisions inside one company's marketing plan are deciding which channels exist.",
        "It cuts the other way too.  If you are the anchor sponsor on a channel you depend on, the audience you are buying is sitting on a single point of failure, and you are the point of failure.  <mark>We have never seen a brand audit its creator roster for this.</mark>  You can find out in an afternoon by asking one question, and the answer tells you which of your partnerships is actually a dependency.",
    ],
    "numbers": [
        ("1", "advertiser whose exit was the first reason the founders gave for closing the channel"),
        ("1M", "subscribers and more than 60 million lifetime views attached to an archive that stops getting new uploads"),
        ("0", "revenue figures published, so nobody outside can say what share of the business that sponsor was"),
    ],
    "flagnote": "Every figure here comes from The Publish Press's reporting of the creators' own announcement video.  No financial detail was published at all — no fee, no term, no notice period, no revenue split, no share of income — so no claim about how much of the business the sponsorship represented can be tested, and we have not made one.  Squarespace has not commented and we found no named publication reporting that it is reducing creator sponsorship generally; the withdrawal is stated by the creators about their own deal only.  The subscriber, video and view counts are as reported and are YouTube's rounded figures rather than exact counts.  The three reasons are given in the order the creators gave them, which is not evidence of their relative weight.",
    "so_what": "On a small-niche teaching channel the sponsor is usually the business, not a bonus on top of it, because the platform pays for views while the advertiser pays for the audience being precisely the right people.  That makes an anchor advertiser structurally load-bearing in a way the rate card never says out loud.  Both sides have been pricing these deals as media placements when the money is closer to funding than to buying.  The brand that works that out gets better terms, and the brand that does not eventually loses a channel it had come to rely on.",
    "do_this": "Pull your creator roster this week and ask every partner one question: what share of your channel's revenue does our deal represent.  Anyone above roughly a third is a dependency rather than a placement, and you should be negotiating term and price on that basis and staggering their renewal away from your other partners'.  Then flag the ones where your exit would end the channel, because that is your leverage and also your risk.",
}

SECTIONS = [
    {
        "id": "ls", "name": "L'S", "page": "pg. 03",
        "note": "what broke, and the failure mode that broke it",
        "tint": "pink",
        "items": [
            {
                "title": "A creator marketing company says one campaign got 38 times more clicks per dollar, and the thing it beat was the brand's own photographs",
                "hook": "Wrong baseline.  A multiple is only worth as much as the ad it is multiplying, and this one was multiplying static images.",
                "stamps": [
                    ("NET INFLUENCER · 22 SEP", "https://www.netinfluencer.com/ghost-is-building-a-creator-marketing-model-between-agencies-and-in-house-teams/"),
                ],
                "body": [
                    "Ghost was founded in 2024 in Los Angeles by R.J. Napolitano, previously at Goldman Sachs.  It sits between an agency and an in-house team: it sources creators, runs the outreach and contracting, and produces content specifically to be run as paid advertising.  On the creator side it ships software that connects to Gmail and drafts replies to brand enquiries.  Pricing is a month-to-month subscription scaled to the campaign, with no long commitment.",
                    "The claim, in the piece's exact words: <mark>the campaign generated 38 times more clicks per dollar compared with the brand's previous ads.</mark>  The client is Badia Spices.  Napolitano calls it a bread-and-butter kind of case study.",
                    "Now the denominator, which is the whole item.  <mark>Those previous ads were the brand's static images and customer photos it had been tagged in, run as digital advertising.</mark>  So the comparison is creator-made video against the brand's own photographs and reposted customer pictures.  Not against the brand's best video.  Not against a professionally produced spot.  Against pictures.",
                    "And note what the metric is not.  <mark>Clicks per dollar is not cost per customer, not revenue, and not return on advertising spend.</mark>  A click is the cheapest thing in the chain to move and the easiest to move badly — a thumb-stopping video will beat a photograph on clicks almost every time without telling you anything about whether anyone bought spices.  The performance of the baseline ads is not published either, so there is no way to know whether 38 times a very bad number is a good number.",
                    "The honest version of the underlying point is still worth having.  Creator-made video used as paid advertising does generally beat a static image, that gap is real, and testing it costs almost nothing.  You just cannot learn anything from a multiple whose denominator is undisclosed, which is why the number that got published is the least useful part of the story.",
                ],
                "flagnote": "The 38 times figure is supplied by the company that ran the campaign, for its own case study, with no audit and no absolute figures on either side of the comparison.  Only one client is named and no funding, headcount or campaign spend is disclosed anywhere in the piece.  We found no second source for the figure and no statement from Badia Spices.  The characterisation of the baseline as static images and user-tagged content is the article's own description of what the previous ads were.",
                "so_what": "A multiple is a sentence with its comparison deleted.  38 times more clicks per dollar than what, spending how much, against what absolute number — strip those out and you are left with a figure that cannot be wrong because it cannot be checked.  The failure mode is not dishonesty, it is that the baseline gets chosen by whoever benefits from the comparison, and the weakest available baseline produces the biggest headline.",
                "do_this": "Run the comparison yourself this week and own both sides of it.  Take your best-performing static advertisement and your best creator-made video asset, put the same budget behind each, same audience and same offer, and report clicks per dollar as two absolute numbers rather than as a ratio.  Then do the same on cost per purchase, because that is the number the ratio was hiding.",
            },
        ],
    },
    {
        "id": "moves", "name": "MOVES", "page": "pg. 04",
        "note": "who did what, and what it signals",
        "items": [
            {
                "title": "Google wrote Gemini into the Sidemen's survival challenge as the thing they have to use to solve it, which is a sponsor no editor can lift out of the timeline",
                "hook": "Five videos, one flagship slot and then a second channel five weeks later.  The product is a rule of the format, not a read.",
                "stamps": [
                    ("NET INFLUENCER · 22 SEP", "https://www.netinfluencer.com/the-sidemen-partner-with-google-gemini-for-multi-video-back-to-school-campaign/"),
                    ("CAMPAIGN · UK", "https://www.campaignlive.co.uk/article/google-gemini-teams-up-with-the-sidemen-for-forest-survival-content-series/4gfgcdmmtjmccxsa91jq2wga54"),
                    ("SIDE PLUS · LISTING", "https://watch.sideplus.com/videos/sdmnsunday-survive-forest-2"),
                ],
                "body": [
                    "The deal is five original videos for Google Gemini, sold as a back to school run.  <mark>The first went out on Sunday 20 September in the Sidemen Sunday slot on the main channel: 24 hours in a remote UK forest, completing challenges to earn tokens for supplies, using Gemini to learn survival skills and solve problems as they go.</mark>  Four more start on 24 October on MoreSidemen, including a format where the group ranks unusual food combinations and Gemini proposes the pairings.  Produced by Sidemen Entertainment with Arcade, the Sidemen's commercial arm.  There is a fan giveaway of signed merchandise and Google Home hardware attached.",
                    "The shape of the buy is the first thing to copy.  <mark>One flagship episode on the biggest channel to buy reach, then four on the secondary channel five weeks later to buy frequency at a lower price.</mark>  The members' cut of the same forest episode runs two hours eighteen minutes, so the format is long enough to carry a product across its length rather than at one point in it — though that listing does not mention Gemini at all, so we cannot say how the product sits in that version.",
                    "The mechanism is the second thing, and it is the reason this is worth copying rather than just noting.  Arcade's commercial managing director Joe Lamb framed it as pairing the product with the group in formats that feel native rather than bolted on.  <mark>Make the product the thing the talent has to use and there is no block to skip — and no block to cut either.</mark>  A sponsor read is a removable object on a timeline.  A sponsor the challenge runs through is structural, and the audience cannot route around it without leaving the video.",
                    "<mark>This is Google's second large creator deal in a month.  On 2 September it signed MrBeast to a multiyear arrangement across Gemini, Google Health and Fitbit.</mark>  Two deals, same pattern: buy a demonstration of the product solving a real problem inside a format that already works, rather than making an advertisement about the product.",
                    "What nobody has published is whether any of it performed.  <mark>No views, no fee, no engagement data, no completion figures.</mark>  The first video is two days old as we write, and the trade round-ups that count branded video have not reached it yet.  So the case here is the construction, not the result, and we will come back when there is a number.",
                ],
                "flagnote": "No performance data, no fee and no deliverable terms have been published by anyone, so nothing in this item is evidence that the campaign worked — only that it is built a particular way.  Our main source is a trade write-up that follows the announcement closely; the Campaign piece is sign-in gated and we confirmed only its headline, byline and the format description.  The Side Plus listing is the paywalled members' cut and its page carries no mention of Gemini at all, so the runtime is verified but we cannot confirm the sponsored content is identical in that version.  The comparison with the MrBeast arrangement is ours; Google has not framed the two as a single strategy.",
                "so_what": "Where the product sits in the structure decides whether it gets watched, and that decision is made at format stage rather than in the edit.  A read is a block, so it is skippable, cuttable and therefore cheap.  A product that the talent must use to win is load-bearing, so it cannot be skipped, but it also cannot be revised without restructuring the video.  You are choosing between a cheap thing people avoid and an expensive thing they cannot, and most brands make that choice by accident.",
                "do_this": "On your next creator brief, write one sentence specifying whether the product is a removable block or a rule of the format, and put it above the deliverables rather than in them.  If you choose the format version, lock your notes before the shoot, because after that every brand note is a structural rewrite rather than a swap.  Then buy the flagship slot once and the secondary channel four times, and compare cost per completed view across the two.",
            },
            {
                "title": "MrBeast spent about ten million dollars on a video with no sponsor, said in advance it would underperform, and pointed its call to action at the industry his own product competes in",
                "hook": "No brand could have bought this one, and that is the design.  The video ends by naming the chocolate industry, and he sells chocolate.",
                "stamps": [
                    ("FORTUNE · 21 SEP", "https://fortune.com/2026/09/21/billionaire-youtuber-mrbeast-ghana-village-philanthropy-work-engagement/"),
                    ("DEXERTO · 19 SEP", "https://www.dexerto.com/youtube/mrbeast-builds-10-million-village-to-rescue-kids-in-ghana-from-illegal-labour-3410389/"),
                ],
                "body": [
                    "The video went out on Saturday and covers the building of Abna Dakwa, a village in Ghana, at a reported cost of nearly ten million dollars over eight months of construction.  <mark>A school for more than 300 students with five years of free daily meals, ten teacher homes, a medical clinic, a marketplace, a community farm, off-grid solar, two water towers and fish farming tanks.</mark>  The stated aim is keeping children out of illegal labour, much of it in cacao.",
                    "He set the expectation himself before it went out: it prob won't perform that well, but it's something I care a lot about and I hope my passion for it shines through.  Challenged afterwards on the idea that he only does this for views, he told Fortune it's literally the opposite, and said he will keep making them.",
                    "Then the line that makes this a business item rather than a philanthropy one.  <mark>The video's call to action is that big chocolate will not care about rampant child labor until you guys watching this video do something about it.</mark>  He owns Feastables, which sells chocolate.  A video reported at nearly ten million dollars carries no sponsor because no sponsor could carry it, and it ends by naming the supply-chain problem of the category his own product sells into.",
                    "<mark>No view figure has been published anywhere.</mark>  We looked across the trade press and the general press and there is none, three days after release, and we cannot explain the absence beyond noting it matches the expectation he set in advance.",
                    "The reaction arrived faster than the numbers.  Within roughly 48 hours the criticism was, why not spend it at home, with Greenville, North Carolina named specifically, and he answered by pointing at his own nonprofit's domestic work.  That question is going to be asked of every brand that co-signs something like this.",
                ],
                "flagnote": "No performance data exists for this video as we write, so nothing here is a claim about how it did.  The cost, the build specification and the eight-month timeline are as reported and are not independently audited; Fortune names no co-funders and we have not verified the partner organisations named elsewhere.  The link between the video's call to action and the Feastables business is drawn in Dexerto's reporting and by us, not by MrBeast in the wording we have.  The criticism is described in the reporting as coming from users rather than from any organisation, so treat its scale as unquantified.",
                "so_what": "This is not a video buying reach, it is a video buying a position in a category, and the only person who can fund it is the person who owns a product in that category.  That is the actual lesson for a brand: the reason he does not need a sponsor is that he is the sponsor, and the return shows up in how his chocolate is understood rather than in the view count.  It also shows how fast the reputational bill arrives — the domestic-spend question landed inside two days, before any performance figure did.",
                "do_this": "Write your domestic-spend answer this week, one paragraph with real figures, and give it to whoever runs your social accounts, so it exists before any creator brings you an overseas philanthropy piece to co-sign.  Then, if you own a product in a category with a supply-chain problem, brief one video that fixes a specific piece of it and names the category, rather than another film about your own sourcing standards.",
            },
            {
                "title": "Arcade signed six creators and put creator video in front of more than 150 advertisers with guaranteed delivery attached",
                "hook": "The licence is the story.  Guaranteed delivery moves creator video out of the influencer line and into the budget that owes you compensation when delivery falls short.",
                "stamps": [
                    ("NET INFLUENCER · 21 SEP", "https://www.netinfluencer.com/arcade-sets-out-to-bring-primetime-budgets-to-european-creator-media/"),
                ],
                "body": [
                    "Arcade was founded in 2021 by Jordan Schwarzenberger, Sam Uwins and Aaron O'Neill and is the Sidemen's commercial business.  <mark>Matt Elek became chief executive in July 2026 after 18 years at Vice Media, more than a decade of it running Europe, the Middle East and Africa.</mark>  Six new signings: Max Fosh, Friends From Work, John Nellis, Faith Kelly, Generation Football and Fallow Chefs.  There is a seven-figure investment from Lumina Media.  Brands named as partners include Virgin Media O2, Formula E, Esports World Cup, Unilever, Lego and Papa Johns.",
                    "<mark>On 17 September it held an invite-only slate presentation in London to more than 150 advertisers and brand partners, showing what its creators will make over the coming year alongside audience data — the advance sales day television networks have run for decades, done for creator video, which the company says is a first in Europe.</mark>",
                    "The load-bearing detail is one clause.  <mark>Its Creator Access division holds a YouTube Partner Sales licence, which enables guaranteed ad delivery against its creator roster.</mark>  That is the difference between hoping a video performs and being contractually owed the audience you paid for, with a make-good — compensation, usually free inventory — when it falls short.",
                    "Elek's own positioning is that this is not a legacy media business working out how to handle creators, because creators are all it does.  He also says the company's returns track its creators' success rather than the volume of deals it processes, which is a claim about incentives that nobody outside can check.",
                    "<mark>No budgets, no revenue, no headcount and no reach figures were disclosed.</mark>  The only numbers in the whole story that describe the business are 150 advertisers and a seven-figure investment.",
                ],
                "flagnote": "One outlet, and the piece reads close to a company profile with the company's own framing throughout.  No revenue, budget, headcount or audience figures are disclosed, and the claim that the London event is the first of its kind in Europe is the company's, not independently established.  What the YouTube Partner Sales licence permits is described only as enabling guaranteed ad delivery, with no technical detail and no confirmation from YouTube.  The incentive claim about returns tracking creator success is unverifiable from outside.",
                "so_what": "Guaranteed delivery is what separates buying media from buying a creator, and it is the thing that lets a brand move the money out of a discretionary marketing line into the one with guarantees and make-goods.  That is a much bigger change to how creator video gets funded than any individual signing, because it changes who inside a company is allowed to approve the spend and what they can promise upwards.  If it works in Europe, every large creator business will want the same licence.",
                "do_this": "Ask each of your creator partners and your agency this week whether they can guarantee delivery, under what licence, and what the make-good is when a video underdelivers — and get the answer in writing rather than on a call.  Wherever the answer is yes, price that inventory against your paid video budget rather than your influencer budget, because it is now the same kind of thing.",
            },
            {
                "title": "Alex Cooper's network is commissioning shows hosted by other people, and the best episode of its big competition format did 1.8 million views",
                "hook": "Keep that number.  It is what a well-funded creator network original actually delivers, and it is the figure to hold up when someone prices one against television.",
                "stamps": [
                    ("ADWEEK · 21 SEP", "https://www.adweek.com/media/unwell-alex-cooper-new-shows-youtube/"),
                    ("NET INFLUENCER · 22 SEP", "https://www.netinfluencer.com/alex-cooper-unwell-expands-youtube-slate-with-four-new-shows-after-500m-usd-valuation/"),
                ],
                "body": [
                    "Four new shows, announced by Unwell's vice president of marketing Ali Lee.  <mark>Petticoat Revolution with Charlotte Long and Daphne Woolsoncroft, and Chronically Out of Line with Molly Scheader, both starting this week; Dani's Side Quest with the UK creator Dani Babes and a second season of Me and Who Els with Elsy Guevara, both in October.</mark>  Fourteen shows are in production and the network puts its combined audience at close to 100 million followers.",
                    "The money behind it: <mark>a 500 million dollar pre-money valuation in August 2026 from WTSL, run by the former Endeavor executive Patrick Whitesell with Jason Lublin.  First outside capital since Unwell launched in 2023.</mark>",
                    "Now the benchmark, and it is the reason this is worth reading rather than skimming.  <mark>Unwell's Winter Games premiere did 1.4 million views on YouTube and its best-performing episode did 1.8 million.  The Summer Games edition carried a 250,000 dollar prize pool.</mark>  That is a competition format from a network valued at half a billion dollars, with a six-figure prize on the table, landing between one and two million views an episode.",
                    "Be careful with what those figures describe.  <mark>They are Winter Games numbers, a different and older property, not evidence about any of the four new shows.</mark>  Nobody has published a figure for the new slate because two of the shows are days old.",
                    "The stated reason for the YouTube weighting is soft — co-founder Matt Kaplan says the audience moves fluidly across platforms and the job is to meet them where they are.  The structural tell is better than the quote: a podcast company is now commissioning video formats fronted by other creators, which is what a studio does.  The pieces also cite Nielsen's July 2026 finding that YouTube took a record 14.2 percent share of total television usage.",
                ],
                "flagnote": "The 1.4 million and 1.8 million view figures relate to Unwell Winter Games, an earlier property, and say nothing about the four new shows; we have used them only as a benchmark and have labelled them as such.  No budget, fee or advertising rate for any of the shows has been disclosed.  The valuation is pre-money and self-reported through the announcement rather than filed.  The Nielsen share figure is for total television usage across all of YouTube, not for creator-network programming, and is quoted from these pieces rather than from Nielsen directly.",
                "so_what": "The interesting number here is the small one.  A creator network with half a billion dollars of valuation behind it, a six-figure prize pool on a sister edition and 100 million followers to promote into produced a competition whose best episode did 1.8 million views.  That is a good outcome and it is also an ordinary one, which means the pitch that creator network originals are television-scale should be held to television-scale numbers before you pay television-scale prices for them.",
                "do_this": "The next time anyone pitches you integration into a creator network original, ask for per-episode views on their last three seasons before you discuss price, and compare it against what an individual creator of the same audience size delivers for a fraction of the production cost.  If the network number is not clearly higher, buy the individual creator and put the difference into more videos.",
            },
        ],
    },
    {
        "id": "onstream", "name": "ON STREAM", "page": "pg. 05",
        "note": "live audiences, what the numbers actually measure, and what a sponsor got",
        "items": [
            {
                "title": "Rocket League crossed 700,000 concurrent viewers for the first time, and the release reporting it left out every number you would need to price against it",
                "hook": "704,608 at peak, four times the qualifying stage we ran on Friday.  Same measurement company, and this time no averages, no duration and no channel count.",
                "open": True,
                "stamps": [
                    ("ESPORTS CHARTS · 21 SEP", "https://escharts.com/news/rlcs-2026-world-championship-viewership"),
                    ("ESPORTS CHARTS · 21 SEP", "https://escharts.com/news/ffws-southeast-asia-2026-fall-viewership"),
                    ("ESPORTS CHARTS · 21 SEP", "https://escharts.com/news/lec-summer-2026-viewership"),
                ],
                "body": [
                    "The RLCS — the Rocket League Championship Series — held its 2026 World Championship at Dickies Arena in Fort Worth and Esports Charts published the figures yesterday.  <mark>Peak concurrent viewers hit 704,608, the first Rocket League match ever above 700,000, and 7.7 million hours were watched.</mark>  Peak concurrent viewers is the largest number of people watching at one single instant across every channel carrying it.  704,608 at one moment is close to eight full Wembley Stadiums.  One thing to say plainly, because the release does not put it in the headline: <mark>that peak came from the Karmine Corp against Team Falcons semifinal, not the grand final.</mark>",
                    "Now what is missing, and it matters more than the record.  <mark>No average concurrent viewers, no broadcast duration, no channel count and no platform split were published.</mark>  Compare that with the same company's release on the qualifying stage four days earlier, which we ran on Friday: peak 173.2 thousand, average concurrents up 30.9 percent, hours watched above 782 thousand, and a broadcast about 35 minutes longer than the previous year's.  That release let you separate a longer show from a bigger audience.  This one does not, so 7.7 million hours is a number you can quote and cannot price against.",
                    "The growth that is real and specific: <mark>Arabic watch time rose 218.2 percent and Arabic peak viewership rose 285.1 percent year on year</mark>, on the back of the Saudi-backed Team Falcons reaching the final.  Spanish and Portuguese grew in both measures without published percentages.  English and French remain the two largest broadcast languages.",
                    "For the channel-count trap, look at a second release the same day.  <mark>The Free Fire World Series Southeast Asia 2026 Fall peaked at 681,910 during Round 11 of the grand final in Surabaya, up 13.79 percent on the Spring edition — counted across 290 broadcasting channels against 133 in Spring.</mark>  The channels counted more than doubled.  Watch time on Kick, the livestreaming platform, went from around 5,600 hours to 100,000, driven by Hindi and Nepali channels.  Indonesian watch time rose 50.1 percent and Vietnamese 37.1 percent.  No total hours watched figure was published at all, so the only hard number in that release is the peak.",
                    "And the release nobody will forward you.  <mark>The LEC, the top European League of Legends competition, peaked at 434,973 on its summer grand final between G2 Esports and KOI, down 8.13 percent year on year, with average concurrent viewers down 17.9 percent.</mark>  Esports Charts calls it the second-least popular event across the last eight half-seasons and the lowest peak since 2024.  Same publisher, same day, three events, and the one in decline is the one European advertisers are most likely to have already bought.",
                ],
                "numbers": [
                    ("704,608", "peak concurrent viewers at the Rocket League world final weekend, close to eight full Wembley Stadiums at one instant — and the peak came from a semifinal"),
                    ("290 / 133", "broadcasting channels counted for the Free Fire Southeast Asia final this edition against the last one, which is why a 13.79 percent rise in peak is not a 13.79 percent bigger audience"),
                    ("434,973", "peak for the European League of Legends summer final, down 8.13 percent year on year with average concurrents down 17.9 percent"),
                ],
                "flagnote": "Esports Charts sells the measurement it publishes and all figures are estimated from platform data rather than audited.  The Rocket League release published no average concurrent viewers, no airtime, no channel count and no platform split, and gave no exact tournament dates, so its 7.7 million hours watched cannot be converted into a cost to reach a thousand people or compared like for like with any other event.  The Free Fire release published no hours watched figure at all and no airtime.  The LEC release published no absolute average concurrent figure, no hours watched, no airtime and no channel count, and its deeper tournament data sits behind a paid dashboard.  None of the three releases carries sponsorship or disclosure data.  The Wembley comparison is ours, using a 90,000 capacity.",
                "so_what": "Three releases from one company on one day, and the amount you can do with each depends entirely on which metrics they chose to print.  Hours watched without a duration and a channel count is not an audience measurement, it is a coverage measurement — the Free Fire release proves it, with the channels counted going from 133 to 290.  Peak is the most robust of the three figures, but only while the channel count holds still — Free Fire's peak rose 13.79 percent as the channels counted went from 133 to 290, so even a peak needs the channel count printed next to it.",
                "do_this": "When a rights holder or agency sends you growth figures this week, answer with a question before you answer the offer, and ask for four things in writing: peak concurrents, average concurrents as an absolute number, the broadcast duration, and the number of channels counted.  If any are missing, price off peak alone and tell them that is why.  And if you want Arabic-language reach cheaply, ask what Rocket League costs this week, before anyone reprices it off that 285 percent.",
            },
        ],
    },
    {
        "id": "watch", "name": "ONE TO WATCH", "page": "pg. 06",
        "note": "one creator with momentum, and the specific client who should be calling",
        "items": [
            {
                "title": "KeepingFishSimple has 487,000 subscribers and 88 million lifetime views, and not one of its last fifteen videos carries a sponsor of any kind",
                "hook": "193,858 views against a 57,909 median.  Both of his big recent videos put an admission in the title, and the steady band underneath them is him running the shop.",
                "open": True,
                "stamps": [
                    ("KEEPINGFISHSIMPLE · YOUTUBE", "https://www.youtube.com/@KeepingFishSimple"),
                ],
                "body": [
                    "The channel joined YouTube on 3 March 2013 and belongs to the owner of an aquarium store in Rocklea, Brisbane.  <mark>635 videos, 88,019,155 lifetime views, 487,000 subscribers on YouTube's rounded figure.</mark>  Two formats: deep single-species breeding and care guides at 15 to 40 minutes, and a newer documentary strand about running the shop, the warehouse and the fish food factory.  Almost no Shorts.  Across the last fifteen uploads he posts every 8.4 days.",
                    "The momentum is a month old and clean.  <mark>Nobody Told Me Breeding Bichirs Was This Easy went up on 27 August and has 193,858 views, against a 57,909 median across his last fifteen long-form uploads.</mark>  That is 3.35 times his own median.",
                    "The shape underneath it is the part a brand should read twice, and it is about titles rather than subjects.  <mark>His two biggest recent uploads both put an admission in the title: Nobody Told Me Breeding Bichirs Was This Easy at 193,858, and Why I Stopped My Fish Breeding Business at 162,544.  The shop and warehouse documentaries sit in a reliable middle band — 63,364 for a tour of the store, 58,562 and 57,909 for two days-in-the-business pieces, 31,172 for a shop and factory upgrade.  Straight species guides sit at the bottom: zebra plecos at 38,472, freshwater stingrays at 18,042, the easiest whiptail catfish at 17,906.</mark>  So the business strand is the floor that holds the channel up, and the spikes come from a confession rather than from a species.",
                    "Then the opening.  We read the full descriptions of his last fifteen uploads.  <mark>No sponsor read, no paid-promotion disclosure, no discount code, no affiliate link of any kind, no Amazon associate links, no Patreon.</mark>  What is there is his own business: the website, a live fish collection, merchandise, the physical store address, and two links to a collaborator and a wholesaler he visited.",
                    "So there is a man demonstrating filtration, lighting, heating, controllers and racking on camera for 15 to 40 minutes at a time with no advertising read anywhere in them, inside a quarantine room and a warehouse fit-out, in front of an audience of nearly half a million people in a hobby built on buying exactly that equipment, and the equipment brands are getting all of it for nothing.  <mark>He also owns the retail end and manufactures his own fish food, which makes him unusually attributable and unusually conflicted at the same time.</mark>",
                ],
                "watch": {
                    "label": "TOP VIDEO, LAST 3 MONTHS",
                    "title": "Nobody Told Me Breeding Bichirs Was This Easy",
                    "url": "https://www.youtube.com/watch?v=bs7IBgtz2jU",
                    "meta": "193,858 views · published 27 August 2026 · 15:53",
                    "note": "A breeding walkthrough shot in his own fish room, with tanks, filtration and heating equipment in frame for most of it.",
                },
                "flagnote": "The subscriber count is YouTube's rounded public figure and no exact number is available.  The 57,909 median is ours, computed across his last fifteen long-form uploads, and every view count is live and still climbing.  View counts and publication dates come from the channel's own published feed data rather than from a third-party measurement company.  The sponsorship finding is from reading fifteen recent video descriptions and the channel's own pages, not from asking him.  He has a video at around 420,000 views from roughly four months ago; the fifteen uploads we used span about four months, so we cannot say for certain whether it sits just inside or just outside them, and either way this is a channel reliably throwing 150,000 to 200,000 outliers rather than one setting records.  He is Australian, he is a competing retailer, and he manufactures fish food, so those two categories are hard conflicts rather than opportunities.",
                "so_what": "A thirteen-year-old channel with no paid read anywhere in its recent output has no rate to anchor against, which makes it about as uncontested as creator inventory gets — and it usually also means the absence is a decision rather than an oversight, so the first conversation is about whether at all, not about price.  The format does something no short read can: a filter or a controller that appears across a multi-month shop build gets demonstrated under real load, by someone whose credibility rests on nobody paying him.  And because he owns a store and an online livestock shop, this is a rare case where you can actually attribute what the video did.",
                "do_this": "Spend an hour this week reading the last fifteen video descriptions on the three biggest channels in whatever category you actually sell into, and list the ones with no sponsor read, no discount code and no affiliate link — that list is your unpriced inventory, and this is how you build it.  If aquarium equipment happens to be your category, email him proposing supplied equipment across the shop and warehouse strand rather than the care guides, with no script approval and a clear disclosure, and ask for store-level sales in the four weeks after each video, since he owns the till.",
            },
        ],
    },
    {
        "id": "money", "name": "THE MONEY", "page": "pg. 07",
        "note": "what things cost, and which way the price is moving",
        "items": [
            {
                "title": "Three measurement companies were re-certified as national currencies this morning, and Nielsen still carries 80 to 90 percent of what actually gets traded",
                "hook": "672 tests, and no published statement of who passed what.  Certification says a number can be traded on, which is not the same as anybody trading on it.",
                "open": True,
                "stamps": [
                    ("MEDIAPOST · 22 SEP", "https://www.mediapost.com/publications/article/418174/joint-industry-committee-re-certifies-3-media-me.html"),
                ],
                "body": [
                    "<mark>The Joint Industry Committee re-certified Comscore, iSpot and VideoAmp as national currencies — the audience datasets advertisers and broadcasters are allowed to write into a contract and pay against — for 2026 through 2028.</mark>  The criteria, in its own words, are transactability across total households, advanced audiences and personified demographics, which in plain terms means whole-household reach, narrower targeted audiences, and person-level age and gender.  The process it describes: 39 data-evaluation questions, 672 tests across transaction types and estimation methods, and 150 million telecast observations across more than 680 networks.",
                    "Who is doing the certifying matters here.  <mark>The Joint Industry Committee is the broadcasters and the agencies themselves</mark> — Paramount Skydance, Fox, NBCUniversal, Warner Bros. Discovery, TelevisaUnivision, AMC Networks, E.W. Scripps and Hallmark Media on one side, with Dentsu, WPP, Horizon Media, IPG Mediabrands, Omnicom Media Group and Publicis Media on the other.  The buyers and sellers of the inventory are certifying the rulers it gets measured with.",
                    "Then the number that decides what the announcement is worth.  <mark>Nielsen still holds roughly 80 to 90 percent of transacted volume as the national television and video currency, on a 2025 estimate published by The Trade Desk's The Current.</mark>  That leaves a tenth to a fifth of transacted volume for everything else, these three included, on a single 2025 estimate.",
                    "What the piece does not say is as important as what it does.  <mark>There is no statement of what changed since the last certification, which of the 672 tests map to which kind of transaction, or whether anyone failed.</mark>  Certified means a currency can be traded on, not that it is accurate for the specific audience you are buying.",
                ],
                "flagnote": "One outlet, and the certifying body is composed of the broadcasters and media agencies who buy and sell the inventory being measured, which is the definition of self-certification rather than independent audit.  The article does not state what changed since the previous certification, what any provider failed, or how the 672 tests map to particular transaction types.  The 80 to 90 percent Nielsen share is a 2025 estimate published by a demand-side advertising platform, not a current audited figure.  Nothing in the certification addresses creator or social video measurement at all.",
                "so_what": "The currency you transact on decides what a guarantee means, and this certification only establishes that a number is tradeable, not that it is right for your audience.  With Nielsen still carrying the overwhelming majority of what actually changes hands, a certified alternative in your contract is a negotiating position rather than a market standard, and the party proposing it usually knows which of the two makes their inventory look better.",
                "do_this": "If you have fourth-quarter or 2027 video guarantees still open, get the certification scope in writing before you accept an alternative currency as the basis of the deal, and ask specifically which tests the provider passed for the transaction type and the audience segment you are actually buying.  Then ask for the same campaign measured both ways for one flight, and keep the gap as your own reference number.",
            },
        ],
    },
    {
        "id": "format", "name": "FORMAT LAB", "page": "pg. 08",
        "note": "how the thing gets made, and when",
        "items": [
            {
                "title": "Somebody tagged 11,223 thumbnails from 1,043 channels, and the covers on each channel's best video differed from its ordinary ones by two percentage points",
                "hook": "The shocked face is on 11 percent of the covers that show a face, under 8 percent of all of them.  And no single design feature predicted a channel's best video.",
                "open": True,
                "stamps": [
                    ("GLOBENEWSWIRE · 17 SEP", "https://www.globenewswire.com/news-release/2026/09/17/3364341/0/en/thumbnail-bench-publishes-study-of-11-223-youtube-thumbnails-the-shocked-face-is-a-myth.html"),
                    ("NET INFLUENCER · 21 SEP", "https://www.netinfluencer.com/youtube-thumbnail-study-of-100k-channels-finds-shocked-faces-on-just-1-in-10-covers/"),
                ],
                "body": [
                    "The study is from Thumbnail Bench, published on 17 September and picked up on the 21st.  <mark>1,043 channels with 100,000 or more subscribers across 11 niches, capped at 100 channels per niche, the 15 most recent uploads of each as of 15 September — 11,223 long-form thumbnails.</mark>  Shorts were filtered out, along with television networks, record labels, children's content and clip compilations.  21 design features were tagged on each cover.",
                    "The census first, because it is useful on its own.  <mark>Faces on 71 percent of covers.  Among the 7,970 thumbnails that show a face: neutral 35 percent, happy 32 percent, shocked 11 percent.</mark>  By niche, faces appear on 89 percent of vlog and fitness covers and 88 percent of finance, but only 47 percent of gaming — of the niches the study breaks out, gaming is the only one where a face is the minority choice.  Note that the trade write-up headlines the shocked-face figure as one in ten covers, which is a garbling: 11 percent is the share among the covers that show a face.  <mark>Text appears on 77 percent, at a median of four words; 23 percent carry no text at all, rising to 51 percent in food.</mark>  36 percent of thumbnails with text repeat half or more of the video's title.",
                    "Channel size changes the habits.  <mark>Channels above 2 million subscribers go text-free on 32 percent of covers against 19 percent for channels under 500,000, and use arrows and screenshots at half the rate of those smaller channels.</mark>",
                    "Now the finding, in their words: no single design feature predicts a channel's best video.  <mark>The only two that moved at all were faces, slightly more common on a channel's best video, and title repetition, slightly less common — each by two percentage points.</mark>  Not two times.  Two points.",
                    "And the caveat, which the study publishes itself and which you should carry with the number wherever you take it: <mark>no click-through rates were used, because they are private to each channel.</mark>  The performance proxy was views per day, which is contaminated by the title, the topic, the upload time and the recommendation system.  Tagging was done by a vision model against a fixed schema, with 98 percent agreement against a second run on a pilot.",
                ],
                "flagnote": "Thumbnail Bench sells artificial intelligence thumbnail generation, so the company whose product is thumbnail decisions has published the study finding that thumbnail features barely separate winners from the field.  That cuts against its own commercial interest in one direction and towards its product in another, and it is not disclosed in the coverage.  No click-through data was used at all — the study says so — and views per day is a proxy shaped mostly by things that are not the thumbnail, so this measures prevalence and correlation, never causation.  The tagging was done by a vision model with a pilot self-consistency check and no human inter-rater baseline.  It was distributed as a press release and we found one trade outlet covering it.",
                "so_what": "Two percentage points is the size of the thing a thumbnail review argues about for forty minutes.  That does not mean covers are irrelevant — a bad one clearly costs you, and faces do help slightly — it means the cover behaves like a threshold you clear rather than a lever you tune, and the tuning hours are being spent on the wrong variable.  The honest limit is that nobody outside a channel can see click-through rate, so the strongest claim available is about what top channels actually do, not what works.",
                "do_this": "Cap thumbnail review at one round this week and move the recovered time into the title and the first ten seconds.  Brief to the niche convention rather than to instinct — a face for finance, where 88 percent of covers carry one; no text in food, where 51 percent already have none; and a face treated as optional in gaming, where fewer than half do — then keep your own before-and-after click-through figures from Studio on every cover you change, because that is the only data on this that will ever be yours.",
            },
        ],
    },
]

FORECAST = [
    {
        "confidence": "LIKELY",
        "window": "by 30 June 2027",
        "headline": "A brand asks its creator partners what share of their revenue it represents, and writes the answer into the contract",
        "body": "Mango Street closing after an anchor advertiser left is the cleanest demonstration yet that a sponsorship can be the business rather than a line in it, and the first brand to read that properly will realise the question cuts both ways — it is leverage on price and term, and it is also a dependency register.  The mechanism that makes this likely is that it costs nothing to ask and the answer is immediately useful to procurement, which is the kind of change that spreads without anybody championing it.  Expect it to appear first as a disclosure question in a partnership questionnaire rather than as a public policy.  The reason it might not happen is that creators have every incentive to refuse, and the ones who most need the deal are the ones least able to say no safely.",
        "do": "Add one line to your creator partnership questionnaire asking what proportion of channel revenue the deal represents, and start collecting the answers now, so that in six months you have a register rather than an anecdote.",
    },
    {
        "confidence": "LIKELY",
        "window": "by 31 March 2027",
        "headline": "A European advertiser buys creator video on guaranteed delivery with a make-good clause, and books it as media rather than influencer spend",
        "body": "Arcade holding a YouTube Partner Sales licence that enables guaranteed delivery is the piece that has been missing, because the thing stopping large budgets moving into creator video has never been belief in the audience — it has been that nobody would guarantee it, which keeps the money in a discretionary pot with a small ceiling.  Once one advertiser signs a guaranteed creator buy with a remedy attached, the internal argument changes from taste to procurement, and procurement moves faster than taste.  Expect the first one to be a brand already named as a partner rather than a new entrant.  The reason it could stall is that guarantees require the seller to eat the shortfall, and creator supply is far less predictable than a television schedule.",
        "do": "Ask your media agency this quarter whether it can place creator video with guaranteed delivery and a make-good, and if it can, run one small guaranteed buy now so your finance team sees the paperwork before the budget conversation.",
    },
    {
        "confidence": "WATCH CLOSELY",
        "window": "by 31 December 2027",
        "headline": "A measurement company starts publishing channel count and duration beside every watch-time figure, because a buyer refuses one without them",
        "body": "Three releases landed from the same measurement company on one day, and one of them reported growth across 290 broadcasting channels where the previous edition counted 133 — which means a coverage change and an audience change are being reported as one number.  The pressure to fix this will not come from the measurement companies, who sell the releases, but from a large buyer who gets caught paying against an inflated number and says so publicly.  The change is cheap to make and hard to argue against once anyone asks for it out loud.  It stays a watch rather than a likely because the current arrangement suits both the rights holders and the measurement vendors, and the buyers who notice tend to raise it privately to protect the relationship.",
        "do": "Put peak concurrents, average concurrents, broadcast duration and channel count into your own reporting template as four required fields, and leave them visibly blank when a seller will not supply them.",
    },
    {
        "confidence": "LONG SHOT",
        "window": "by 31 December 2027",
        "headline": "A brand publishes real click-through data from its own thumbnail tests, and it contradicts the vendor studies",
        "body": "Thumbnail studies keep hitting the same wall, stated openly in the one published on 17 September: click-through rate is private to each channel, so the research has to use views per day as a proxy and can only report what channels do rather than what works.  The only organisations that can close that hole are the ones sitting on the data, which means a brand with a large owned channel and nothing to sell in the thumbnail business.  Somebody in that position will eventually publish, because being the source of the only real numbers on a subject everybody argues about is cheap authority.  It stays a long shot because the same data tells competitors what works on your audience, and most brands would rather keep the edge than have the citation.",
        "do": "Start logging click-through rate in Studio against a one-line description of each thumbnail change you make, so that if you ever want to publish, or just settle an internal argument, you have a year of your own evidence.",
    },
]

TLDR = [
    "Mango Street is closing after ten years, nearly 400 videos, a million subscribers and more than 60 million views, and the first reason its founders gave was that Squarespace is pulling out before year-end — with no revenue figures published, so nobody outside knows what share of the business it was.  Ask every creator partner this week what proportion of their channel revenue your deal represents, treat anything above roughly a third as a dependency rather than a placement, and stagger those renewals apart.",
    "Arcade, the Sidemen's commercial business, presented its creator slate to more than 150 advertisers in London on 17 September and its Creator Access division holds a YouTube Partner Sales licence that enables guaranteed ad delivery against its roster.  Ask your creator partners and your agency in writing whether they can guarantee delivery, under what licence and with what make-good, and move any inventory where the answer is yes onto your paid video budget.",
    "Somebody tagged 11,223 thumbnails from 1,043 channels over 100,000 subscribers, and the covers on each channel's best video differed from its ordinary ones by two percentage points on the only two features that moved at all, with the shocked face appearing on 11 percent of the covers that show a face rather than on most covers — and no click-through data was used, because it is private to each channel.  Cap thumbnail review at one round, put the time into the title and first ten seconds, and keep your own click-through figures on every cover you change.",
    "Google's new Sidemen deal writes Gemini into the survival challenge as the thing the group has to use to solve it, across five videos split between one flagship episode on the main channel and four on the secondary channel five weeks later, and it is Google's second large creator deal in a month after MrBeast on 2 September.  Specify in your next creator brief whether the product is a removable block or a rule of the format, and lock your brand notes before the shoot if you choose the format version.",
    "Rocket League peaked at 704,608 concurrent viewers, its first match above 700,000, on a semifinal rather than the final — and the release published no average concurrents, no duration and no channel count, while a second release the same day reported Free Fire growth counted across 290 broadcasting channels against 133 last edition.  Ask every seller for peak concurrents, average concurrents as an absolute, broadcast duration and channel count in writing before you respond to an offer, and price off peak alone when any are missing.",
    "A creator marketing company published a 38 times more clicks per dollar result for Badia Spices, and the ads it beat were the brand's own static images and user-tagged content, with no absolute figures on either side and clicks standing in for purchases.  Run the comparison yourself with your best static advertisement against your best creator video, same budget and audience and offer, and report clicks per dollar and cost per purchase as absolute numbers on both sides rather than as a ratio.",
    "Alex Cooper's Unwell added four YouTube shows fronted by other creators after a 500 million dollar pre-money valuation in August, and its Winter Games competition did 1.4 million views on the premiere and 1.8 million on its best episode, with a separate Summer Games edition carrying a 250,000 dollar prize pool.  Ask for per-episode views on the last three seasons before discussing price on any creator network original, and compare it against an individual creator of the same audience size.",
]

SHARE = [
    {
        "who": "JARED · CEO",
        "angle": "A photography channel with a million subscribers is closing because one advertiser left, which means the audience was never the asset and the sponsor was never buying a placement at market price.",
        "post": "A photography channel with a million subscribers and more than 60 million views is closing. The first reason its founders gave was that Squarespace is pulling out before the end of the year.\n\nTen years, nearly 400 videos, and one advertiser's renewal decision.\n\nThose figures come from The Publish Press, and one of the founders put the lesson plainly: diversify your forms of revenue, you never know when it is going to disappear.\n\nI hear audience described as the asset constantly. This is what it looks like when it is not. A million people were still there. What left was one line in somebody else's marketing budget.\n\nThere is a read in this for brands too, and it is the one I would actually take into a meeting. If your sponsorship exit closes a channel, you were not buying a media placement at market rate. You were funding the thing. And you were almost certainly paying rate-card prices for something you had far more leverage over than the rate card admits.\n\nIt cuts both ways, which is the uncomfortable part. If you are the anchor sponsor on a channel you rely on, the audience you are buying is sitting on a single point of failure, and you are it.\n\nI do not think most companies could tell you which of their creator partners that describes.",
        "why": "It takes a creator-economy shutdown story and turns it into a procurement insight a sceptical client has never considered — that the brand was paying a placement price for something closer to funding, and never used the leverage that gave it.  Image: a single invoice line struck through on flat orange, one subscriber figure beside it.",
    },
    {
        "who": "JAMES · CREATIVE DIRECTOR",
        "angle": "A study of 11,223 thumbnails found the covers on each channel's best video differed from its ordinary ones by two percentage points, which makes the thumbnail a threshold to clear rather than a lever to tune.",
        "post": "Someone tagged 11,223 YouTube thumbnails from 1,043 channels over 100,000 subscribers. Then they looked at each channel's best video and asked what its cover did differently.\n\nTwo percentage points. That was the gap.\n\nFaces turned up slightly more often on the best video. Repeated title text turned up slightly less. Nothing else separated winners from the field. The study is from Thumbnail Bench, and to their credit they say openly they could not use click-through rate, because it is private to each channel. So read it as a census of what top channels do, not proof of what works.\n\nI have sat in thumbnail reviews that ran longer than the edit review, arguing over a decision worth two percentage points. Three faces, five expressions, which eyebrow. We have all done it and I have led plenty of them.\n\nThe shocked face, incidentally, is on 11 percent of the covers that show a face. Under 8 percent of all of them. Gaming is the only niche broken out where a face appears on fewer than half.\n\nA cover is a threshold you clear, not a dial you tune. Clear it, then spend the argument on the first ten seconds instead.\n\nI am not settled on it, because I have watched a thumbnail change swing a video. Maybe the swing comes from fixing a bad one rather than perfecting a good one.",
        "why": "A creative director conceding that the craft decision his own reviews are built around accounts for two percentage points is the admission nobody expects from that chair, and he holds the caveat honestly instead of overselling the study.  Image: a grid of near-identical thumbnails, one circled, flat pink ground.",
    },
    {
        "who": "LAWRY · LEAD VIDEO EDITOR",
        "angle": "Whether a sponsor is a removable block or a load-bearing beat is decided at format stage, and it sets how much every later brand note costs in the edit.",
        "post": "Google's new Sidemen deal puts Gemini inside the challenge. They have to use it to work out how to survive the night. That is not a sponsor read sitting on top of the video. It is a beat the video is built on.\n\nWhich changes the edit completely, and none of it shows up on a media plan.\n\nA normal sponsor block sits alone on the timeline. Sixty to ninety seconds, clean in, clean out, nothing depending on it. Most editors would drop it after the first proper hook and before the first big set piece. You can lift the whole thing out and the video still works. Which is exactly why people skip it, and part of why it is cheap.\n\nWrite the product into the mechanic and you lose that. There is no block to skip. There is also no block to cut, and that is the part nobody flags. When the brand comes back with a note, you are not swapping a read. You are restructuring an act.\n\nSo whether a sponsor is removable gets decided at format stage, weeks before anyone opens a timeline, and it sets the price of every brand note for the rest of the job.\n\nI would still take the load-bearing version. I would just want somebody from the edit in the room where that gets decided.",
        "why": "It follows one commercial structure down into a concrete timeline decision — where a read sits and whether it can be lifted — and lands on the business consequence, that a format choice sets the cost of every later brand note, which only reads from inside the cut.  Image: two timelines side by side, one with a liftable block, flat black ground.",
    },
]
