ISSUE = {
    "date_iso":  "2026-09-16",
    "kicker":    "Crux Media // Wednesday 16 September 2026",
    "tagline":   "What brands did on YouTube yesterday, and whether it worked.",
    "pace":      "STEADY",
    "next_drop": "Next drop: Thursday, 06:30 MT",
}

LEAD = {
    "headline": "THE FIRST PROPER COUNT OF THE CREATOR MARKET LANDED YESTERDAY AT 1.2 BILLION POUNDS, AND IT LEAVES OUT THE MONEY THAT MAKES CREATOR VIDEO WORK",
    "deck": "IAB UK published the first dedicated measurement of what brands pay creators.  It has the market growing at 26 percent while the rest of digital advertising grows at 9.6.  It also excludes paid amplification — the media money spent pushing a creator's post at people who do not follow that creator — and the practitioners it surveyed think amplification is two to three times the size of the fee.  So the number everybody will quote is roughly a quarter of what actually gets spent.",
    "stamps": [
        ("MARKETING WEEK · 15 SEP", "https://www.marketingweek.com/uk-creator-revenue-one-billion/"),
        ("DIGIDAY · 16 SEP", "https://digiday.com/media/iab-creator-upfront-why-a-half-built-infrastructure-is-holding-back-cfo-buy-in/"),
    ],
    "body": [
        "IAB UK, the trade body for digital advertising, published this yesterday with the Institute for Advertising and Media Statistics.  It is the first time anybody has tried to measure the UK creator partnership market on its own rather than folding it into social spend.  <mark>2024 came in at 804 million pounds.  2025 at 966 million, up 20.1 percent.  2026 is projected at 1.217 billion, up 26 percent.</mark>  Digital advertising excluding creator partnerships grew 9.6 percent over the same period.  Creator partnerships worked out at about 2.4 percent of the UK's 40.5 billion pound digital ad spend in 2025.",
        "Now the line buried in the methodology.  The study does not count paid amplification.  Amplification is what it sounds like — you pay the platform to put a creator's post in front of people who do not already follow them, because the creator's own audience is not big enough to be the whole campaign.  <mark>The respondents told the researchers that amplification could potentially amount to two to three times creator partnership revenues.</mark>  That is their estimate rather than a measured figure, and it is the most useful sentence in the whole report.",
        "Run the arithmetic, because nobody in the coverage does.  If the 2026 fee pool is 1.217 billion and amplification runs at two to three times that, the real money moving through creator campaigns next year is somewhere around 3.6 to 4.9 billion pounds.  Which means that when a vendor puts 2.4 percent of digital spend on a slide, the honest figure is closer to seven to ten.  Our calculation, from their numbers.",
        "Here is the mechanism, and it decides how you write a budget.  The fee buys the licence and the face.  The media buys the delivery.  They are two separate purchases and only one of them is in the headline number, which is why creator marketing keeps getting described as cheap by people who have only ever seen the invoice with the creator's name on it.  If you build a plan off the fee, you have funded the shoot and not the distribution, and then you judge the shoot for the distribution's failure.",
        "The American half of the same problem landed in the same twenty-four hours.  The IAB ran its first Creatorfronts in New York on Tuesday, with speakers from Meta, Agentio and YouTube, and Digiday's read is that the plumbing is what is stopping big budgets.  <mark>The IAB's own projection puts US creator ad spend at 44 billion dollars this year.</mark>  James Douglas, the IAB's president, was blunt about what that means.  Improvisation is easy when a market is small.  But at 44 billion dollars, it's going to break, and it's not going to be fair and equitable and truly opportunistic for everyone.  He also asked the question the whole event was really about: what's the true cost of a creator?",
        "And what finance actually wants is smaller and duller than the pitch decks assume — a standard definition of a view, a clear answer on who owns what, and consistent pricing.  Karin Tracy, group lead of retail and ecommerce at Meta, introduced her numbers with this is the part all your CFOs care about, then cited a 19 percent reduction in cost per action from Meta's creator commerce work.  Ankur Goyal, chief marketing officer at Ultra Pouches, put the reframe more usefully than anyone: creators are the best at making the creative for your gigantic media investments on all these channels.  That is the same point the UK study makes by accident.  The creator is the production company.  The media is still the media.",
    ],
    "numbers": [
        ("1.217bn", "pounds projected UK creator partnership spend in 2026, growing at 26% against 9.6% for the rest of digital"),
        ("2-3x", "what respondents say paid amplification adds on top of the fee, and the study counts none of it"),
        ("44bn", "dollars, the IAB's own projection of US creator ad spend this year, with no agreed definition of a view"),
    ],
    "flagnote": "IAB UK is a trade body funded by the companies that sell this inventory, and a first-ever market sizing that finds a large fast-growing market serves its members and its new creator training programme.  No respondent count was disclosed for the UK study.  The two to three times amplification multiple is what respondents estimated, not something anyone measured, and the 3.6 to 4.9 billion pound range and the seven to ten percent share are our own arithmetic on top of that estimate.  The 44 billion dollar US figure is the IAB's own projection rather than an independent count.  The two headline numbers are not comparable to each other: one is UK partnership fees only, the other is US creator ad spend on a broader definition.",
    "so_what": "Everybody in this industry has spent two years arguing about whether creator marketing is worth the money, using a number that describes a quarter of the money.  The fee is the part that gets negotiated, invoiced and reported, so it is the part that gets counted, while the media weight behind the post sits in a different budget line owned by a different team and never gets attributed to the creator campaign at all.  That is how you end up with a programme that looks cheap on paper, underdelivers in the read-out, and gets cut by someone who never saw the other three quarters.",
    "do_this": "Pull your last three creator campaigns and write down two figures for each — what you paid the creator, and what you spent putting media behind their post.  Add them together and recalculate your cost per result on the combined number.  Bring that one table to your next budget conversation, because it is the only version of the arithmetic your finance team will accept once a standard definition lands.",
}

SECTIONS = [
    {
        "id": "ws", "name": "W'S", "page": "pg. 02",
        "note": "what worked, and the exact reason it worked",
        "tint": "blue",
        "items": [
            {
                "title": "94 percent of TikTok Shop's US luxury resale money comes from livestreams, because a live camera answers the one question a photograph cannot",
                "hook": "Gross merchandise value up 400 percent year on year.  Handbags and watches, invite only, five authentication partners, and almost nothing sells from a listing page.",
                "open": True,
                "stamps": [("MODERN RETAIL · 16 SEP", "https://www.modernretail.co/operations/nearly-all-luxury-resale-transactions-on-tiktok-shop-us-now-come-from-livestreams/")],
                "body": [
                    "TikTok disclosed this at its first Luxury Resale Summit in New York last week and Modern Retail reported it this morning.  <mark>Year to date, 94 percent of TikTok Shop's US luxury resale revenue comes from lives.</mark>  <mark>Luxury resale gross merchandise value — the total value of goods sold — is up 400 percent year on year</mark>, driven mostly by handbags and watches.  The category is invite only.  Sellers have to be asked in, and they have to work with one of five authentication partners: Entrupy, Legitmark, CheckCheck, Legit App and Real Authentication.",
                    "Rainee Walker, head of category for luxury resale in the US at TikTok Shop, describes the mechanism without dressing it up.  Livestreaming lets a seller have a conversation, describe the condition and show the item in real time.  That is the whole thing.",
                    "Think about what a second-hand luxury handbag actually needs in order to sell.  The buyer has two fears — that it is fake, and that the wear is worse than the photographs suggest.  A listing page can answer neither, because every photograph was chosen by the person selling it.  A live camera can, on demand, because the buyer types show me the corner and the corner appears.  The authentication partner handles the first fear.  The live handles the second, and the second is the one that kills the sale.",
                    "The sellers already run it like a broadcast schedule rather than a shop.  Fashionphile, with roughly 204,000 TikTok followers, runs a daily live called Fashionphile TV, and says TikTok Shop is 25 percent of its UK business.  Rebag has about 265,000 followers.  MyGemma has 31,000 — a small following by any standard — and says TikTok and livestream channels account for 15 to 20 percent of revenue.",
                    "The transferable part has nothing to do with luxury.  Live video wins wherever the purchase is blocked by a specific doubt that a fixed asset cannot resolve, and loses wherever the buyer already trusts the product.  Which is why brands running lives for commodity goods get nothing out of them and conclude that live does not work.  Live works exactly as well as your category's trust problem is large.",
                ],
                "flagnote": "Every figure here was disclosed by TikTok at its own summit and none of it has been independently audited.  The 400 percent gross merchandise value rise is off an undisclosed base, and a category that was invite-only and small a year ago will produce large percentage growth without much absolute volume.  The 94 percent share covers US luxury resale only, which is a curated cohort of invited sellers, not TikTok Shop as a whole.",
                "so_what": "The received wisdom is that live commerce is a sales format that has never worked in the West, and the number that just landed says it works spectacularly in one narrow case.  The case is a category where the buyer's objection is specific, physical and impossible to settle with a photograph, and where the seller can settle it in ten seconds by moving the camera.  Live is not a sales channel there.  It is an inspection channel, and the sale is just what happens after the inspection passes.",
                "do_this": "Write down the single question your customers ask most often before they buy, and decide whether a person pointing a camera could answer it in ten seconds.  If yes, book a weekly live and let people ask it.  If no, stop funding lives and put the money into the asset that does answer it.",
            },
            {
                "title": "Brands publishing six or fewer times a week got 20 percent more engagement, and the firm reporting it will not say how many brands it looked at",
                "hook": "55 percent of Instagram views now come from people who do not follow the account.  Quarterly follower growth has almost halved since 2023.",
                "stamps": [("DASH SOCIAL · 14 SEP", "https://www.globenewswire.com/news-release/2026/09/14/3361391/0/en/dash-social-reveals-where-social-media-growth-goes-next-in-2026-social-media-trends-report-issue-2.html")],
                "flagnote": "Dash Social sells the social analytics platform that measures saves, shares and what it calls brand-distinctive content, so the finding that you should post less and measure quality more is also a sales argument for its own dashboard.  It disclosed no sample size, no brand count, no post count, no date range and no platform split, which makes none of this independently checkable — treat every figure as directional rather than precise.  Total Social Impact is the vendor's own composite metric and the release does not define it.",
                "body": [
                    "Dash Social published the second issue of its 2026 trends report on Monday.  The headline finding is the one that contradicts how most brand channels are staffed.  <mark>Brands publishing six or fewer times per week generated 20 percent higher engagement than those publishing more frequently.</mark>",
                    "The two numbers that explain it sit alongside.  <mark>55 percent of Instagram views come from non-followers.  54 percent of TikTok views come through the For You Page</mark>, which is the recommendation feed rather than the following feed.  Meanwhile <mark>quarterly Instagram follower growth has fallen from 1.7 percent in 2023 to 0.9 percent in 2026</mark> while shares increased more than 50 percent.",
                    "Put those together and the mechanism is plain.  Your follower count has stopped being your distribution.  The recommendation feed is, and a recommendation feed does not care how often you post — it cares whether any individual post earns a save or a share, which are the signals it reads as this was worth keeping.  So volume stopped buying reach some time ago and nobody updated the content calendar.",
                    "What does earn those signals, according to the same report, is being identifiably yourself.  <mark>On TikTok, brand-distinctive posts generated 35 percent more saves and 18 percent more shares than generic content.  On Instagram, 23 percent more saves.</mark>  The report does not publish how it decides a post is brand-distinctive, which is the weakest link in the whole thing and worth saying out loud.",
                    "Two more figures worth holding.  <mark>Brands boosted 34 percent more organic posts year on year</mark>, and when they did, reach grew to 7.3 times the original organic audience — which is the amplification money the lead story says nobody counts, showing up in somebody else's dataset.  And <mark>roughly 77 percent of annual growth was generated outside brands' four biggest weeks</mark>, which is an argument against building the whole year around launches and holidays.",
                ],
                "so_what": "Most brand channels are still staffed and scheduled as though the follower base were the audience, which means the team's whole job is feeding a number that no longer decides who sees anything.  If more than half your views come from people who do not follow you, the unit of work is the individual post's ability to travel, not the weekly quota.  Cutting output and spending the recovered hours on making each thing stranger and more specifically yours is the same trade, measured properly.",
                "do_this": "Count what your team published in the last four weeks and, if it is more than six a week, cut next month's plan to six and hand the recovered production hours to the two ideas that were too odd or too involved to make at the old cadence.  Then check saves and shares rather than likes, because those are the signals deciding your reach.",
            },
        ],
    },
    {
        "id": "ls", "name": "L'S", "page": "pg. 03",
        "note": "what broke, and the failure mode underneath it",
        "tint": "pink",
        "items": [
            {
                "title": "Wrong audience: the US Open doubled its creator roster to about 100, then somebody stopped play with a ring light and the whole programme wore it",
                "hook": "ESPN reported that the people who halted the tennis had no credentials at all.  It made no difference to where the blame landed.",
                "stamps": [("DIGIDAY · 14 SEP", "https://digiday.com/media/what-weve-learned-from-the-creator-snafus-at-this-years-us-open/")],
                "body": [
                    "On 31 August, play was halted during Naomi Osaka's opening match after several people in a hospitality suite took flash photographs.  A video went round of somebody using a ring light for self-portraits mid-match.  ESPN reported that the individuals involved were not USTA-credentialed.  It made no difference to who got blamed.",
                    "The context is the number.  <mark>The USTA invited about 100 credentialed creators this year, nearly double the roughly 50 it invited in 2025</mark>, when the programme launched.  <mark>Digiday reports the 2025 cohort generated more than 5.5 million social engagements</mark>, which is presumably why somebody approved doubling it.",
                    "And that is the failure mode, stated plainly by the people who run these programmes for a living.  Emily Steele, chief executive and co-founder of Hummingbirds: it's the right influencers who have a relationship to what they're covering, not influencers who were dropped in for the weekend.  Beni Brown, global director of strategy at Buttermilk, on where the line is: the backlash comes when it stops being about the game.",
                    "Doubling a roster is the easiest thing in this business to do and the hardest thing to do well, because the selection criterion that made the first fifty work was relationship to the sport, and relationship to the sport does not scale by inviting more people.  The second fifty are, definitionally, the ones who cleared a lower bar.",
                    "Cayley Stonehouse, senior social media strategist at Gupta Media, described what the brief should have contained, and it is a list nobody writes: the rules of the sport, the etiquette, when and where they should be capturing content and what's expected of them while they're there.  Becky Owen, chief marketing officer at Billion Dollar Boy, says her shop mandates strict etiquette protocols that protect the craft of the athletes and the experience of paying fans.  Both descriptions are of documents that cost nothing and did not exist.",
                ],
                "flagnote": "ESPN reported that the people who caused the stoppage were not USTA-credentialed, so the incident and the creator programme are adjacent rather than the same thing, and this item should be read as being about what the association got blamed for rather than what it did.  Digiday does not say what the 5.5 million social engagements figure counts or who produced it.  The roughly 100 and roughly 50 creator counts are approximate as published.",
                "so_what": "When a creator programme doubles, the thing that made it work is usually the thing that gets diluted, because the first cohort was picked by somebody who cared and the second was picked to hit a number.  And an event audience cannot tell a credentialed creator from an uncredentialed guest with a phone — they see people behaving like the event is a backdrop, and they assign it to whoever invited them.  You inherit the behaviour of everybody who looks like your programme, not just everybody in it.",
                "do_this": "Before your next event creator programme, write a one-page conduct brief covering what the audience expects, where filming is allowed and what happens if a creator disrupts the thing they came to cover, and require a signature on it alongside the contract.  Then cap the roster at the number of people you can personally vouch for having a real relationship to the subject.",
            },
            {
                "title": "Wrong economics: 89 percent of European brands will spend more on creators, and the share running them inside a real campaign fell from 45 percent to 32",
                "hook": "Rosters expanded, budgets rose, and integration went backwards in twelve months.  About one in ten describe their creator strategy as fully joined up to the rest of their marketing.",
                "stamps": [("NET INFLUENCER · 16 SEP", "https://www.netinfluencer.com/influencer-marketing-investment-is-outpacing-the-infrastructure-built-to-manage-it-report-finds/")],
                "flagnote": "Kolsquare sells influencer marketing software and surveyed marketers on whether they intend to spend more on influencer marketing, which is a question with a predictable answer.  The sample is European only across seven markets and the findings do not automatically transfer to the US.  Everything here is stated intention and self-reported practice rather than measured outcome.",
                "body": [
                    "Kolsquare published its third annual survey with B2B International on Wednesday.  <mark>1,123 marketing decision-makers across seven European markets, fielded May and June 2026.</mark>  The spending numbers are what you would expect.  <mark>89 percent expect to increase spend over the next twelve months, up from 75 percent in 2025 and 54 percent in 2024.</mark>  <mark>60 percent already spend more than 100,000 euros a year and 36 percent more than 200,000.</mark>",
                    "The number that should stop you is the one going the other way.  <mark>32 percent connected their influencer work to integrated brand campaigns this year, down from 45 percent in 2025.</mark>  <mark>Only about 10 percent describe their strategy as fully integrated into overall marketing</mark>, and roughly 30 percent still run it as a standalone activity.  Money up, joined-up thinking down, in the same twelve months.",
                    "Where the growth actually went is the roster.  <mark>85 percent expanded theirs, and 37 percent now work with more than 100 influencers, double the 18 percent who did in 2024.</mark>  That is the axis that scales without anybody senior having to change how a campaign is planned.  You can sign fifty more creators with a procurement process.  You cannot integrate creator work into a brand campaign without someone re-writing the brief and the measurement plan, and nobody has been given that job.",
                    "Which is exactly why the measurement is where it is.  <mark>37 percent name engagement rate as their top performance indicator, and only 41 percent are extremely confident they can measure it.</mark>  Confidence is highest on views at 56 percent and impressions at 50.6, and collapses on the things that actually describe brand effect — sentiment at 22.5 percent, earned media value at 21.",
                    "Read against this morning's lead, the two studies describe the same hole from opposite ends.  One says nobody counts the media money behind creator posts.  The other says the creator work is not planned alongside the campaigns that money belongs to.  Those are the same sentence.",
                ],
                "so_what": "Creator budgets are growing on the axis that requires no organisational change, which is roster size, while the axis that would make them pay — being part of the campaign rather than next to it — actively went backwards this year.  That happens because more creators is a purchasing decision and integration is a planning decision, and planning decisions need an owner with enough seniority to rewrite a brief.  A creator line that nobody senior owns will keep growing and keep underperforming, and the two facts will never be connected in a review.",
                "do_this": "Name one person this week who owns creator work inside your next integrated campaign brief rather than alongside it, and give them sign-off on the same brief the rest of the campaign runs from.  If that person does not exist, stop adding creators to the roster until they do.",
            },
        ],
    },
    {
        "id": "moves", "name": "MOVES", "page": "pg. 04",
        "note": "platform, policy and legal changes that alter what you can make and buy",
        "items": [
            {
                "title": "OpenAI is testing an ad whose click does not go to your website",
                "hook": "The button says Chat with us and it opens a branded conversation inside ChatGPT.  Wayfair has confirmed it is in the pilot.",
                "stamps": [("DIGIDAY · 14 SEP", "https://digiday.com/marketing/openais-next-chatgpt-ad-format-click-to-chat-not-to-site/")],
                "body": [
                    "OpenAI showed this at Goldman Sachs' Communacopia conference on 8 September and Digiday reported it on Monday, having viewed the format on video.  An advertiser attaches a branded business agent to an ad.  The call to action reads Chat with us.  Clicking it does not take anybody to your site — it opens a branded chat inside ChatGPT where the person talks to your agent.",
                    "Morgan Brown, Wayfair's director of paid media, confirmed it: yes, Wayfair is participating in OpenAI's Sponsored Agent pilot to explore how conversational commerce can help customers make more informed, confident decisions.  Sarah Friar, OpenAI's chief financial officer, has described the current ChatGPT ads as a basic starting point for what AI-native advertising becomes.",
                    "Not everybody is convinced there is money in it yet.  Shamsul Chowdhury, senior vice president of paid media at Zeno Group, on AI platforms as ad channels: while they've been a hot new platform for advertisers, the ROI just hasn't been there for the most part.  Farhad Divecha, group chief executive at Accuracast, compares it to WhatsApp ads, which open lines of communication with prospects.",
                    "The production consequence is the part nobody has written down.  Every piece of brand video you have ever made ends at a landing page, and a landing page is something your team designs, writes and controls.  If the destination becomes a conversation, the asset that decides whether the click converts is not a page any more.  It is whatever your agent knows about your products, and that is a data problem sitting in a completely different department.",
                ],
                "so_what": "For twenty years the job of a video has been to earn a click to a page you built.  If the page is replaced by a conversation, then the quality of your product data — specifications, stock, returns policy, the answer to the awkward comparison question — becomes the thing your creative is handing off to.  Great film into a badly briefed agent is the same failure as great film into a broken checkout, except nobody on the creative side will see it happen.",
                "do_this": "Ask whoever owns your product data this week whether it could answer the ten questions your customers actually ask before buying, in sentences.  If it cannot, that is now a creative dependency, and it belongs on the same timeline as your next campaign rather than in a backlog.",
            },
            {
                "title": "Twitch will now grade a stream after it ends and tell the streamer what to change",
                "hook": "Personalised feedback after every broadcast, in the Creator Dashboard and by email.  Small test group, opt-in, and Twitch says it stays optional.",
                "stamps": [("TUBEFILTER · 15 SEP", "https://www.tubefilter.com/2026/09/15/twitch-generative-ai-stream-coach-creator-assistant/")],
                "body": [
                    "Twitch has built Stream Coach, a virtual assistant that gives a streamer personalised feedback after every broadcast.  From the Twitch help page: it highlights what's working, where viewers engaged most, and what to try next.  It lands in the Creator Dashboard with summary emails.",
                    "Only a small group has access while it is tested, and Twitch has been unusually careful about the framing, presumably because its previous AI rollouts drew a reaction.  From Twitch Support: Stream Coach is entirely optional.  Eligible streamers can opt out if they don't want to receive coaching, and are always in control of whether or not they use any of the feedback it provides.",
                    "It is not alone.  YouTube has launched Practice Mode for vertical live and TikTok sends LIVE best practice out through its Creator's Cut newsletter.  Every major live platform has now decided that telling creators how to stream better is a product.",
                    "Here is the part that concerns anyone buying a sponsor read.  Where viewers engaged most is, for a sponsored stream, a per-minute engagement curve — and it is the first time anybody has had one of those without paying a measurement firm for it.  Your streaming partners are about to be told, for free, which parts of their broadcast hold people.  Your sponsor segment sits somewhere on that curve.",
                ],
                "so_what": "Two things follow from a platform coaching every creator on it.  The advice converges, so the format converges, and the thing you are buying gets more uniform and less distinctive over about a year.  But in the short run there is a genuine gift here — creators are being handed engagement data about their own broadcasts that has never existed at this price, and you can simply ask them for it.",
                "do_this": "Ask each streaming partner you work with whether they have Stream Coach access, and if they do, ask them to send you what it says about the segments where your sponsor reads sat.  Then move your next read to whichever part of their broadcast the tool says holds people.",
            },
            {
                "title": "A24 has bought a horror franchise that anybody is legally allowed to copy, and its writers say nobody called them",
                "hook": "The SCP Foundation is a Creative Commons wiki.  Its contributors say a rival service could stream the finished film without paying for it.",
                "stamps": [("TUBEFILTER · 14 SEP", "https://www.tubefilter.com/2026/09/14/a24-scp-foundation-movie/")],
                "body": [
                    "Deadline broke on 11 September that A24 is partnering with Spooky Pictures and Image Nation Studios on a film adaptation of the SCP Foundation, the community horror-writing project.  Tubefilter followed on Monday with the part that matters, which is that nobody from SCP is involved.",
                    "The wiki's writers and staff put out a statement: we were not consulted or contacted regarding this film.  They add that they have been attempting to contact the filmmakers but haven't yet been successful, and that to the best of their knowledge no approach has been made in the other direction either.  Their flat assertion: A24 does not and cannot have any exclusive rights to anything related to the SCP Foundation.",
                    "The licensing is the whole story and it is not complicated.  SCP started in 2007 with a 4chan user called Moto42 posting a photograph of a real sculpture by Izumi Katō and describing it as SCP-173.  In 2008 the material moved onto a Wikidot wiki, which ships with a Creative Commons Attribution-ShareAlike 3.0 licence.  That licence lets anybody distribute the material commercially.  It also requires that anything distributed under it carries the same licence.  The writers spell out the consequence: anybody could upload a copy to YouTube, and any commercial streaming service would be free to stream the film without payment.",
                    "The reason Hollywood is here at all is that Iron Lung, Backrooms and Obsession all worked at the box office, so internet-native horror is now a category studios chase.  Community-written properties are the cheapest way into it, and they are cheap for a structural reason that a purchase does not fix.",
                ],
                "so_what": "Internet-native intellectual property is cheap to option and close to impossible to fence, because the licence that let the community build the thing is the same licence that stops anybody owning the output.  What you are actually buying is the goodwill of the people who made it, which is not a legal instrument and cannot be bought from anyone but them.  Skipping that call is the whole error here, and it costs a studio the one asset it needed.",
                "do_this": "If anybody in your business is looking at a deal on internet-native material — a wiki, a fan property, a community format — get legal to read the licence before marketing reads the pitch, and budget a real payment to the people who made it even where the licence says you do not have to.",
            },
        ],
    },
    {
        "id": "onstream", "name": "ON STREAM", "page": "pg. 05",
        "note": "the live numbers, and what they are worth to a sponsor",
        "items": [
            {
                "title": "A four-day game launch took a bigger live peak than the world final of a Blizzard esport, and much of that audience was being paid in loot to keep the stream open",
                "hook": "WARDOGS peaked at 452,600 across platforms.  The Overwatch World Cup grand final peaked at 401,000 — and held the higher average across a month.",
                "open": True,
                "stamps": [
                    ("STREAMS CHARTS · 15 SEP", "https://streamscharts.com/news/wardogs-viewership-statistics"),
                    ("ESPORTS CHARTS · 15 SEP", "https://escharts.com/news/overwatch-world-cup-2026-viewership-record"),
                    ("TWITCH BLOG · 9 SEP", "https://blog.twitch.tv/en/2026/09/09/twitch-state-of-gaming-2026/"),
                ],
                "numbers": [
                    ("452.6K", "WARDOGS peak concurrent viewers across Twitch, YouTube and Kick, 10-13 September"),
                    ("140K", "its average concurrent viewers on Twitch, against 173,100 average for the Overwatch World Cup"),
                    ("1.6bn", "of Twitch's 8.6 billion hours watched this year came from streams running a Drops reward"),
                ],
                "body": [
                    "WARDOGS is a 100-player tactical shooter from BULKHEAD, published by Team17.  It went into Steam Early Access on 10 September.  Streams Charts measured 10 to 13 September and published on Tuesday: <mark>more than 452,600 peak concurrent viewers across Twitch, YouTube and Kick, 346,100 of them inside the Twitch category, 140,000 average concurrent viewers on Twitch and 17.2 million hours watched, 13.1 million of those on Twitch.</mark>  It was the most-watched game on Twitch across launch weekend.  shroud, summit1g and TheBurntPeanut led it.  Steam concurrent players hit more than 340,000 on release day and 428,600 at the weekend peak.",
                    "The comparison ran in parallel.  Esports Charts published the Overwatch World Cup 2026 the same day: <mark>a 401,000 peak on the grand final in Anaheim on 13 September, 173,100 average concurrent viewers, 10.1 million hours watched across 20 August to 14 September and more than 600 channels</mark>, with the biggest single channel, ow_esports, at 140,500 peak.  South Korea beat Saudi Arabia 4-1 for a fourth title.  It is the highest peak the series has managed in more than eight years, up 83.7 percent on 2023 in hours watched.",
                    "Define the three numbers, because they get quoted interchangeably and they do different jobs.  Peak concurrent viewers is the most people watching at the same moment, which is demand.  Average concurrent viewers is what the ordinary minute looked like, which is what a logo on a stream is really sold against.  Hours watched is everybody's time added together, and it rises whenever something runs longer or more channels carry it.  So a four-day launch out-peaked and out-houred a twenty-six day world championship, and lost on the average.",
                    "Now the reason the launch number exists, which Streams Charts states directly: Twitch Drops were available on nearly all of these channels, giving viewers an additional incentive.  Drops pay a viewer in game items for leaving a stream open on a linked account.  It is the only mechanic in live video that pays the audience to be counted.",
                    "Twitch published the scale of that a week earlier in its State of Gaming report.  <mark>More than 8.6 billion hours watched from 1 January to 1 September, of which 1.6 billion came from Drops-enabled streams — and that Drops figure is up 46 percent on last year.</mark>  More than 7,500 Drops campaigns ran, up 20 percent, with 40 million users claiming one, up 15 percent.  That puts about 19 percent of Twitch's watch time this year on a sponsorship mechanic, which is our own arithmetic against their published totals.  The mechanic is growing considerably faster than the platform.",
                    "For scale on 452,600 people at once: that is roughly five times the capacity of Wembley Stadium, all watching a game that had been on sale for four days.",
                ],
                "flagnote": "The WARDOGS figures are Streams Charts and the tournament figures are Esports Charts, published separately.  The averages are not measured on the same basis — WARDOGS' 140,000 average is Twitch only while the tournament's 173,100 is across all its platforms — so read that comparison as indicative rather than like for like.  Neither publisher gave total airtime for the WARDOGS window, so hours watched cannot be normalised by duration.  The 19 percent Drops share of Twitch hours is our own calculation, and Twitch published no lift, conversion or brand-outcome figures alongside the Drops totals.",
                "so_what": "A launch week and a world championship produced roughly the same live peak, and only one of them had to be worth watching for the whole time.  Drops is the mechanic that closes that gap — the viewer opens the stream for the item, and the stream counts them either way.  About a fifth of everything watched on Twitch this year sat on that mechanic and it is growing at 46 percent a year, so if you buy live without asking whether it was running you are routinely paying a demand price for rented attention.",
                "do_this": "On your next live sponsorship, demand peak concurrents, average concurrent viewers, hours watched and total airtime in one table, and ask explicitly whether a rewards mechanic was running during the window being quoted.  Price a Drops-boosted window below an unincentivised one, and put the difference in writing before you sign.",
            },
        ],
    },
    {
        "id": "watch", "name": "ONE TO WATCH", "page": "pg. 06",
        "note": "one creator with momentum, and the client who should be calling",
        "items": [
            {
                "title": "Nicole Rudolph's median video is up 57 percent in five months, and the videos a brand would actually want to buy are her worst ones",
                "hook": "377,000 subscribers, 38.5 million lifetime views, and a talking-head essay about the 40-hour week beat the reveal of her 18-month house renovation by nearly four to one.",
                "open": True,
                "stamps": [("YOUTUBE · @NICOLERUDOLPH", "https://www.youtube.com/@NicoleRudolph")],
                "body": [
                    "Nicole Rudolph makes social history video essays — where clothes, houses, working hours and household objects came from, and what they say about the people who used them.  The channel started in August 2020 and carries <mark>277 videos, 377,000 subscribers as YouTube displays it, and 38,490,250 lifetime views</mark>.  She publishes weekly, on Fridays.",
                    "Across her last fifteen uploads the median is <mark>208,363 views</mark>, which is our own calculation from the counts YouTube displays.  That is about 55 percent of her subscriber count.  Most channels her size run somewhere between 10 and 30 percent, so her audience turns up at a rate that is unusual and worth paying for on its own.",
                    "The momentum is in the floor, not the ceiling.  Her previous fifteen uploads, from November 2025 to March 2026, had a median of <mark>132,848</mark>.  Same output — fifteen videos in 147 days in both windows — and the median is up <mark>56.8 percent</mark>.  The older window actually contained bigger spikes, including one at 814,498.  The newer one has nothing above 325,819 and thirteen of fifteen above 112,000.  She has turned a channel that occasionally exploded into a channel that reliably does two hundred thousand a week, which is a much easier thing to buy.",
                    "Now the part a marketer will not enjoy.  She asked nearly the same question twice, eight weeks apart.  <mark>Why is Fabric Quality so Bad Now, published 16 May, a straight history, did 237,092.  Why is Clothing Quality so Bad Now - How to Shop Better, published 11 July, the same framing plus a buying guide, did 74,305.</mark>  Same channel, same season, same subject.  Three point two times, our arithmetic.  The half that tells people what to buy is the half that dies.",
                    "It holds across the whole channel.  Grouping her last fifteen by type, the social history essays run to a <mark>median of 217,123</mark> and the house renovation, personal and shopping-advice videos to a <mark>median of 72,687</mark> — roughly three to one, and our classification.  Her Art Deco kitchen and bathroom reveal, the payoff of an eighteen-month renovation series, did <mark>75,913</mark>.  A talking-head essay about the forty-hour week did <mark>281,538</mark>.",
                    "And look at who is currently buying her.  She is represented by Viral Nation and her channel page carries a sponsorship contact.  <mark>Fourteen of her last fifteen uploads carry a paid sponsor</mark>, by our count.  The advertisers are Zocdoc five times, Incogni five times, and one each for Quince, Grow Therapy and a dog food brand.  A doctor-booking app and a data-broker opt-out service are paying for an audience that shows up in six figures for videos about textile construction and historic houses.  <mark>Zocdoc's five slots have a median of 208,363.  Incogni's five have a median of 112,671.</mark>  Same channel, same period, and one advertiser systematically bought the weaker half of it.",
                    "The last thing, and it is the useful one: carrying a sponsor does not cost her views.  Her three biggest videos in the window are all sponsored.  The format moves the number, not the advertisement sitting inside it, which means her best-performing inventory is genuinely available and nobody in her actual subject category has bought any of it.",
                ],
                "watch": {
                    "label": "TOP VIDEO, LAST 3 MONTHS",
                    "title": "The 40-hour Week was Meant to be Temporary",
                    "url": "https://www.youtube.com/watch?v=4ss002M6J9Q",
                    "meta": "281,538 views · published 25 July 2026 · 28m 31s",
                    "note": "Twenty-eight minutes of social history on how the forty-hour week was sold as a temporary measure and then stopped being one, carrying a paid sponsor read.",
                },
                "flagnote": "The medians, the format grouping, the sponsor-slot comparison and the 56.8 percent growth figure are our own calculations across her last thirty uploads, read off YouTube on 16 September, not published statistics, and the view counts have moved since.  The subscriber figure is the rounded number YouTube displays rather than an exact count.  Note also that her recent subjects have moved from fabric and popcorn ceilings into labour, birth rates and public schooling — that is where her numbers are, and it is a judgement any buyer will want to make for themselves.",
                "so_what": "This is a channel whose entire subject matter is materials, clothing and houses, monetised almost entirely by advertisers with nothing to do with any of that, while the brands who actually make those things are absent.  The reason they are absent is probably that the only thing they know how to buy is a video about their product, and on this channel that format is the worst-performing one by a factor of three.  The inventory that actually works costs the same and reaches three times as many people — it just does not carry their name in the title.",
                "do_this": "If you sell fabric, natural-fibre clothing, heritage footwear, tile, paint, fixtures or hardware, use the sponsorship contact on her channel page this week and buy a sixty to ninety second read inside an essay she was already going to make.  Do not commission her to make a video about your product, because her own numbers say that is the one thing on this channel that does not work.",
            },
        ],
    },
    {
        "id": "money", "name": "THE MONEY", "page": "pg. 07",
        "note": "the numbers that change what a thing is worth buying",
        "items": [
            {
                "title": "Google, Meta and Amazon took 56 percent of US advertising last year, and the analyst who counted expects it to rise every year for five",
                "hook": "Up from 53 percent in 2024.  Everybody else fell from 47 to 43.  Machine-directed buying was 2 percent of the US market in 2023 and is forecast at 27 by 2030.",
                "open": True,
                "stamps": [("DIGIDAY · 15 SEP", "https://digiday.com/media-buying/ad-tech-briefing-ai-is-reinforcing-big-techs-grip-on-advertising-growth/")],
                "body": [
                    "Research firm Madison and Wall put numbers on it and Digiday published them on Tuesday.  <mark>Google went from 28 percent of US ad revenue in 2024 to 29 in 2025.  Meta went from 17 to 19.  Amazon from 8 to 9.  Together, 53 percent to 56.</mark>  <mark>Everybody else fell from 47 percent to 43.</mark>  Political advertising is excluded.",
                    "Luke Stillman of Madison and Wall does not expect it to stop.  We say in the US, it's 56 percent of the total is the big three now.  It's going to be a little higher this year.  His view is that it rises a little every year for the next five, because those three outperform the market average every year.",
                    "The mechanism is the automation, and this is the figure to hold: <mark>machine-directed ad spending was about 12 percent of the US market in 2025, against 2 percent in 2023, and is forecast to reach 27 percent by 2030</mark>.  A tool that decides where your money goes can only place it inside the inventory its owner controls.  So every budget handed to one of those tools is a budget that has structurally stopped comparison-shopping, and the seller wrote the tool.",
                    "Stillman is bleak about who breaks the cycle, and specifically rules out the obvious candidate: it's certainly not going to be advertiser choice that does anything because no one's willing to make that choice.",
                    "For context on the growth everyone is fighting over, the IAB's 2026 figures have <mark>US ad spending growing 12.3 percent this year, revised up from 9.5</mark>, with social media up 16.5 percent, connected TV up 15.6 and commerce media up 13.6.",
                ],
                "flagnote": "Madison and Wall is a research and advisory firm and these are its estimates rather than audited figures.  The share numbers exclude political advertising, which is material in US election years.  No precise 2026 share was published — Stillman's a little higher is directional only.",
                "so_what": "The share of your budget where a human being chooses a specific placement is shrinking fast, and the tools taking over that choice are owned by the three companies whose share of the market keeps rising.  There is nothing sinister in it and no regulator is going to arrive.  What is worth noticing is that the one category a machine cannot buy on your behalf is the category that does not exist as purchasable inventory — your own channel, a direct creator relationship, an audience that belongs to you.",
                "do_this": "Work out what percentage of your media budget this year was placed by a machine rather than chosen by a person, and put that single number in front of your leadership alongside what you spent on owned and direct creator work.  If the second number is under a tenth of the first, you have no position outside somebody else's auction.",
            },
            {
                "title": "Steven Bartlett and the man who bought Reebok have 400 million dollars to turn creators into product companies",
                "hook": "OBSN will fund creator-led consumer brands with Authentic Brands supplying licensing and distribution.  Night has 70 million in the same race.  CAA and TPG have 250.",
                "stamps": [("TUBEFILTER · 15 SEP", "https://www.tubefilter.com/2026/09/15/steven-bartlett-obsn-invest-creator-business-jamie-salter/")],
                "body": [
                    "Steven Bartlett, who makes the Diary of a CEO podcast, and Jamie Salter, who founded Authentic Brands, launched OBSN on Tuesday — pronounced obsession — to <mark>invest 400 million dollars in creator-led companies</mark>.  Bartlett's own business was valued at <mark>425 million dollars</mark> when he took outside investment last year.  Salter's Authentic Brands is the company that scaled Reebok and manages the intellectual property of Elvis Presley and Marilyn Monroe, and it will supply product, licensing and distribution to whatever OBSN backs.",
                    "The thesis, in Bartlett's own words about an earlier investment in the podcaster Maggie Sellers Reum: now, the question is, would you buy Hot Smart Rich fragrance?  Would you buy Hot Smart Rich apparel?  What does it look like?  Does it look like Gucci?  Does it look like Prada?",
                    "It is not a lone bet.  <mark>The talent firm Night has committed 70 million dollars to the same idea.  CAA with its equity partner TPG plans to deploy 250 million.</mark>  Slow Ventures, an investor in Bartlett's business, is hunting creator-entrepreneurs in high-value categories.  Somewhere north of 700 million dollars of committed capital is now chasing the same conversion.",
                    "What all of it is buying is the same thing: the moment a creator stops being a media business with one revenue line and becomes a company that sells an object.  A creator with an audience and no product is an advertising business whose only customer is you.",
                ],
                "so_what": "This money changes your negotiating position and nobody will tell you when it does.  A creator with an equity-backed product line has a competing use for the same slot in the same video you are trying to buy, and a better alternative raises their price for everything else.  The creators most attractive to these funds are exactly the ones you want — a clear identity, a defined category, an audience that buys things — so expect the good ones to get more expensive and less available over the next two years.",
                "do_this": "Look at your three most valuable creator relationships and ask each of them what they are building that is not media.  Then decide now whether you want first refusal or category exclusivity written into the next renewal, because that clause costs almost nothing today and will be unbuyable once somebody funds them.",
            },
        ],
    },
    {
        "id": "format", "name": "FORMAT LAB", "page": "pg. 08",
        "note": "the format decision underneath the numbers",
        "items": [
            {
                "title": "The third biggest branded video on YouTube last week was a 17-minute production.  The fourth was a phone clip of a toddler, and they finished 1.4 million views apart",
                "hook": "Dude Perfect and BODYARMOR did 12,402,563.  A dad called Jesse Moncur and a balance bike company did 11,025,413.  One of those cost money.",
                "open": True,
                "stamps": [("TUBEFILTER · 15 SEP", "https://www.tubefilter.com/2026/09/15/top-5-branded-videos-mrbeast-dude-perfect-jesse-moncur/")],
                "body": [
                    "Tubefilter publishes a weekly ranking of the most-watched branded videos on YouTube, drawn from Gospel Stats, its own sponsorship tracking tool.  Any video launched with an official brand partner is eligible.  Tuesday's chart, in order.",
                    "<mark>MrBeast and Call of Duty Mobile at 104,169,846 views</mark> for Escape 100 Cops, Win 500,000 Dollars, twenty minutes long.  <mark>MrBeast 2 and Jack Link's at 23,032,812</mark> for a drive across as many states as possible in a day.  <mark>Dude Perfect and BODYARMOR at 12,402,563</mark> for School Stereotypes, seventeen minutes of sketches and trick shots that the team called the number one requested video in its history.  And then <mark>Jesse Moncur and Strider Bikes at 11,025,413</mark> — a Short, shot on a phone, of a toddler being surprised with the bike he had been asking for.",
                    "Sit with the gap between third and fourth, because it is the entire lesson.  <mark>A seventeen-minute production from one of the most established teams on YouTube beat a phone clip by 1.4 million views, which is about 11 percent.</mark>  One of those had a crew, a location, a build and a schedule.  The other had a dad, a bike and a child's face.  Strider Bikes is a balance bike company, not a national advertiser.",
                    "The honest part of the chart is the entry Tubefilter puts at the bottom on purpose.  At <mark>rank 3,398</mark> sits a BookTuber called JustAli with a full day-in-the-life carrying two sponsors, on <mark>54,380 views</mark>.  That is what a branded video normally does.  The top four are outliers, and the chart is honest enough to print an ordinary one next to them.",
                    "So the format decision is not production value against no production value.  It is whether the thing being filmed is genuinely happening.  The trick shots are staged, brilliantly, and everybody watching knows it and enjoys it on those terms.  The toddler is not staged and cannot be, and that is the only variable the cheaper video had.",
                ],
                "flagnote": "The ranking comes from Gospel Stats, which is Tubefilter's own product, so the publication is reporting on data it sells.  View counts are as published on 15 September and will have risen.  No spend figures are published for any of these videos, so the cost comparison between the third and fourth entries is inference from what is visible on screen rather than from disclosed budgets.",
                "so_what": "A branded video chart is a chart of outliers, and reading it as a plan will bankrupt you.  What it does show honestly is that the audience for a staged production and the audience for an unstaged moment are roughly the same size, and only one of those requires a budget.  The catch is that unstaged cannot be commissioned — you can only be in a position to catch it, which means filming more and planning less, and that is an uncomfortable brief to write.",
                "do_this": "Hold back a quarter of your next branded video budget and spend it on three or four unstaged phone-shot versions of the same idea, published as Shorts alongside the main production.  Compare cost per view across both within a fortnight, and let that number decide the split on the one after.",
            },
        ],
    },
]

FORECAST = [
    {
        "confidence": "LIKELY",
        "window": "by 30 June 2027",
        "headline": "A standard definition of a creator view ships, and quietly reprices half the market downwards",
        "body": "The IAB has now said in public that it is building measurement standards, its own president has said the market breaks without them, and finance teams are refusing budget until they exist.  The thing nobody is saying out loud is what happens on the day one definition wins.  Every price currently in the market was set against whichever count flattered the seller, so the campaigns that looked cheapest per view are disproportionately the ones counting most generously.  When the standard lands, those prices do not fall — the view counts do, and the cost per view triples on a spreadsheet without anybody changing anything.",
        "do": "Ask every creator seller to state in writing which view definition their price is quoted against, and keep those answers, so that when the standard lands you can tell which of your rates actually moved.",
    },
    {
        "confidence": "WATCH CLOSELY",
        "window": "by 31 December 2026",
        "headline": "Someone publishes creator fees and amplification spend side by side, and the market's reported size roughly triples overnight",
        "body": "IAB UK has now put the two-to-three-times amplification estimate on the record, which makes it quotable, and Dash Social has independently reported that brands boosted 34 percent more organic posts year on year with reach growing to 7.3 times the original audience.  The measurement that follows logically is total programme cost rather than talent fee, and whichever vendor publishes it first gets to announce that the creator market is three times bigger than everyone thought.  That is an irresistible press release and the data to build it already sits inside every large agency.",
        "do": "Start recording fee and amplification as two fields on the same line in your own reporting now, so that when somebody else publishes the comparison you already know where your business sits against it.",
    },
    {
        "confidence": "LIKELY",
        "window": "by 31 March 2027",
        "headline": "A live sponsorship gets priced with an explicit discount for a rewards mechanic running in the window",
        "body": "Twitch has now published that 1.6 billion of its 8.6 billion hours this year came from Drops-enabled streams, and a four-day game launch has just out-peaked a world championship final largely on that mechanic.  Once one buyer notices that the audience was being paid to leave the stream open, the question of what a Drops-inflated hour is worth becomes a negotiation rather than a curiosity.  The first discount will not be announced — it will show up as a rate card with two prices on it and no explanation of the difference.",
        "do": "Add one line to your live sponsorship template asking whether a rewards or Drops mechanic ran during the measured window, and start collecting the answers before anyone is embarrassed about them.",
    },
    {
        "confidence": "LONG SHOT",
        "window": "by 30 June 2027",
        "headline": "A brand publishes conversion results from an ad whose destination is a chat agent rather than a web page",
        "body": "Wayfair is in OpenAI's pilot now and has confirmed it publicly, which is the harder of the two steps.  The moment one advertiser puts a number next to a click-to-chat campaign, every creative brief in the industry acquires a line about what the agent needs to know, and product data stops being a back-office concern and becomes a production dependency.  It stays a long shot because the first credible number is as likely to be bad as good, and a bad one gets buried rather than published.",
        "do": "Write down the ten questions your customers ask before buying and check whether your product data answers them in full sentences, because that is the asset a chat destination actually runs on.",
    },
]

TLDR = [
    "IAB UK's first measurement of the creator market puts UK partnership spend at 1.217 billion pounds for 2026, up 26 percent against 9.6 percent for the rest of digital, and explicitly excludes paid amplification that respondents estimate at two to three times the fee.  Pull your last three creator campaigns, add the creator fee to the media money spent pushing their posts, and recalculate your cost per result on the combined figure before your next budget conversation.",
    "Google, Meta and Amazon took 56 percent of US ad revenue in 2025, up from 53 the year before, while machine-directed buying grew from 2 percent of the market in 2023 to about 12 in 2025 and is forecast at 27 percent by 2030.  Calculate what share of your budget was placed by a machine rather than chosen by a person, and set it next to what you spent on owned channels and direct creator relationships.",
    "94 percent of TikTok Shop's US luxury resale revenue now comes from livestreams, with gross merchandise value up 400 percent year on year, because a live camera settles a condition question that a listing photograph cannot.  Write down the question your customers ask most before buying, and if a person pointing a camera could answer it in ten seconds, book a weekly live and let people ask it.",
    "89 percent of European brands surveyed by Kolsquare expect to raise creator spend, 85 percent have expanded rosters and 37 percent now run more than 100 influencers, while the share connecting creator work to integrated brand campaigns fell from 45 percent to 32.  Name one person this week who owns creator work inside your campaign brief rather than beside it, and give them sign-off on the same brief everyone else runs from.",
    "Dash Social reports that brands publishing six or fewer times a week get 20 percent higher engagement, that 55 percent of Instagram views come from non-followers, and that quarterly follower growth has fallen from 1.7 percent in 2023 to 0.9 in 2026 — though it publishes no sample size.  Cap next month's output at six posts a week and hand the recovered hours to the two ideas that were too odd to make at the old cadence.",
    "The WARDOGS launch peaked at 452,600 concurrent viewers across platforms over four days against the Overwatch World Cup grand final's 401,000, with Twitch Drops running on nearly every channel and 1.6 billion of Twitch's 8.6 billion hours this year coming from Drops-enabled streams.  Demand peak, average, hours watched and airtime in one table on your next live buy, and ask outright whether a rewards mechanic was running in the quoted window.",
    "Nicole Rudolph's median video is up 56.8 percent in five months to 208,363 views, and by our count her social history essays run about three times her house, personal and shopping-advice videos, with a straight fabric history beating the same question plus a buying guide by 3.2 to one.  If you sell fabric, clothing, footwear, tile, paint or fixtures, buy a read inside an essay she was already making rather than commissioning a video about your product.",
]

SHARE = [
    {
        "who": "JARED · CEO",
        "angle": "Every deck quoting the creator market this week is quoting a quarter of it, and the missing three quarters is the media that makes the video work.",
        "post": "The creator market got measured properly for the first time yesterday, and the number everyone is quoting leaves out most of the money.\n\nIAB UK put UK creator partnership spend at 1.217 billion pounds for 2026, growing 26% while the rest of digital advertising grows 9.6%. Good number. Real growth.\n\nBut the study counts what brands pay creators. It does not count paid amplification, which is the media money you spend pushing that creator's post at people who don't already follow them.\n\nThe practitioners they surveyed estimated amplification at two to three times the fee.\n\nSo the real figure is somewhere near four billion, and the 2.4% of digital spend everyone will put on a slide is closer to 7 or 10%.\n\nI think this explains an argument I keep having. Somebody says creator work is cheap, somebody else says it underperforms, and both are looking at the same invoice.\n\nThe fee buys the licence and the face. The media buys the delivery. They arrive from different budgets, get approved by different people, and only one ends up in the creator campaign's report.\n\nSo the campaign gets judged on the shoot while the distribution sits in a column nobody attributes.\n\nI don't think anyone is being dishonest. Fees get invoiced and media gets planned, and the two have never had to be added together before.\n\nThey do now.",
        "why": "It takes the week's most quotable creator-market number and argues it is 25 percent of the real one, which reframes the cheap-versus-underperforming argument every marketing leader has had.  Image: halftone cutout of a single paper invoice, flat bright blue ground, one big off-white 4X.",
    },
    {
        "who": "JAMES · CREATIVE DIRECTOR",
        "angle": "The third and fourth biggest branded videos on YouTube last week finished 11 percent apart, and only one of them had a crew.",
        "post": "Last week's third biggest branded video on YouTube was a 17-minute Dude Perfect production. 12,402,563 views.\n\nFourth was a phone clip of a toddler getting a bike. 11,025,413 views. Figures from Tubefilter's weekly branded chart.\n\nAn 11% gap. One had a crew, a location, a build and a schedule. The other had a dad called Jesse Moncur, a Strider balance bike, and a kid's face.\n\nI make my living arguing for the budget that makes the first one possible, so I want to be careful here.\n\nThe Dude Perfect video is excellent. It's staged, everybody watching knows it's staged, and the craft is the entire pleasure. That's a legitimate thing to sell and I'd sell it again.\n\nBut the thing the cheap video had is the one thing money cannot buy back. It was actually happening. The kid's reaction could not have been directed into existence by anyone in my job.\n\nWhich leaves me somewhere uncomfortable. You can commission staged. You cannot commission real. You can only be filming when it happens, which means shooting far more than you plan and accepting that most of it is nothing.\n\nThat is a terrible brief to write and I don't know how to price it.\n\nI still think most brands should make the expensive one. I'm just less sure than I was on Monday that it's the expensive part doing the work.",
        "why": "A creative director conceding on the record that an 11 percent gap separated his own discipline from a phone clip, and that the variable was not craft, is the admission that makes it land.  Image: halftone cutout of a child's balance bike, flat bright blue ground, one big off-white 11.",
    },
    {
        "who": "LAWRY · LEAD VIDEO EDITOR",
        "angle": "Adding a buying guide to the end of an explainer cost the same creator two thirds of her audience, and the damage was done by the title before the edit started.",
        "post": "A creator I've been watching asked nearly the same question twice, eight weeks apart, and the second version did a third of the views.\n\nNicole Rudolph, 377,000 subscribers, social history essays. May: \"Why is Fabric Quality so Bad Now?\"  237,092 views. July: \"Why is Clothing Quality so Bad Now - How to Shop Better.\"  74,305.\n\nSame channel, same subject, same season. 3.2 times apart.\n\nThe only structural difference is that the second one has a buying guide bolted on the end.\n\nAnd this is an edit problem more than a strategy problem. When you add an advice section, it goes in the title, because otherwise nobody knows it's there. The moment it's in the title, the twenty minutes before it stop being the video. They become the thing standing between the viewer and the list.\n\nMost editors would put the advice last. It feels like a payoff. You build the history, then hand people the useful part.\n\nBut you've already told them the useful part is coming, so you've turned your own best material into a queue.\n\nI don't think the fix is cutting the advice. It's probably not promising it. Let the list be a surprise at minute twenty-two and the twenty-two minutes are still an essay.\n\nThough that means a worse title, and a worse title has its own cost. I don't know where that trade lands.",
        "why": "It is a decision an editor genuinely makes — where the advice section sits and whether the title announces it — and it turns out to have been worth 160,000 views on one video.  Image: halftone cutout of a folded tape measure, flat bright blue ground, one big off-white 3.2X.",
    },
]
